/*
Run this script on:

        (localdb)\MSSQLLocalDB.CSETWeb11100    -  This database will be modified

to synchronize it with:

        (localdb)\MSSQLLocalDB.CSETWeb11200

You are recommended to back up your database before running this script

Script created by SQL Compare version 14.6.10.20102 from Red Gate Software Ltd at 6/7/2022 10:31:30 AM

*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL Serializable
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CS_SITE_INFORMATION_ASSESSMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CSI_ORGANIZATION_DEMOGRAPHICS_CIST_CSI_STAFF_COUNTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CSI_ORGANIZATION_DEMOGRAPHICS_CIST_CSI_STAFF_COUNTS_2]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[CIST_CSI_SERVICE_COMPOSITION]'
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_COMPOSITION] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_COMPOSITION_ASSESSMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_COMPOSITION] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_COMPOSITION_CIST_CSI_DEFINING_SYSTEMS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS]'
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS_CIST_CSI_DEFINING_SYSTEMS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS_CIST_CSI_SERVICE_COMPOSITION]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CS_DEMOGRAPHICS_ASSESSMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_DEMOGRAPHICS_CIST_CSI_BUDGET_BASES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_DEMOGRAPHICS_CIST_CSI_CUSTOMER_COUNTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_DEMOGRAPHICS_CIST_CSI_STAFF_COUNTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_DEMOGRAPHICS_CIST_CSI_STAFF_COUNTS_2]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [FK_CIST_CSI_SERVICE_DEMOGRAPHICS_CIST_CSI_USER_COUNTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_BUDGET_BASES]'
GO
ALTER TABLE [dbo].[CIST_CSI_BUDGET_BASES] DROP CONSTRAINT [PK_CIST_CSI_BUDGET_BASES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_CUSTOMER_COUNTS]'
GO
ALTER TABLE [dbo].[CIST_CSI_CUSTOMER_COUNTS] DROP CONSTRAINT [PK_CIST_CSI_CUSTOMER_AMOUNTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_DEFINING_SYSTEMS]'
GO
ALTER TABLE [dbo].[CIST_CSI_DEFINING_SYSTEMS] DROP CONSTRAINT [PK_CIST_CSI_DEFINING_SYSTEMS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [PK_CIST_CS_SITE_INFORMATION]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_SERVICE_COMPOSITION]'
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_COMPOSITION] DROP CONSTRAINT [PK_CIST_CSI_SERVICE_COMPOSITION]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS]'
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] DROP CONSTRAINT [PK_CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [PK_CIST_CS_DEMOGRAPHICS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_STAFF_COUNTS]'
GO
ALTER TABLE [dbo].[CIST_CSI_STAFF_COUNTS] DROP CONSTRAINT [PK_CIST_CSI_STAFF_AMOUNTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_USER_COUNTS]'
GO
ALTER TABLE [dbo].[CIST_CSI_USER_COUNTS] DROP CONSTRAINT [PK_CIST_CSI_USER_AMOUNTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_CUSTOMER_COUNTS]'
GO
ALTER TABLE [dbo].[CIST_CSI_CUSTOMER_COUNTS] DROP CONSTRAINT [DF_CIST_CSI_CUSTOMER_COUNTS_Sequence]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Motivation_CRR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Motivation_RRAP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Motivation_Organization_Request]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Motivation_Law_Enforcement_Request]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Motivation_Direct_Threats]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Motivation_Special_Event]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Motivation_Other]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Completed_For_SLTT]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Completed_For_Federal]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_SITE_INFORMATION_Completed_For_National_Special_Event]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS] DROP CONSTRAINT [DF_CIST_CS_DEMOGRAPHICS_Multi_Site]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[CIST_CSI_USER_COUNTS]'
GO
ALTER TABLE [dbo].[CIST_CSI_USER_COUNTS] DROP CONSTRAINT [DF_CIST_CSI_USER_COUNTS_Sequence]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping index [IX_CIST_CSI_DEFINING_SYSTEMS] from [dbo].[CIST_CSI_DEFINING_SYSTEMS]'
GO
DROP INDEX [IX_CIST_CSI_DEFINING_SYSTEMS] ON [dbo].[CIST_CSI_DEFINING_SYSTEMS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_BUDGET_BASES]', N'CIS_CSI_BUDGET_BASES', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_CUSTOMER_COUNTS]', N'CIS_CSI_CUSTOMER_COUNTS', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_DEFINING_SYSTEMS]', N'CIS_CSI_DEFINING_SYSTEMS', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_ORGANIZATION_DEMOGRAPHICS]', N'CIS_CSI_ORGANIZATION_DEMOGRAPHICS', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_SERVICE_COMPOSITION]', N'CIS_CSI_SERVICE_COMPOSITION', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS]', N'CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_SERVICE_DEMOGRAPHICS]', N'CIS_CSI_SERVICE_DEMOGRAPHICS', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_STAFF_COUNTS]', N'CIS_CSI_STAFF_COUNTS', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_rename N'[dbo].[CIST_CSI_USER_COUNTS]', N'CIS_CSI_USER_COUNTS', N'OBJECT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CSI_BUDGET_BASES] on [dbo].[CIS_CSI_BUDGET_BASES]'
GO
ALTER TABLE [dbo].[CIS_CSI_BUDGET_BASES] ADD CONSTRAINT [PK_CIS_CSI_BUDGET_BASES] PRIMARY KEY CLUSTERED ([Budget_Basis])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CSI_CUSTOMER_AMOUNTS] on [dbo].[CIS_CSI_CUSTOMER_COUNTS]'
GO
ALTER TABLE [dbo].[CIS_CSI_CUSTOMER_COUNTS] ADD CONSTRAINT [PK_CIS_CSI_CUSTOMER_AMOUNTS] PRIMARY KEY CLUSTERED ([Customer_Count])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CSI_DEFINING_SYSTEMS] on [dbo].[CIS_CSI_DEFINING_SYSTEMS]'
GO
ALTER TABLE [dbo].[CIS_CSI_DEFINING_SYSTEMS] ADD CONSTRAINT [PK_CIS_CSI_DEFINING_SYSTEMS] PRIMARY KEY CLUSTERED ([Defining_System_Id])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CS_SITE_INFORMATION] on [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [PK_CIS_CS_SITE_INFORMATION] PRIMARY KEY CLUSTERED ([Assessment_Id])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CSI_SERVICE_COMPOSITION] on [dbo].[CIS_CSI_SERVICE_COMPOSITION]'
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_COMPOSITION] ADD CONSTRAINT [PK_CIS_CSI_SERVICE_COMPOSITION] PRIMARY KEY CLUSTERED ([Assessment_Id])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] on [dbo].[CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS]'
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] ADD CONSTRAINT [PK_CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] PRIMARY KEY CLUSTERED ([Assessment_Id], [Defining_System_Id])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CS_DEMOGRAPHICS] on [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [PK_CIS_CS_DEMOGRAPHICS] PRIMARY KEY CLUSTERED ([Assessment_Id])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CSI_STAFF_AMOUNTS] on [dbo].[CIS_CSI_STAFF_COUNTS]'
GO
ALTER TABLE [dbo].[CIS_CSI_STAFF_COUNTS] ADD CONSTRAINT [PK_CIS_CSI_STAFF_AMOUNTS] PRIMARY KEY CLUSTERED ([Staff_Count])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_CIS_CSI_USER_AMOUNTS] on [dbo].[CIS_CSI_USER_COUNTS]'
GO
ALTER TABLE [dbo].[CIS_CSI_USER_COUNTS] ADD CONSTRAINT [PK_CIS_CSI_USER_AMOUNTS] PRIMARY KEY CLUSTERED ([User_Count])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [IX_CIS_CSI_DEFINING_SYSTEMS] on [dbo].[CIS_CSI_DEFINING_SYSTEMS]'
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIS_CSI_DEFINING_SYSTEMS] ON [dbo].[CIS_CSI_DEFINING_SYSTEMS] ([Defining_System])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CS_SITE_INFORMATION_ASSESSMENTS] FOREIGN KEY ([Assessment_Id]) REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CSI_ORGANIZATION_DEMOGRAPHICS_CIS_CSI_STAFF_COUNTS] FOREIGN KEY ([Cybersecurity_IT_ICS_Staff_Count]) REFERENCES [dbo].[CIS_CSI_STAFF_COUNTS] ([Staff_Count]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CSI_ORGANIZATION_DEMOGRAPHICS_CIS_CSI_STAFF_COUNTS_2] FOREIGN KEY ([IT_ICS_Staff_Count]) REFERENCES [dbo].[CIS_CSI_STAFF_COUNTS] ([Staff_Count])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[CIS_CSI_SERVICE_COMPOSITION]'
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_COMPOSITION] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_COMPOSITION_ASSESSMENTS] FOREIGN KEY ([Assessment_Id]) REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_COMPOSITION] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_COMPOSITION_CIS_CSI_DEFINING_SYSTEMS] FOREIGN KEY ([Primary_Defining_System]) REFERENCES [dbo].[CIS_CSI_DEFINING_SYSTEMS] ([Defining_System_Id]) ON UPDATE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS]'
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS_CIS_CSI_DEFINING_SYSTEMS] FOREIGN KEY ([Defining_System_Id]) REFERENCES [dbo].[CIS_CSI_DEFINING_SYSTEMS] ([Defining_System_Id]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS_CIS_CSI_SERVICE_COMPOSITION] FOREIGN KEY ([Assessment_Id]) REFERENCES [dbo].[CIS_CSI_SERVICE_COMPOSITION] ([Assessment_Id]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CS_DEMOGRAPHICS_ASSESSMENTS] FOREIGN KEY ([Assessment_Id]) REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_DEMOGRAPHICS_CIS_CSI_BUDGET_BASES] FOREIGN KEY ([Budget_Basis]) REFERENCES [dbo].[CIS_CSI_BUDGET_BASES] ([Budget_Basis]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_DEMOGRAPHICS_CIS_CSI_CUSTOMER_COUNTS] FOREIGN KEY ([Customers_Count]) REFERENCES [dbo].[CIS_CSI_CUSTOMER_COUNTS] ([Customer_Count]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_DEMOGRAPHICS_CIS_CSI_STAFF_COUNTS] FOREIGN KEY ([IT_ICS_Staff_Count]) REFERENCES [dbo].[CIS_CSI_STAFF_COUNTS] ([Staff_Count]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_DEMOGRAPHICS_CIS_CSI_STAFF_COUNTS_2] FOREIGN KEY ([Cybersecurity_IT_ICS_Staff_Count]) REFERENCES [dbo].[CIS_CSI_STAFF_COUNTS] ([Staff_Count])
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [FK_CIS_CSI_SERVICE_DEMOGRAPHICS_CIS_CSI_USER_COUNTS] FOREIGN KEY ([Authorized_Non_Organizational_User_Count]) REFERENCES [dbo].[CIS_CSI_USER_COUNTS] ([User_Count]) ON UPDATE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding constraints to [dbo].[CIS_CSI_CUSTOMER_COUNTS]'
GO
ALTER TABLE [dbo].[CIS_CSI_CUSTOMER_COUNTS] ADD CONSTRAINT [DF_CIS_CSI_CUSTOMER_COUNTS_Sequence] DEFAULT ((0)) FOR [Sequence]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding constraints to [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Motivation_CRR] DEFAULT ((0)) FOR [Motivation_CRR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Motivation_RRAP] DEFAULT ((0)) FOR [Motivation_RRAP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Motivation_Organization_Request] DEFAULT ((0)) FOR [Motivation_Organization_Request]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Motivation_Law_Enforcement_Request] DEFAULT ((0)) FOR [Motivation_Law_Enforcement_Request]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Motivation_Direct_Threats] DEFAULT ((0)) FOR [Motivation_Direct_Threats]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Motivation_Special_Event] DEFAULT ((0)) FOR [Motivation_Special_Event]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Motivation_Other] DEFAULT ((0)) FOR [Motivation_Other]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Completed_For_SLTT] DEFAULT ((0)) FOR [Completed_For_SLTT]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Completed_For_Federal] DEFAULT ((0)) FOR [Completed_For_Federal]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[CIS_CSI_ORGANIZATION_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_SITE_INFORMATION_Completed_For_National_Special_Event] DEFAULT ((0)) FOR [Completed_For_National_Special_Event]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding constraints to [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[CIS_CSI_SERVICE_DEMOGRAPHICS] ADD CONSTRAINT [DF_CIS_CS_DEMOGRAPHICS_Multi_Site] DEFAULT ((0)) FOR [Multi_Site]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding constraints to [dbo].[CIS_CSI_USER_COUNTS]'
GO
ALTER TABLE [dbo].[CIS_CSI_USER_COUNTS] ADD CONSTRAINT [DF_CIS_CSI_USER_COUNTS_Sequence] DEFAULT ((0)) FOR [Sequence]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
-- This statement writes to the SQL Server Log so SQL Monitor can show this deployment.
IF HAS_PERMS_BY_NAME(N'sys.xp_logevent', N'OBJECT', N'EXECUTE') = 1
BEGIN
    DECLARE @databaseName AS nvarchar(2048), @eventMessage AS nvarchar(2048)
    SET @databaseName = REPLACE(REPLACE(DB_NAME(), N'\', N'\\'), N'"', N'\"')
    SET @eventMessage = N'Redgate SQL Compare: { "deployment": { "description": "Redgate SQL Compare deployed to ' + @databaseName + N'", "database": "' + @databaseName + N'" }}'
    EXECUTE sys.xp_logevent 55000, @eventMessage
END
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	PRINT 'The database update failed'
END
GO
