SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL Serializable
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[ASSESSMENT_IRP]'
GO
ALTER TABLE [dbo].[ASSESSMENT_IRP] DROP CONSTRAINT [FK__Assessmen__Asses__5DEAEAF5]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[ASSESSMENT_IRP] DROP CONSTRAINT [FK__Assessmen__IRP_I__5EDF0F2E]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[ASSESSMENT_IRP_HEADER]'
GO
ALTER TABLE [dbo].[ASSESSMENT_IRP_HEADER] DROP CONSTRAINT [FK__ASSESSMEN__ASSES__658C0CBD]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[ASSESSMENT_IRP_HEADER] DROP CONSTRAINT [FK__ASSESSMEN__IRP_H__668030F6]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_ASSESSMENT_CONTACTS_FACILITATOR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_ASSESSMENT_CONTACTS_POINTOFCONTACT]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_ASSESSMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS_ASSET_VALUES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS_ORGANIZATION_TYPE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS_SIZE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_SECTOR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [FK_DEMOGRAPHICS_SECTOR_INDUSTRY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[DEMOGRAPHICS_ASSET_VALUES]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS_ASSET_VALUES] DROP CONSTRAINT [FK_DEMOGRAPHICS_ASSET_VALUES_APP_CODE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[DOCUMENT_FILE]'
GO
ALTER TABLE [dbo].[DOCUMENT_FILE] DROP CONSTRAINT [FK_DOCUMENT_FILE_DEMOGRAPHICS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_ASSESSMENT_VALUES]'
GO
ALTER TABLE [dbo].[FINANCIAL_ASSESSMENT_VALUES] DROP CONSTRAINT [FK_FINANCIAL_ASSESSMENT_VALUES_ASSESSMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_ASSESSMENT_VALUES] DROP CONSTRAINT [FK_FINANCIAL_ASSESSMENT_VALUES_FINANCIAL_ATTRIBUTES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_DETAILS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DETAILS] DROP CONSTRAINT [FK_FINANCIAL_DETAILS_FINANCIAL_GROUPS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [FK_FINANCIAL_DOMAIN_FILTERS_ASSESSMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [FK_FINANCIAL_DOMAIN_FILTERS_FINANCIAL_DOMAINS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_DOMAIN_FILTERS_V2]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS_V2] DROP CONSTRAINT [FK_FINANCIAL_DOMAIN_FILTERS_V2_FINANCIAL_DOMAINS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS_V2] DROP CONSTRAINT [FK_FINANCIAL_DOMAIN_FILTERS_V2_FINANCIAL_MATURITY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_FFIEC_MAPPINGS]'
GO
ALTER TABLE [dbo].[FINANCIAL_FFIEC_MAPPINGS] DROP CONSTRAINT [FK_FINANCIAL_FFIEC_MAPPINGS_FINANCIAL_DETAILS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_GROUPS]'
GO
ALTER TABLE [dbo].[FINANCIAL_GROUPS] DROP CONSTRAINT [FK_FINANCIAL_GROUPS_FINANCIAL_ASSESSMENT_FACTORS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_GROUPS] DROP CONSTRAINT [FK_FINANCIAL_GROUPS_FINANCIAL_COMPONENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_GROUPS] DROP CONSTRAINT [FK_FINANCIAL_GROUPS_FINANCIAL_DOMAINS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_GROUPS] DROP CONSTRAINT [FK_FINANCIAL_GROUPS_FINANCIAL_MATURITY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_HOURS]'
GO
ALTER TABLE [dbo].[FINANCIAL_HOURS] DROP CONSTRAINT [FK_FINANCIAL_HOURS_ASSESSMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_HOURS] DROP CONSTRAINT [FK_FINANCIAL_HOURS_FINANCIAL_HOURS_COMPONENT]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_HOURS] DROP CONSTRAINT [FK_FINANCIAL_HOURS_FINANCIAL_REVIEWTYPE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_HOURS_COMPONENT]'
GO
ALTER TABLE [dbo].[FINANCIAL_HOURS_COMPONENT] DROP CONSTRAINT [FK_FINANCIAL_HOURS_COMPONENT_FINANCIAL_DOMAINS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_QUESTIONS]'
GO
ALTER TABLE [dbo].[FINANCIAL_QUESTIONS] DROP CONSTRAINT [FK_FINANCIAL_QUESTIONS_FINANCIAL_DETAILS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_QUESTIONS] DROP CONSTRAINT [FK_FINANCIAL_QUESTIONS_NEW_QUESTION]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_REQUIREMENTS]'
GO
ALTER TABLE [dbo].[FINANCIAL_REQUIREMENTS] DROP CONSTRAINT [FK_FINANCIAL_REQUIREMENTS_FINANCIAL_DETAILS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINANCIAL_REQUIREMENTS] DROP CONSTRAINT [FK_FINANCIAL_REQUIREMENTS_NEW_REQUIREMENT]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[FINANCIAL_TIERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_TIERS] DROP CONSTRAINT [FK_FINANCIAL_TIERS_FINANCIAL_DETAILS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[HYDRO_DATA]'
GO
ALTER TABLE [dbo].[HYDRO_DATA] DROP CONSTRAINT [FK__HYDRO_DAT__Mat_O__377107A9]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[HYDRO_DATA] DROP CONSTRAINT [FK__HYDRO_DAT__Mat_Q__38652BE2]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[HYDRO_DATA_ACTIONS]'
GO
ALTER TABLE [dbo].[HYDRO_DATA_ACTIONS] DROP CONSTRAINT [FK__HYDRO_DAT__Progr__76D69450]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[HYDRO_DATA_ACTIONS] DROP CONSTRAINT [FK_HYDRO_DATA_ACTIONS_ANSWER]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[IRP]'
GO
ALTER TABLE [dbo].[IRP] DROP CONSTRAINT [FK_IRP_IRP_HEADER]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[ISE_ACTIONS]'
GO
ALTER TABLE [dbo].[ISE_ACTIONS] DROP CONSTRAINT [FK_MATURITY_QUESTIONS_MAT_QUESTION_ID]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping foreign keys from [dbo].[ISE_ACTIONS_FINDINGS]'
GO
ALTER TABLE [dbo].[ISE_ACTIONS_FINDINGS] DROP CONSTRAINT [FK_ISE_ACTIONS_FINDINGS_FINDING]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[ASSESSMENT_IRP]'
GO
ALTER TABLE [dbo].[ASSESSMENT_IRP] DROP CONSTRAINT [PK_Assessment_IRP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[ASSESSMENT_IRP_HEADER]'
GO
ALTER TABLE [dbo].[ASSESSMENT_IRP_HEADER] DROP CONSTRAINT [PK_ASSESSMENT_IRP_HEADER]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [PK_DEMOGRAPHICS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS_ASSET_VALUES]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS_ASSET_VALUES] DROP CONSTRAINT [PK_DEMOGRAPHICS_ASSET_VALUES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS_ORGANIZATION_TYPE]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS_ORGANIZATION_TYPE] DROP CONSTRAINT [PK_DEMOGRAPHICS_ORGANIZATION_TYPE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS_SIZE]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS_SIZE] DROP CONSTRAINT [PK_DemographicsSize]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[EXTRA_ACET_MAPPING]'
GO
ALTER TABLE [dbo].[EXTRA_ACET_MAPPING] DROP CONSTRAINT [PK_EXTRA_ACET_MAPPING]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_ASSESSMENT_FACTORS]'
GO
ALTER TABLE [dbo].[FINANCIAL_ASSESSMENT_FACTORS] DROP CONSTRAINT [PK_FINANCIAL_ASSESSMENT_FACTORS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_ASSESSMENT_VALUES]'
GO
ALTER TABLE [dbo].[FINANCIAL_ASSESSMENT_VALUES] DROP CONSTRAINT [PK_FINANCIAL_ASSESSMENT_VALUES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_ATTRIBUTES]'
GO
ALTER TABLE [dbo].[FINANCIAL_ATTRIBUTES] DROP CONSTRAINT [PK_FINANCIAL_ATTRIBUTES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_COMPONENTS]'
GO
ALTER TABLE [dbo].[FINANCIAL_COMPONENTS] DROP CONSTRAINT [PK_FINANCIAL_COMPONENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DETAILS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DETAILS] DROP CONSTRAINT [PK_FINANCIAL_TIERS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAINS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAINS] DROP CONSTRAINT [PK_FINANCIAL_DOMAINS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [PK_FINANCIAL_DOMAIN_FILTERS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS_V2]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS_V2] DROP CONSTRAINT [PK_FiltersNormalized]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_FFIEC_MAPPINGS]'
GO
ALTER TABLE [dbo].[FINANCIAL_FFIEC_MAPPINGS] DROP CONSTRAINT [PK_FINANCIAL_FFIEC_MAPPINGS_1]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_GROUPS]'
GO
ALTER TABLE [dbo].[FINANCIAL_GROUPS] DROP CONSTRAINT [PK_FINANCIAL_GROUPS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_HOURS]'
GO
ALTER TABLE [dbo].[FINANCIAL_HOURS] DROP CONSTRAINT [PK_FINANCIAL_ASSESSMENT_HOURS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_HOURS_COMPONENT]'
GO
ALTER TABLE [dbo].[FINANCIAL_HOURS_COMPONENT] DROP CONSTRAINT [PK_FINANCIAL_HOURS_COMPONENT]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_MATURITY]'
GO
ALTER TABLE [dbo].[FINANCIAL_MATURITY] DROP CONSTRAINT [PK_FINANCIAL_MATURITY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_QUESTIONS]'
GO
ALTER TABLE [dbo].[FINANCIAL_QUESTIONS] DROP CONSTRAINT [PK_FINANCIAL_QUESTIONS_1]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_REQUIREMENTS]'
GO
ALTER TABLE [dbo].[FINANCIAL_REQUIREMENTS] DROP CONSTRAINT [PK_FINANCIAL_REQUIREMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_REVIEWTYPE]'
GO
ALTER TABLE [dbo].[FINANCIAL_REVIEWTYPE] DROP CONSTRAINT [PK_FINANCIAL_REVIEWTYPE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_TIERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_TIERS] DROP CONSTRAINT [PK_FINANCIAL_TIERS_1]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[HYDRO_DATA]'
GO
ALTER TABLE [dbo].[HYDRO_DATA] DROP CONSTRAINT [PK_HYDRO_DATA]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[HYDRO_DATA]'
GO
ALTER TABLE [dbo].[HYDRO_DATA] DROP CONSTRAINT [IX_HYDRO_DATA]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[HYDRO_DATA_ACTIONS]'
GO
ALTER TABLE [dbo].[HYDRO_DATA_ACTIONS] DROP CONSTRAINT [PK__HYDRO_DA__36918F3818A6E56C]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[HYDRO_PROGRESS]'
GO
ALTER TABLE [dbo].[HYDRO_PROGRESS] DROP CONSTRAINT [PK__HYDRO_PR__D558797A8254CF40]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[IRP]'
GO
ALTER TABLE [dbo].[IRP] DROP CONSTRAINT [PK_IRP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[IRP_HEADER]'
GO
ALTER TABLE [dbo].[IRP_HEADER] DROP CONSTRAINT [PK_IRP_HEADER]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[ISE_ACTIONS]'
GO
ALTER TABLE [dbo].[ISE_ACTIONS] DROP CONSTRAINT [PK_ISE_ACTIONS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[ISE_ACTIONS_FINDINGS]'
GO
ALTER TABLE [dbo].[ISE_ACTIONS_FINDINGS] DROP CONSTRAINT [PK_ISE_ACTIONS_FINDINGS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[LEVEL_BACKUP_ACET]'
GO
ALTER TABLE [dbo].[LEVEL_BACKUP_ACET] DROP CONSTRAINT [PK_LEVEL_BACKUP_ACET]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[LEVEL_BACKUP_ACET_QUESTIONS]'
GO
ALTER TABLE [dbo].[LEVEL_BACKUP_ACET_QUESTIONS] DROP CONSTRAINT [PK_LEVEL_BACKUP_ACET_QUESTIONS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [DF_DEMOGRAPHICS_NeedsPrivacy]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [DF_DEMOGRAPHICS_NeedsSupplyChain]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [DF_DEMOGRAPHICS_NeedsICS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] DROP CONSTRAINT [DF_DEMOGRAPHICS_IsScoped]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[DEMOGRAPHICS_ASSET_VALUES]'
GO
ALTER TABLE [dbo].[DEMOGRAPHICS_ASSET_VALUES] DROP CONSTRAINT [DF_DEMOGRAPHICS_ASSET_VALUES_AppCode]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [DF_FINANCIAL_DOMAIN_FILTERS_B]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [DF_FINANCIAL_DOMAIN_FILTERS_E]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [DF_FINANCIAL_DOMAIN_FILTERS_Int]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [DF_FINANCIAL_DOMAIN_FILTERS_A]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS] DROP CONSTRAINT [DF_FINANCIAL_DOMAIN_FILTERS_Inn]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_DOMAIN_FILTERS_V2]'
GO
ALTER TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS_V2] DROP CONSTRAINT [DF_FiltersNormalized_IsOn]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[FINANCIAL_HOURS]'
GO
ALTER TABLE [dbo].[FINANCIAL_HOURS] DROP CONSTRAINT [DF_FINANCIAL_ASSESSMENT_HOURS_Hours]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping constraints from [dbo].[IRP]'
GO
ALTER TABLE [dbo].[IRP] DROP CONSTRAINT [df_Risk_Type]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping index [IX_FINANCIAL_ASSESSMENT_FACTORS] from [dbo].[FINANCIAL_ASSESSMENT_FACTORS]'
GO
DROP INDEX [IX_FINANCIAL_ASSESSMENT_FACTORS] ON [dbo].[FINANCIAL_ASSESSMENT_FACTORS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping index [IX_FINANCIAL_COMPONENTS] from [dbo].[FINANCIAL_COMPONENTS]'
GO
DROP INDEX [IX_FINANCIAL_COMPONENTS] ON [dbo].[FINANCIAL_COMPONENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping index [IX_FINANCIAL_DOMAINS] from [dbo].[FINANCIAL_DOMAINS]'
GO
DROP INDEX [IX_FINANCIAL_DOMAINS] ON [dbo].[FINANCIAL_DOMAINS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping index [IX_FINANCIAL_GROUPS] from [dbo].[FINANCIAL_GROUPS]'
GO
DROP INDEX [IX_FINANCIAL_GROUPS] ON [dbo].[FINANCIAL_GROUPS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping index [IX_FINANCIAL_MATURITY] from [dbo].[FINANCIAL_MATURITY]'
GO
DROP INDEX [IX_FINANCIAL_MATURITY] ON [dbo].[FINANCIAL_MATURITY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_AggregationCustomQuestionnaireLoad]'
GO
DROP PROCEDURE [dbo].[usp_AggregationCustomQuestionnaireLoad]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[CheckHeading]'
GO
DROP PROCEDURE [dbo].[CheckHeading]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[LEVEL_BACKUP_ACET_QUESTIONS]'
GO
DROP TABLE [dbo].[LEVEL_BACKUP_ACET_QUESTIONS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[LEVEL_BACKUP_ACET]'
GO
DROP TABLE [dbo].[LEVEL_BACKUP_ACET]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[EXTRA_ACET_MAPPING]'
GO
DROP TABLE [dbo].[EXTRA_ACET_MAPPING]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getMaturitySummaryOverall]'
GO
DROP PROCEDURE [dbo].[usp_getMaturitySummaryOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetMaturityComparisonBestToWorst]'
GO
DROP PROCEDURE [dbo].[GetMaturityComparisonBestToWorst]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetQuestions]'
GO
DROP PROCEDURE [dbo].[usp_GetQuestions]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetMaturityAnswerTotals]'
GO
DROP PROCEDURE [dbo].[usp_GetMaturityAnswerTotals]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_StatementsReviewedTabTotals]'
GO
DROP PROCEDURE [dbo].[usp_StatementsReviewedTabTotals]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_StatementsReviewed]'
GO
DROP PROCEDURE [dbo].[usp_StatementsReviewed]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_MaturityDetailsCalculations]'
GO
DROP PROCEDURE [dbo].[usp_MaturityDetailsCalculations]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getVADRSummaryPage]'
GO
DROP PROCEDURE [dbo].[usp_getVADRSummaryPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getVADRSummaryOverall]'
GO
DROP PROCEDURE [dbo].[usp_getVADRSummaryOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getVADRSummaryByGoalOverall]'
GO
DROP PROCEDURE [dbo].[usp_getVADRSummaryByGoalOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getVADRSummaryByGoal]'
GO
DROP PROCEDURE [dbo].[usp_getVADRSummaryByGoal]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getVADRSummary]'
GO
DROP PROCEDURE [dbo].[usp_getVADRSummary]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getStandardSummaryOverall]'
GO
DROP PROCEDURE [dbo].[usp_getStandardSummaryOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetStandardsSummaryPage]'
GO
DROP PROCEDURE [dbo].[usp_GetStandardsSummaryPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getStandardsSummary]'
GO
DROP PROCEDURE [dbo].[usp_getStandardsSummary]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetStandardsResultsByCategoryPage]'
GO
DROP PROCEDURE [dbo].[usp_GetStandardsResultsByCategoryPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getStandardsResultsByCategory]'
GO
DROP PROCEDURE [dbo].[usp_getStandardsResultsByCategory]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetStandardsRankedCategoriesPage]'
GO
DROP PROCEDURE [dbo].[usp_GetStandardsRankedCategoriesPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getStandardsRankedCategories]'
GO
DROP PROCEDURE [dbo].[usp_getStandardsRankedCategories]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getRRASummaryPage]'
GO
DROP PROCEDURE [dbo].[usp_getRRASummaryPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getRRASummaryOverall]'
GO
DROP PROCEDURE [dbo].[usp_getRRASummaryOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getRRASummaryByGoalOverall]'
GO
DROP PROCEDURE [dbo].[usp_getRRASummaryByGoalOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getRRASummaryByGoal]'
GO
DROP PROCEDURE [dbo].[usp_getRRASummaryByGoal]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getRRASummary]'
GO
DROP PROCEDURE [dbo].[usp_getRRASummary]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetRawCountsForEachAssessment_Standards]'
GO
DROP PROCEDURE [dbo].[usp_GetRawCountsForEachAssessment_Standards]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getRankedStandardCategories]'
GO
DROP PROCEDURE [dbo].[usp_getRankedStandardCategories]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetRankedQuestions]'
GO
DROP PROCEDURE [dbo].[usp_GetRankedQuestions]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetRankedCategoriesPage]'
GO
DROP PROCEDURE [dbo].[usp_GetRankedCategoriesPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getRankedCategories]'
GO
DROP PROCEDURE [dbo].[usp_getRankedCategories]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetQuestionsWithFeedBack]'
GO
DROP PROCEDURE [dbo].[usp_GetQuestionsWithFeedBack]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getMinMaxAverageForSectorIndustry]'
GO
DROP PROCEDURE [dbo].[usp_getMinMaxAverageForSectorIndustry]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getMedianOverall]'
GO
DROP PROCEDURE [dbo].[usp_getMedianOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getGenericModelSummaryByGoal]'
GO
DROP PROCEDURE [dbo].[usp_getGenericModelSummaryByGoal]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getFirstPage]'
GO
DROP PROCEDURE [dbo].[usp_getFirstPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetOverallRankedCategoriesPage]'
GO
DROP PROCEDURE [dbo].[usp_GetOverallRankedCategoriesPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getOverallRankedCategories]'
GO
DROP PROCEDURE [dbo].[usp_getOverallRankedCategories]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getFinancialQuestions]'
GO
DROP PROCEDURE [dbo].[usp_getFinancialQuestions]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetComponentTypesPage]'
GO
DROP PROCEDURE [dbo].[usp_GetComponentTypesPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getComponentTypes]'
GO
DROP PROCEDURE [dbo].[usp_getComponentTypes]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetComponentsSummaryPage]'
GO
DROP PROCEDURE [dbo].[usp_GetComponentsSummaryPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getComponentsSummary]'
GO
DROP PROCEDURE [dbo].[usp_getComponentsSummary]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetComponentsResultsByCategoryPage]'
GO
DROP PROCEDURE [dbo].[usp_GetComponentsResultsByCategoryPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getComponentsResultsByCategory]'
GO
DROP PROCEDURE [dbo].[usp_getComponentsResultsByCategory]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetComponentsRankedCategoriesPage]'
GO
DROP PROCEDURE [dbo].[usp_GetComponentsRankedCategoriesPage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getComponentsRankedCategories]'
GO
DROP PROCEDURE [dbo].[usp_getComponentsRankedCategories]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GetAssessmentPie]'
GO
DROP PROCEDURE [dbo].[usp_GetAssessmentPie]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getAnswerComponentOverrides]'
GO
DROP PROCEDURE [dbo].[usp_getAnswerComponentOverrides]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_GenerateSPRSScore]'
GO
DROP PROCEDURE [dbo].[usp_GenerateSPRSScore]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_financial_attributes]'
GO
DROP PROCEDURE [dbo].[usp_financial_attributes]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_countsForLevelsByGroupMaturityModel]'
GO
DROP PROCEDURE [dbo].[usp_countsForLevelsByGroupMaturityModel]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_CopyIntoSet_Delete]'
GO
DROP PROCEDURE [dbo].[usp_CopyIntoSet_Delete]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_CopyIntoSet]'
GO
DROP PROCEDURE [dbo].[usp_CopyIntoSet]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_Assessments_Completion_For_User]'
GO
DROP PROCEDURE [dbo].[usp_Assessments_Completion_For_User]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_Assessments_Completion_For_Access_Key]'
GO
DROP PROCEDURE [dbo].[usp_Assessments_Completion_For_Access_Key]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_Answer_Components_Default]'
GO
DROP PROCEDURE [dbo].[usp_Answer_Components_Default]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[IseAnswerDistribution]'
GO
DROP PROCEDURE [dbo].[IseAnswerDistribution]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetPercentageOverall]'
GO
DROP PROCEDURE [dbo].[GetPercentageOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetMaturityGroupings]'
GO
DROP PROCEDURE [dbo].[GetMaturityGroupings]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetMaturityDetailsCalculations]'
GO
DROP PROCEDURE [dbo].[GetMaturityDetailsCalculations]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetCompatibilityCounts]'
GO
DROP PROCEDURE [dbo].[GetCompatibilityCounts]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[vFinancialGroups]'
GO
DROP VIEW [dbo].[vFinancialGroups]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetComparisonFileSummary]'
GO
DROP PROCEDURE [dbo].[GetComparisonFileSummary]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetComparisonFilePercentage]'
GO
DROP PROCEDURE [dbo].[GetComparisonFilePercentage]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetComparisonFileOveralls]'
GO
DROP PROCEDURE [dbo].[GetComparisonFileOveralls]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetComparisonAreasFile]'
GO
DROP PROCEDURE [dbo].[GetComparisonAreasFile]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetCombinedOveralls]'
GO
DROP PROCEDURE [dbo].[GetCombinedOveralls]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getExplodedComponent]'
GO
DROP PROCEDURE [dbo].[usp_getExplodedComponent]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetAreasOverall]'
GO
DROP PROCEDURE [dbo].[GetAreasOverall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetAreasData]'
GO
DROP PROCEDURE [dbo].[GetAreasData]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetAnswerDistribMaturity]'
GO
DROP PROCEDURE [dbo].[GetAnswerDistribMaturity]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[GetAnswerDistribGroupings]'
GO
DROP PROCEDURE [dbo].[GetAnswerDistribGroupings]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[Get_Recommendations]'
GO
DROP PROCEDURE [dbo].[Get_Recommendations]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[Get_Merge_Conflicts]'
GO
DROP PROCEDURE [dbo].[Get_Merge_Conflicts]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[Get_Assess_Detail_Filter_Data]'
GO
DROP PROCEDURE [dbo].[Get_Assess_Detail_Filter_Data]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[DeleteUser]'
GO
DROP PROCEDURE [dbo].[DeleteUser]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[DeleteAssessment]'
GO
DROP PROCEDURE [dbo].[DeleteAssessment]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[clean_out_requirements_mode]'
GO
DROP PROCEDURE [dbo].[clean_out_requirements_mode]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_CF_ConvertLegacyFull]'
GO
DROP PROCEDURE [dbo].[usp_CF_ConvertLegacyFull]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[AcetAnswerDistribution]'
GO
DROP PROCEDURE [dbo].[AcetAnswerDistribution]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[Acet_GetActionItemsForReport]'
GO
DROP PROCEDURE [dbo].[Acet_GetActionItemsForReport]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_CF_Questions]'
GO
DROP PROCEDURE [dbo].[usp_CF_Questions]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_CF_Score_Overall]'
GO
DROP PROCEDURE [dbo].[usp_CF_Score_Overall]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_CF_Score_Averages]'
GO
DROP PROCEDURE [dbo].[usp_CF_Score_Averages]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[usp_getCSETQuestionsForCRRM]'
GO
DROP PROCEDURE [dbo].[usp_getCSETQuestionsForCRRM]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[ISE_ACTIONS]'
GO
DROP TABLE [dbo].[ISE_ACTIONS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[ISE_ACTIONS_FINDINGS]'
GO
DROP TABLE [dbo].[ISE_ACTIONS_FINDINGS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_TIERS]'
GO
DROP TABLE [dbo].[FINANCIAL_TIERS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_REQUIREMENTS]'
GO
DROP TABLE [dbo].[FINANCIAL_REQUIREMENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_QUESTIONS]'
GO
DROP TABLE [dbo].[FINANCIAL_QUESTIONS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_REVIEWTYPE]'
GO
DROP TABLE [dbo].[FINANCIAL_REVIEWTYPE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_HOURS_COMPONENT]'
GO
DROP TABLE [dbo].[FINANCIAL_HOURS_COMPONENT]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_HOURS]'
GO
DROP TABLE [dbo].[FINANCIAL_HOURS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_COMPONENTS]'
GO
DROP TABLE [dbo].[FINANCIAL_COMPONENTS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_ASSESSMENT_FACTORS]'
GO
DROP TABLE [dbo].[FINANCIAL_ASSESSMENT_FACTORS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_FFIEC_MAPPINGS]'
GO
DROP TABLE [dbo].[FINANCIAL_FFIEC_MAPPINGS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_MATURITY]'
GO
DROP TABLE [dbo].[FINANCIAL_MATURITY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_DOMAIN_FILTERS_V2]'
GO
DROP TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS_V2]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_DOMAINS]'
GO
DROP TABLE [dbo].[FINANCIAL_DOMAINS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_DOMAIN_FILTERS]'
GO
DROP TABLE [dbo].[FINANCIAL_DOMAIN_FILTERS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_DETAILS]'
GO
DROP TABLE [dbo].[FINANCIAL_DETAILS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_GROUPS]'
GO
DROP TABLE [dbo].[FINANCIAL_GROUPS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_ATTRIBUTES]'
GO
DROP TABLE [dbo].[FINANCIAL_ATTRIBUTES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[FINANCIAL_ASSESSMENT_VALUES]'
GO
DROP TABLE [dbo].[FINANCIAL_ASSESSMENT_VALUES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[DEMOGRAPHICS_SIZE]'
GO
DROP TABLE [dbo].[DEMOGRAPHICS_SIZE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[DEMOGRAPHICS_ORGANIZATION_TYPE]'
GO
DROP TABLE [dbo].[DEMOGRAPHICS_ORGANIZATION_TYPE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[DEMOGRAPHICS_ASSET_VALUES]'
GO
DROP TABLE [dbo].[DEMOGRAPHICS_ASSET_VALUES]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[DEMOGRAPHICS]'
GO
DROP TABLE [dbo].[DEMOGRAPHICS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[HYDRO_DATA_ACTIONS]'
GO
DROP TABLE [dbo].[HYDRO_DATA_ACTIONS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[HYDRO_PROGRESS]'
GO
DROP TABLE [dbo].[HYDRO_PROGRESS]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[HYDRO_DATA]'
GO
DROP TABLE [dbo].[HYDRO_DATA]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[IRP]'
GO
DROP TABLE [dbo].[IRP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[IRP_HEADER]'
GO
DROP TABLE [dbo].[IRP_HEADER]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[ASSESSMENT_IRP_HEADER]'
GO
DROP TABLE [dbo].[ASSESSMENT_IRP_HEADER]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Dropping [dbo].[ASSESSMENT_IRP]'
GO
DROP TABLE [dbo].[ASSESSMENT_IRP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[ASSESSMENTS]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[ASSESSMENTS] ADD
[TotalQuestionCount] [int] NULL,
[CompletedQuestionCount] [int] NULL,
[Done] [bit] NULL CONSTRAINT [DF_ASSESSMENTS_Done] DEFAULT ((0))
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[ASSESSMENT_SECTOR_SUBSECTOR]'
GO
CREATE TABLE [dbo].[ASSESSMENT_SECTOR_SUBSECTOR]
(
[AssessmentSectorSubsectorId] [int] NOT NULL IDENTITY(1, 1),
[Assessment_Id] [int] NOT NULL,
[SectorId] [int] NOT NULL,
[IndustryId] [int] NULL,
[Sequence] [int] NOT NULL
) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK__ASSESSME__43AF4010758B5AA6] on [dbo].[ASSESSMENT_SECTOR_SUBSECTOR]'
GO
ALTER TABLE [dbo].[ASSESSMENT_SECTOR_SUBSECTOR] ADD CONSTRAINT [PK__ASSESSME__43AF4010758B5AA6] PRIMARY KEY CLUSTERED ([AssessmentSectorSubsectorId]) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding constraints to [dbo].[ASSESSMENT_SECTOR_SUBSECTOR]'
GO
ALTER TABLE [dbo].[ASSESSMENT_SECTOR_SUBSECTOR] ADD CONSTRAINT [UQ_ASSESSMENT_SECTOR_SUBSECTOR] UNIQUE NONCLUSTERED ([Assessment_Id], [SectorId], [IndustryId]) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding constraints to [dbo].[ASSESSMENT_SECTOR_SUBSECTOR]'
GO
ALTER TABLE [dbo].[ASSESSMENT_SECTOR_SUBSECTOR] ADD CONSTRAINT [UQ_Assessment_Sequence] UNIQUE NONCLUSTERED ([Assessment_Id], [Sequence]) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[FINDING]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINDING] ADD
[Assessment_ID] [int] NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[FINDING] ALTER COLUMN [Answer_Id] [int] NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[MATURITY_QUESTIONS]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[MATURITY_QUESTIONS] ADD
[Is_Answerable] [bit] NOT NULL CONSTRAINT [DF__MATURITY___Is_An__5E5FEC41] DEFAULT ((1))
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[ASSESSMENT_CONTACTS]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS] ADD
[Favorite] [bit] NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[USERS]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[USERS] ADD
[IsLocalAccount] [bit] NOT NULL CONSTRAINT [DF__USERS__isLocalAc__01FE2E39] DEFAULT ((0))
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[PARAMETERS]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[PARAMETERS] ADD
[Lang] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PARAMETERS__Lang__76F68FE1] DEFAULT ('en')
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[GALLERY_ITEM_USER]'
GO
CREATE TABLE [dbo].[GALLERY_ITEM_USER]
(
[Gallery_Item_Guid] [uniqueidentifier] NOT NULL,
[UserId] [int] NOT NULL,
[IsFavorite] [bit] NOT NULL CONSTRAINT [DF__GALLERY_I__IsFav__63E3BB6D] DEFAULT ((0))
) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_GALLERY_ITEM_USER] on [dbo].[GALLERY_ITEM_USER]'
GO
ALTER TABLE [dbo].[GALLERY_ITEM_USER] ADD CONSTRAINT [PK_GALLERY_ITEM_USER] PRIMARY KEY CLUSTERED ([Gallery_Item_Guid], [UserId]) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [IX_GALLERY_ITEM_USER_Favorites] on [dbo].[GALLERY_ITEM_USER]'
GO
CREATE NONCLUSTERED INDEX [IX_GALLERY_ITEM_USER_Favorites] ON [dbo].[GALLERY_ITEM_USER] ([UserId], [IsFavorite]) WHERE ([IsFavorite]=(1)) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[GROUPING_SELECTION]'
GO
CREATE TABLE [dbo].[GROUPING_SELECTION]
(
[Assessment_Id] [int] NOT NULL,
[Grouping_Id] [int] NOT NULL
) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_GROUPING_SELECTION] on [dbo].[GROUPING_SELECTION]'
GO
ALTER TABLE [dbo].[GROUPING_SELECTION] ADD CONSTRAINT [PK_GROUPING_SELECTION] PRIMARY KEY CLUSTERED ([Assessment_Id], [Grouping_Id]) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[MATURITY_QUESTION_PROPS]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[MATURITY_QUESTION_PROPS] ALTER COLUMN [PropertyValue] [nvarchar] (3000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[FillEmptyMaturityQuestionsForAnalysis]'
GO

-- =============================================
-- Author:		Dylan Johnson
-- Create date: 10/04/2020
-- Description:	Create empty data for questions that have not been filled out to ensure correct reporting values
-- =============================================
ALTER PROCEDURE [dbo].[FillEmptyMaturityQuestionsForAnalysis]
	@Assessment_Id int	
AS
BEGIN	
	DECLARE @result int;  
	begin
	BEGIN TRANSACTION;  
	EXEC @result = sp_getapplock @Resource = '[Answer]', @LockMode = 'Exclusive';
	INSERT INTO [dbo].[ANSWER]  ([Question_Or_Requirement_Id],[Answer_Text],[Question_Type],[Assessment_Id])     
		select mq.Mat_Question_Id,Answer_Text = 'U', Question_Type='Maturity', Assessment_Id =@Assessment_Id
		from [dbo].[MATURITY_QUESTIONS] mq
			where Maturity_Model_Id in
			(select model_id from [dbo].[AVAILABLE_MATURITY_MODELS]
			where Assessment_Id = @Assessment_Id) 
			and Mat_Question_Id not in 
			(select Question_Or_Requirement_Id from [dbo].[ANSWER] 
			where Assessment_Id = @Assessment_Id)
			and is_answerable = 1
		IF @result = -3  
		BEGIN  
			ROLLBACK TRANSACTION;  
		END  
		ELSE  
		BEGIN  
			EXEC sp_releaseapplock @Resource = '[Answer]'; 	
			COMMIT TRANSACTION;  
		END
	end

END
/****** Object:  StoredProcedure [dbo].[FillEmptyQuestionsForAnalysis]    Script Date: 12/16/2020 11:01:33 AM ******/
SET ANSI_NULLS ON
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[usp_GetTop5Areas]'
GO

-- =============================================
-- Author:		hansbk (Fixed to handle requirements)
-- Create date: 1/27/2020
-- Modified: 2/16/2026 - Added support for requirements
-- Description:	get the percentages for each area
-- line up the assessments 
-- =============================================
ALTER PROCEDURE [dbo].[usp_GetTop5Areas]
	@Aggregation_id int
AS
BEGIN

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON;

	-- Execute trend order setup
	EXEC usp_setTrendOrder @aggregation_id
	
	-- Declare variables
	DECLARE @assessment1 int, @assessment2 int
	SET @assessment1 = NULL;
	SET @assessment2 = NULL; 

	-- Drop temp tables if they exist
	IF OBJECT_ID('tempdb..#answers') IS NOT NULL DROP TABLE #answers
	IF OBJECT_ID('tempdb..#TopBottomType') IS NOT NULL DROP TABLE #TopBottomType
	
	-- Create temp tables
	CREATE TABLE #TopBottomType(
		[Question_Group_Heading] [nvarchar](100) NOT NULL,
		[pdifference] [float] NULL,
		[TopBottomType] [nvarchar](10) NOT NULL
	)

	CREATE TABLE #answers (
		assessment_id int, 
		answer_id int, 
		is_requirement bit, 
		question_or_requirement_id int, 
		mark_for_review bit, 
		comment ntext, 
		alternate_justification ntext, 
		question_number int, 
		answer_text nvarchar(50), 
		component_guid nvarchar(36), 
		is_component bit, 
		custom_question_guid nvarchar(50), 
		is_framework bit, 
		old_answer_id int, 
		reviewed bit
	)

	-- Cursor to get assessments
	DECLARE sse CURSOR FOR 
	SELECT Assessment_Id 
	FROM AGGREGATION_ASSESSMENT 
	WHERE Aggregation_Id = @Aggregation_id
	ORDER BY Sequence DESC
	
	DECLARE @assessment_id int

	OPEN sse
	FETCH NEXT FROM sse INTO @assessment_id 
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF (@assessment1 IS NULL) SET @assessment1 = @assessment_id 

		INSERT INTO #answers EXEC [GetRelevantAnswers] @assessment_id		
		
		FETCH NEXT FROM sse INTO @assessment_id 
		IF(@assessment2 IS NULL) SET @assessment2 = @assessment_id
	END
	CLOSE sse 
	DEALLOCATE sse
	
	-- Validate we have at least 2 assessments
	IF @assessment1 IS NULL OR @assessment2 IS NULL
	BEGIN
		SELECT 'Error: Need at least 2 assessments for comparison' AS ErrorMessage
		RETURN
	END

	-- Calculate differences and insert into temp table
	INSERT INTO #TopBottomType(Question_Group_Heading, pdifference, TopBottomType)
	SELECT  
		assessment1.Question_Group_Heading,
		assessment1.percentage - assessment2.percentage AS pdifference,
		'None' AS TopBottomType
	FROM (
		-- Assessment 1 percentages
		SELECT 
			a.Assessment_Id,
			a.Question_Group_Heading,
			a.YesCount,
			a.NoCount,
			a.NaCount,
			a.AlternateCount,
			a.UnansweredCount,
			b.Total, 
			(ISNULL(YesCount,0) + ISNULL(AlternateCount,0)) / CAST(Total AS FLOAT) AS percentage  
		FROM (
			SELECT 
				Assessment_Id, 
				Question_Group_Heading,
				[Y] AS [YesCount],			
				[N] AS [NoCount],
				[NA] AS [NaCount],
				[A] AS [AlternateCount],
				[U] AS [UnansweredCount]			
			FROM (
				-- FIXED: Handle both questions and requirements
				SELECT 
					Assessment_Id, 
					h.Question_Group_Heading, 
					Answer_Text			 
				FROM #answers a 
				LEFT JOIN NEW_QUESTION q ON a.Question_Or_Requirement_Id = q.Question_Id AND a.is_requirement = 0
				LEFT JOIN NEW_REQUIREMENT r ON a.Question_Or_Requirement_Id = r.Requirement_Id AND a.is_requirement = 1
				JOIN vQUESTION_HEADINGS h ON 
					(a.is_requirement = 0 AND q.Heading_Pair_Id = h.Heading_Pair_Id) OR
					(a.is_requirement = 1 AND r.Question_Group_Heading_Id = h.Question_Group_Heading_Id)
				WHERE answer_text <> 'NA'
			) p
			PIVOT (
				COUNT(Answer_Text)
				FOR Answer_Text IN ([Y],[N],[NA],[A],[U])
			) AS pvt 
			WHERE Assessment_Id IS NOT NULL
		) a 
		JOIN (
			SELECT 
				Assessment_Id, 
				h.Question_Group_Heading, 
				COUNT(answer_text) AS Total 	
			FROM #answers a 
			LEFT JOIN NEW_QUESTION q ON a.Question_Or_Requirement_Id = q.Question_Id AND a.is_requirement = 0
			LEFT JOIN NEW_REQUIREMENT r ON a.Question_Or_Requirement_Id = r.Requirement_Id AND a.is_requirement = 1
			JOIN vQUESTION_HEADINGS h ON 
				(a.is_requirement = 0 AND q.Heading_Pair_Id = h.Heading_Pair_Id) OR
				(a.is_requirement = 1 AND r.Question_Group_Heading_Id = h.Question_Group_Heading_Id)
			WHERE answer_text <> 'NA' AND assessment_id = @assessment1
			GROUP BY Assessment_Id, h.Question_Group_Heading
		) b ON a.assessment_id = b.assessment_id AND a.Question_Group_Heading = b.Question_Group_Heading
	) assessment1 
	JOIN (
		-- Assessment 2 percentages (same logic)
		SELECT 
			a.Assessment_Id,
			a.Question_Group_Heading,
			a.YesCount,
			a.NoCount,
			a.NaCount,
			a.AlternateCount,
			a.UnansweredCount,
			b.Total, 
			(ISNULL(YesCount,0) + ISNULL(AlternateCount,0)) / CAST(Total AS FLOAT) AS percentage  
		FROM (
			SELECT 
				Assessment_Id, 
				Question_Group_Heading,
				[Y] AS [YesCount],			
				[N] AS [NoCount],
				[NA] AS [NaCount],
				[A] AS [AlternateCount],
				[U] AS [UnansweredCount]			
			FROM (
				SELECT 
					Assessment_Id, 
					h.Question_Group_Heading, 
					Answer_Text			 
				FROM #answers a 
				LEFT JOIN NEW_QUESTION q ON a.Question_Or_Requirement_Id = q.Question_Id AND a.is_requirement = 0
				LEFT JOIN NEW_REQUIREMENT r ON a.Question_Or_Requirement_Id = r.Requirement_Id AND a.is_requirement = 1
				JOIN vQUESTION_HEADINGS h ON 
					(a.is_requirement = 0 AND q.Heading_Pair_Id = h.Heading_Pair_Id) OR
					(a.is_requirement = 1 AND r.Question_Group_Heading_Id = h.Question_Group_Heading_Id)
				WHERE answer_text <> 'NA'
			) p
			PIVOT (
				COUNT(Answer_Text)
				FOR Answer_Text IN ([Y],[N],[NA],[A],[U])
			) AS pvt 
			WHERE Assessment_Id IS NOT NULL
		) a 
		JOIN (
			SELECT 
				Assessment_Id, 
				h.Question_Group_Heading, 
				COUNT(answer_text) AS Total 	
			FROM #answers a 
			LEFT JOIN NEW_QUESTION q ON a.Question_Or_Requirement_Id = q.Question_Id AND a.is_requirement = 0
			LEFT JOIN NEW_REQUIREMENT r ON a.Question_Or_Requirement_Id = r.Requirement_Id AND a.is_requirement = 1
			JOIN vQUESTION_HEADINGS h ON 
				(a.is_requirement = 0 AND q.Heading_Pair_Id = h.Heading_Pair_Id) OR
				(a.is_requirement = 1 AND r.Question_Group_Heading_Id = h.Question_Group_Heading_Id)
			WHERE answer_text <> 'NA' AND assessment_id = @assessment2
			GROUP BY Assessment_Id, h.Question_Group_Heading
		) b ON a.assessment_id = b.assessment_id AND a.Question_Group_Heading = b.Question_Group_Heading
	) assessment2 ON assessment1.Question_Group_Heading = assessment2.Question_Group_Heading
	ORDER BY pdifference DESC

	-- Mark bottom 5 (most declined)
	UPDATE #TopBottomType 
	SET TopBottomType = 'BOTTOM' 
	FROM (
		SELECT TOP 5 Question_Group_Heading 
		FROM #TopBottomType 
		ORDER BY pdifference
	) a
	WHERE #TopBottomType.Question_Group_Heading = a.Question_Group_Heading

	-- Mark top 5 (most improved - only positive changes)
	UPDATE #TopBottomType 
	SET TopBottomType = 'TOP' 
	FROM (
		SELECT TOP 5 Question_Group_Heading 
		FROM #TopBottomType 
		WHERE pdifference >= 0
		ORDER BY pdifference DESC
	) a
	WHERE #TopBottomType.Question_Group_Heading = a.Question_Group_Heading

	-- Final result set
	SELECT 
		a.Assessment_Id,
		a.Question_Group_Heading,
		a.YesCount,
		a.NoCount,
		a.NaCount,
		a.AlternateCount,
		a.UnansweredCount,
		b.Total, 
		((ISNULL(YesCount,0) + ISNULL(AlternateCount,0)) / CAST(Total AS FLOAT)) * 100 AS percentage,
		#TopBottomType.pdifference, 
		TopBottomType,
		Assessment_Date
	FROM (
		SELECT 
			Assessment_Id, 
			Question_Group_Heading,
			[Y] AS [YesCount],			
			[N] AS [NoCount],
			[NA] AS [NaCount],
			[A] AS [AlternateCount],
			[U] AS [UnansweredCount]			
		FROM (
			SELECT 
				Assessment_Id, 
				h.Question_Group_Heading, 
				Answer_Text			 
			FROM #answers a 
			LEFT JOIN NEW_QUESTION q ON a.Question_Or_Requirement_Id = q.Question_Id AND a.is_requirement = 0
			LEFT JOIN NEW_REQUIREMENT r ON a.Question_Or_Requirement_Id = r.Requirement_Id AND a.is_requirement = 1
			JOIN vQUESTION_HEADINGS h ON 
				(a.is_requirement = 0 AND q.Heading_Pair_Id = h.Heading_Pair_Id) OR
				(a.is_requirement = 1 AND r.Question_Group_Heading_Id = h.Question_Group_Heading_Id)
			WHERE answer_text <> 'NA'
		) p
		PIVOT (
			COUNT(Answer_Text)
			FOR Answer_Text IN ([Y],[N],[NA],[A],[U])
		) AS pvt 
		WHERE Assessment_Id IS NOT NULL
	) a 
	JOIN (
		SELECT 
			Assessment_Id, 
			h.Question_Group_Heading, 
			COUNT(answer_text) AS Total 	
		FROM #answers a 
		LEFT JOIN NEW_QUESTION q ON a.Question_Or_Requirement_Id = q.Question_Id AND a.is_requirement = 0
		LEFT JOIN NEW_REQUIREMENT r ON a.Question_Or_Requirement_Id = r.Requirement_Id AND a.is_requirement = 1
		JOIN vQUESTION_HEADINGS h ON 
			(a.is_requirement = 0 AND q.Heading_Pair_Id = h.Heading_Pair_Id) OR
			(a.is_requirement = 1 AND r.Question_Group_Heading_Id = h.Question_Group_Heading_Id)
		WHERE answer_text <> 'NA'
		GROUP BY Assessment_Id, h.Question_Group_Heading
	) b ON a.assessment_id = b.assessment_id AND a.Question_Group_Heading = b.Question_Group_Heading 
	JOIN #TopBottomType ON b.Question_Group_Heading = #TopBottomType.Question_Group_Heading
	JOIN ASSESSMENTS ON a.assessment_id = assessments.Assessment_Id
	WHERE #TopBottomType.TopBottomType IN ('TOP','BOTTOM')  -- FIXED: Case sensitivity
	ORDER BY TopBottomType DESC, pdifference DESC, Question_Group_Heading, Assessment_Date, Assessment_Id
	
END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[func_MQ]'
GO

-- =============================================
-- Author:		Randy Woods
-- Create date: 10-OCT-2023
-- Description:	Returns all MATURITY_QUESTIONS rows applicable for an assessment.
--              If the assessment is using a "sub model", only the questions in the
--              sub model are returned.  Otherwise, all questions for the assessment's
--              model are returned.
-- =============================================
ALTER FUNCTION [dbo].[func_MQ]
(
	@assessmentId int
)
RETURNS 
@MQ TABLE 
(
	[Mat_Question_Id] [int] NOT NULL,
	[Question_Title] [nvarchar](250) NULL,
	[Question_Text] [nvarchar](max) NOT NULL,
	[Supplemental_Info] [nvarchar](max) NULL,
	[Category] [nvarchar](250) NULL,
	[Sub_Category] [nvarchar](250) NULL,
	[Maturity_Level_Id] [int] NOT NULL,
	[Sequence] [int] NOT NULL,
	[Text_Hash]  [varbinary](20),
	[Maturity_Model_Id] [int] NOT NULL,
	[Parent_Question_Id] [int] NULL,
	[Ranking] [int] NULL,
	[Grouping_Id] [int] NULL,
	[Examination_Approach] [nvarchar](max) NULL,
	[Short_Name] [nvarchar](80) NULL,
	[Mat_Question_Type] [nvarchar](50) NULL,
	[Parent_Option_Id] [int] NULL,
	[Supplemental_Fact] [nvarchar](max) NULL,
	[Scope] [nvarchar](250) NULL,
	[Recommend_Action] [nvarchar](max) NULL,
	[Risk_Addressed] [nvarchar](max) NULL,
	[Services] [nvarchar](max) NULL,
	[Outcome] nvarchar(max) null,
	[Security_Practice] nvarchar(max) null,
	[Implementation_Guides] nvarchar(max) null,
	[Is_Answerable] [bit] NULL
)
AS
BEGIN
	declare @modelId int
	select @modelId = model_id from AVAILABLE_MATURITY_MODELS where Assessment_Id = @assessmentId and selected = 1

	declare @submodel varchar(20)
    select @submodel = stringvalue from DETAILS_DEMOGRAPHICS where assessment_id = @assessmentId and DataItemName = 'MATURITY-SUBMODEL'


	if @submodel is null 
	begin
		insert into @MQ select * from MATURITY_QUESTIONS where maturity_model_id = @modelId
	end
	else
	begin
		insert into @MQ select * from MATURITY_QUESTIONS where maturity_model_id = @modelId
		and mat_question_id in (select mat_question_id from MATURITY_SUB_MODEL_QUESTIONS where sub_model_name = @submodel)
	end
	
	RETURN 
END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[usp_Assessments_For_User]'
GO

ALTER PROCEDURE [dbo].[usp_Assessments_For_User]
@User_Id int
AS
SET NOCOUNT ON;

-- Replaces view Assessments_For_User.  Gathering missing alt justification is
-- more straightforward using a procedure than a view.

-- build a table variable with ALT answers without justification
declare @ATM table(assessment_id INT)

insert into @ATM
select distinct assessment_id 
from Answer_Standards_InScope
where (isnull(alternate_justification, '') = '' and answer_text = 'A')

insert into @ATM
select distinct assessment_id 
from Answer_Maturity
where (isnull(alternate_justification, '') = '' and answer_text = 'A')

insert into @ATM
select distinct assessment_id 
from Answer_Components_InScope
where (isnull(alternate_justification, '') = '' and answer_text = 'A')

select 	
    AssessmentId = a.Assessment_Id,
	AssessmentName = Assessment_Name,
	AssessmentDate = Assessment_Date,
	AssessmentCreatedDate,	
	LastModifiedDate,
	MarkedForReview = isnull(mark_for_review,0),
	UseDiagram,
	UseStandard,
	UseMaturity,	
	workflow,
	SelectedMaturityModel = m.Model_Name,
	iseSubmitted = i.Ise_Submitted,
	submittedDate = i.Submitted_Date,
	SelectedStandards = string_agg(s.Short_Name, ', '),
	case when a.assessment_id in (select assessment_id from @ATM) then CAST(1 AS BIT) else CAST(0 AS BIT) END as AltTextMissing,
    a.Done,
    c.Favorite,
	c.UserId
	from ASSESSMENTS a 
		join INFORMATION i on a.Assessment_Id = i.Id
		left join AVAILABLE_MATURITY_MODELS amm on amm.Assessment_Id = a.Assessment_Id
		left join MATURITY_MODELS m on m.Maturity_Model_Id = amm.model_id
		left join AVAILABLE_STANDARDS astd on astd.Assessment_Id = a.Assessment_Id
		left join SETS s on s.Set_Name = astd.Set_Name		
		join ASSESSMENT_CONTACTS c on a.Assessment_Id = c.Assessment_Id and c.UserId = @User_Id		
		left join (
			select distinct a.Assessment_Id, v.Mark_For_Review
			from ASSESSMENTS a 
			join Answer_Standards_InScope v on a.Assessment_Id = v.Assessment_Id 
			where v.Mark_For_Review = 1 

			union

			select distinct a.Assessment_Id, Mark_For_Review
			from ASSESSMENTS a
			join Answer_Maturity v on a.Assessment_id = v.Assessment_Id
			where v.Mark_For_Review = 1

			union 

			select distinct a.Assessment_Id, Mark_For_Review 
			from ASSESSMENTS a 
			join Answer_Components_InScope v on a.Assessment_Id = v.Assessment_Id 
			where v.Mark_For_Review = 1) b 
			
		on a.Assessment_Id = b.Assessment_Id
		where c.UserId = @User_Id
		group by a.Assessment_Id, Assessment_Name, Assessment_Date, AssessmentCreatedDate, 
					LastModifiedDate, mark_for_review, UseDiagram,
					UseStandard, UseMaturity, Workflow, Model_Name, 
					Ise_Submitted, Submitted_Date, a.Done, c.Favorite, c.UserId
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[analytics_Compute_MaturitySampleSize]'
GO

-- =============================================
-- Author:		Mostafa, Randy
-- Create date: 11-12-2024
-- Description: Return Assessment count based on maturity model id and optional sector_id
-- =============================================
ALTER PROCEDURE [dbo].[analytics_Compute_MaturitySampleSize]
@maturity_model_id int,
@sector_id int = NULL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	--test base case where there is no data in db at all
SELECT SectorId, COUNT(Assessment_Id) AS AssessmentCount
FROM (
    SELECT ss.Assessment_Id, ss.SectorId as SectorId FROM ASSESSMENT_SECTOR_SUBSECTOR ss
    JOIN AVAILABLE_MATURITY_MODELS amm
    ON ss.Assessment_Id = amm.Assessment_Id
    WHERE amm.model_id = @maturity_model_id
    AND (@sector_id IS NULL OR (ss.SectorId = @sector_id))
) AS CombinedResult
GROUP BY SectorId;
END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[Analytics_Answers]'
GO

ALTER VIEW [dbo].[Analytics_Answers]
AS
SELECT Assessment_Id, Question_Or_Requirement_Id, Question_Type, CASE WHEN ANSWER.Answer_Text = 'A' OR
                  ANSWER.Answer_Text = 'Y' THEN N'Y' ELSE 'N' END AS Answer_Text
FROM     dbo.ANSWER
WHERE  (Answer_Text <> 'NA')
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[analytics_Compute_MaturityAll]'
GO

-- =============================================
-- Author:       Luke G, Lilly, Barry
-- Create date:  4-6-2022
-- Description:  18 stored procedures for analytics.
--               This procedure returns the AVG, MIN, MAX, MEDIAN Question Group Heading
--               for the Question_Type 'Maturity' for all sectors and industries.
--
-- Modification: 12-NOV-2024
-- Author:       Randy
-- Description:  Made sector and industry parameters optional, to cast a wider net.
--               Added consideration for a sector and industry stored in DETAILS_DEMOGRAPHICS.
--               Groupings are now sorted in sequence order rather than alphabetically.
-- =============================================
ALTER PROCEDURE [dbo].[analytics_Compute_MaturityAll]
    @maturity_model_id  INT,
    @sector_id          INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- Drop temp tables if they exist
    IF OBJECT_ID('tempdb..#Temp')  IS NOT NULL DROP TABLE #Temp;
    IF OBJECT_ID('tempdb..#Temp2') IS NOT NULL DROP TABLE #Temp2;
    IF OBJECT_ID('tempdb..#Temp3') IS NOT NULL DROP TABLE #Temp3;

    -- -------------------------------------------------------------------------
    -- Step 1: Get the base data
    -- -------------------------------------------------------------------------
    SELECT
        a.Assessment_Id,
        Question_Group,
        Answer_Text,
        ISNULL(COUNT(a.Answer_Text), 0) AS Answer_Count,
        SUM(ISNULL(COUNT(Answer_Text), 0))
            OVER (PARTITION BY a.Assessment_Id, Question_Group) AS Total,
        CAST(
            ISNULL(
                (
                    CAST(COUNT(a.Answer_Text) AS FLOAT)
                    / ISNULL(NULLIF(SUM(COUNT(Answer_Text))
                        OVER (PARTITION BY a.Assessment_Id, Question_Group), 0), 1)
                ) * 100,
                0
            )
        AS FLOAT) AS [Percentage]
    INTO #Temp
    FROM [Analytics_Answers] a
    JOIN MATURITY_QUESTIONS q ON a.Question_Or_Requirement_Id = q.Mat_Question_Id
    JOIN ANALYTICS_MATURITY_GROUPINGS g ON q.Mat_Question_Id = g.Maturity_Question_Id
    LEFT JOIN ASSESSMENT_SECTOR_SUBSECTOR ddsector ON a.Assessment_Id = ddsector.Assessment_Id
    WHERE
        a.Question_Type = 'Maturity'
        AND q.Is_Answerable = 1
        AND q.Maturity_Model_Id = @maturity_model_id
        AND g.Maturity_Model_Id = @maturity_model_id
        AND NULLIF(@sector_id, ddsector.SectorId) IS NULL
    GROUP BY
        a.Assessment_Id,
        Question_Group,
        Answer_Text;

    -- -------------------------------------------------------------------------
    -- Step 2: Handle all-Yes, all-No, and mixed answer cases
    -- -------------------------------------------------------------------------

    -- Capture Yes answers and mixed cases
    SELECT *
    INTO #Temp2
    FROM #Temp
    WHERE Answer_Text = 'Y';

    -- Capture all-No cases (no Yes answers exist; treat percentage as 0)
    INSERT INTO #Temp2
    SELECT
        Assessment_Id,
        Question_Group,
        Answer_Text = 'Y',
        Answer_Count,
        Total,
        [Percentage] = 0
    FROM #Temp
    WHERE Answer_Text = 'N'
      AND Answer_Count = Total;

    -- -------------------------------------------------------------------------
    -- Step 3: Calculate MIN, MAX, AVG per grouping
    -- -------------------------------------------------------------------------
    SELECT
        G1.Question_Group AS Question_Group_Heading,
        G1.Global_Sequence,
        MIN(ISNULL(G2.[Percentage], 0)) AS [minimum],
        MAX(ISNULL(G2.[Percentage], 0)) AS [maximum],
        AVG(ISNULL(G2.[Percentage], 0)) AS [average]
    INTO #Temp3
    FROM (
        SELECT DISTINCT
            Question_Group,
            Global_Sequence
        FROM ANALYTICS_MATURITY_GROUPINGS
        WHERE Maturity_Model_Id = @maturity_model_id
    ) G1
    LEFT JOIN #Temp2 G2 ON G1.Question_Group = G2.Question_Group
    GROUP BY
        G1.Question_Group,
        G1.Global_Sequence;

    -- -------------------------------------------------------------------------
    -- Step 4: Add median and return final result set
    -- -------------------------------------------------------------------------
    SELECT
        a.Question_Group_Heading,
        CAST(a.minimum AS FLOAT) AS minimum,
        CAST(a.maximum AS FLOAT) AS maximum,
        CAST(a.average AS FLOAT) AS average,
        ISNULL(b.median, 0) AS median
    FROM #Temp3 a
    LEFT JOIN (
        SELECT DISTINCT
            Question_Group AS Question_Group_Heading,
            ISNULL(
                PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY [Percentage])
                    OVER (PARTITION BY Question_Group),
                0
            ) AS median
        FROM #Temp2
    ) b ON a.Question_Group_Heading = b.Question_Group_Heading
    ORDER BY
        a.Global_Sequence;

END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[analytics_compute_single_averages_maturity]'
GO

-- =============================================
-- Author:      Barry
-- Create date: 4/6/2022
-- Description: Average for maturity model
-- =============================================
ALTER PROCEDURE [dbo].[analytics_compute_single_averages_maturity]
    @assessment_id     INT,
    @maturity_model_id INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        G1.Title,
        G1.Answer_Text,
        ISNULL(G2.Answer_Count, 0) AS Answer_Count,
        ISNULL(G2.Total, 0) AS Total,
        ISNULL(G2.Percentage, 0) AS [Percentage]
    FROM (
        SELECT DISTINCT
            Assessment_Id  = @assessment_id,
            Question_Group AS Title,
            Global_Sequence,
            Answer_Text    = 'Y'
        FROM ANALYTICS_MATURITY_GROUPINGS
        WHERE Maturity_Model_Id = @maturity_model_id
    ) G1
    LEFT JOIN (
        SELECT
            Question_Group AS Title,
            Answer_Text,
            COUNT(Answer_Text) AS Answer_Count,
            SUM(COUNT(Answer_Text))
                OVER (PARTITION BY Question_Group) AS Total,
            CAST(
                ISNULL(
                    (
                        CAST(COUNT(a.Answer_Text) AS FLOAT)
                        / ISNULL(NULLIF(SUM(COUNT(Answer_Text))
                            OVER (PARTITION BY Question_Group), 0), 1)
                    ) * 100,
                    0
                )
            AS FLOAT) AS [Percentage]
        FROM Analytics_Answers a
        JOIN ANALYTICS_MATURITY_GROUPINGS g ON a.Question_Or_Requirement_Id = g.Maturity_Question_Id
        JOIN MATURITY_QUESTIONS mq ON a.Question_Or_Requirement_Id = mq.Mat_Question_Id
        WHERE Assessment_Id = @assessment_id
          AND mq.Is_Answerable = 1
        GROUP BY
            Question_Group,
            Answer_Text
    ) G2 ON G1.Title = G2.Title AND G1.Answer_Text = G2.Answer_Text
    WHERE G1.Answer_Text = 'Y'
    ORDER BY Global_Sequence;

END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[analytics_Compute_standard_all]'
GO

-- =============================================
-- Author:		Barry H
-- Create date: 4-19-2022
-- =============================================
ALTER PROCEDURE [dbo].[analytics_Compute_standard_all]
	@assessment_id int, --default assessment_id the mode will be pulled from this assessment
	@set_name nvarchar(20), --this is the standard set name key
	@sector_id int,
	@industry_id int	
AS
BEGIN
	SET NOCOUNT ON;
	declare @ApplicationMode nvarchar(20)

	exec dbo.GetApplicationModeDefault @assessment_id, @ApplicationMode output

if(@ApplicationMode = 'Questions Based')	
begin
	
	IF OBJECT_ID('tempdb..#Temp') IS NOT NULL DROP TABLE #Temp
	IF OBJECT_ID('tempdb..#Temp2') IS NOT NULL DROP TABLE #Temp2

	---This is step 1 get the base data
	
	select a.Assessment_Id,Question_Group_Heading, Answer_Text, count(answer_text) qc into #temp
	FROM Analytics_Answers a 
	join NEW_QUESTION c on a.Question_Or_Requirement_Id=c.Question_Id
	join vQuestion_Headings h on c.Heading_Pair_Id=h.heading_pair_Id		
	join NEW_QUESTION_SETS s on c.Question_Id = s.Question_Id			
	join AVAILABLE_STANDARDS avs on a.Assessment_Id=avs.Assessment_Id	
	left join ASSESSMENT_SECTOR_SUBSECTOR ss on a.Assessment_Id = ss.Assessment_Id
	where a.Answer_Text != 'NA' and a.question_type = 'Question' 												
			and s.Set_Name = @set_name
			and avs.Set_Name = @set_name
		and nullif(@sector_id, ss.sectorid) is null
	group by a.assessment_id, Question_Group_Heading, Answer_Text 
	order by Question_Group_Heading, Assessment_Id

	insert #temp
	select	assessment_id=@assessment_id,
	a.Question_Group_Heading,Answer_Text='Y',qc=0
	from (
	select Question_Group_Heading	FROM  
	NEW_QUESTION c 
	join vQuestion_Headings h on c.Heading_Pair_Id=h.heading_pair_Id		
	join NEW_QUESTION_SETS s on c.Question_Id = s.Question_Id			
	where  s.Set_Name = @set_name
	group by Question_Group_Heading) A left join #temp b on a.Question_Group_Heading=b.Question_Group_Heading
	where b.Question_Group_Heading is null

	--this is step 2 calculate percentages and group up by assessment id and question group
	select *, cast(qc as float)/cast( ISNULL(nullif(total,0),1) as float) [percentage] into #temp2
	from (		
		select Assessment_Id, Question_Group_Heading, answer_text,qc, sum(qc) over(partition by assessment_id,question_group_heading) as total
		from #temp
		group by Assessment_Id,Question_Group_Heading, answer_text, qc)  a

	--this is step 3 fix the outside cases where the answers are either all no or all yes
	--case 100% No
	--case 100% Yes
	--case mixed yes and no
	insert #temp2
	select assessment_id,QUESTION_GROUP_HEADING,'Y',qc,total, [percentage]=0 from #temp2 where Answer_Text = 'N' and qc=total
	insert #temp2
	select assessment_id,QUESTION_GROUP_HEADING,'Y',qc,total, [percentage] from #temp2 where Answer_Text = 'Y' 


	--finally step 4 give me the answers with the calculated median
	 select a.QUESTION_GROUP_HEADING, a.minimum, a.maximum, a.average, b.median--, b.rown 
          from 
          (
                 select QUESTION_GROUP_HEADING, minimum, maximum, average 
                 from (
                                    select question_group_heading, (ISNULL(min([percentage]),0) *100) minimum, 
                                       (ISNULL(max(percentage),0) *100) maximum, 
                                       (ISNULL(AVG(percentage),0) *100) average
                                       from #Temp2
                                       group by Question_Group_Heading
                 ) qryA
          ) a
          join
          (
                 select QUESTION_GROUP_HEADING, median, rown 
                 from 
                 (
                         select QUESTION_GROUP_HEADING, 
                                    isnull(PERCENTILE_disc(0.5) WITHIN GROUP (ORDER BY [percentage]) OVER (PARTITION BY Question_Group_Heading),0) AS median,
                                    ROW_NUMBER() OVER (PARTITION BY question_group_heading ORDER BY question_group_heading) rown
                         from (
                                           select question_group_heading, 
                                                  (ISNULL([percentage],0) *100) [percentage]
                                              from #Temp2
                         ) qry
                 ) qryB
                 where rown = 1
          ) b ON a.QUESTION_GROUP_HEADING = b.QUESTION_GROUP_HEADING
end
else 
begin 
	IF OBJECT_ID('tempdb..#tempR') IS NOT NULL DROP TABLE #tempR	 
	IF OBJECT_ID('tempdb..#tempR2') IS NOT NULL DROP TABLE #tempR2	 

	
	select a.Assessment_Id,Standard_Category as Question_Group_Heading, Answer_Text
	,count(answer_text) qc into #tempR
	FROM Analytics_Answers a 
	join NEW_REQUIREMENT c on a.Question_Or_Requirement_Id=c.Requirement_Id
	join REQUIREMENT_SETS s on c.Requirement_Id=s.Requirement_Id	
	join AVAILABLE_STANDARDS avs on a.Assessment_Id=avs.Assessment_Id		
	left join ASSESSMENT_SECTOR_SUBSECTOR ss on a.Assessment_Id = ss.Assessment_Id
	where a.Answer_Text != 'NA' and a.question_type = 'Requirement' 												
			and s.Set_Name = @set_name
			and avs.Set_Name = @set_name
			and nullif(@sector_id, ss.sectorid) is null
	group by a.assessment_id, Standard_Category, Answer_Text
	order by Question_Group_Heading, Assessment_Id

	insert #tempR
	select	assessment_id=@assessment_id,
	a.Question_Group_Heading,Answer_Text='Y',qc=0
	from (
	select distinct STANDARD_CATEGORY as Question_Group_Heading	FROM  
	NEW_REQUIREMENT c
	join REQUIREMENT_SETS s on c.Requirement_Id=s.Requirement_Id			
	where  s.Set_Name = @set_name
	group by Standard_Category) A left join #tempR b on a.Question_Group_Heading=b.Question_Group_Heading
	where b.Question_Group_Heading is null






	select *, cast(qc as float)/cast( ISNULL(nullif(total,0),1) as float) [percentage] into #tempR2
	from (		
		select Assessment_Id, Question_Group_Heading, answer_text,qc, sum(qc) over(partition by assessment_id,question_group_heading) as total
		from #tempR
		group by Assessment_Id,Question_Group_Heading, answer_text, qc)  a

	--case 100% No
	--case 100% Yes
	--case mixed yes and no
	insert #tempR2
	select assessment_id,QUESTION_GROUP_HEADING,'Y',qc,total, [percentage]=0 from #tempR2 where Answer_Text = 'N' and qc=total
	insert #tempR2
	select assessment_id,QUESTION_GROUP_HEADING,'Y',qc,total, [percentage] from #tempR2 where Answer_Text = 'Y' 


  select a.QUESTION_GROUP_HEADING, a.minimum, a.maximum, a.average, b.median--, b.rown 
          from 
          (
				select question_group_heading, (ISNULL(min([percentage]),0) *100) minimum, 
                (ISNULL(max(percentage),0) *100) maximum, 
                (ISNULL(AVG(percentage),0) *100) average
                from #tempR2
                group by Question_Group_Heading          
          ) a
          left join
          (
                 select QUESTION_GROUP_HEADING, median, rown 
                 from 
                 (
                         select QUESTION_GROUP_HEADING, 
                                    isnull(PERCENTILE_disc(0.5) WITHIN GROUP (ORDER BY [percentage]) OVER (PARTITION BY Question_Group_Heading),0) AS median,
                                    ROW_NUMBER() OVER (PARTITION BY question_group_heading ORDER BY question_group_heading) rown
                         from (
                                           select question_group_heading, 
                                                  (ISNULL([percentage],0) *100) [percentage]
                                              from #tempR2
                         ) qry
                 ) qryB
                 where rown = 1
          ) b ON a.QUESTION_GROUP_HEADING = b.QUESTION_GROUP_HEADING
end
END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[analytics_compute_single_averages_standard]'
GO

-- =============================================
-- Author:		Barry
-- Create date: 4/21/2022
-- Description:	average for maturity model
-- =============================================
ALTER PROCEDURE [dbo].[analytics_compute_single_averages_standard]
	@assessment_id int,
	@set_name nvarchar(20)
AS
BEGIN
SET NOCOUNT ON;
	declare @ApplicationMode nvarchar(20)

	exec dbo.GetApplicationModeDefault @assessment_id, @ApplicationMode output

if(@ApplicationMode = 'Questions Based')	
begin
	IF OBJECT_ID('tempdb..#temp') IS NOT NULL DROP TABLE #temp	 
	
	select a.Assessment_Id,Question_Group_Heading, Answer_Text,count(answer_text) qc into #temp
	FROM Analytics_Answers a 
	join NEW_QUESTION c on a.Question_Or_Requirement_Id=c.Question_Id
	join vQuestion_Headings h on c.Heading_Pair_Id=h.heading_pair_Id		
	join NEW_QUESTION_SETS s on c.Question_Id = s.Question_Id			
	join AVAILABLE_STANDARDS avs on a.Assessment_Id=avs.Assessment_Id		
	where a.Answer_Text != 'NA' and a.question_type = 'Question' 												
			and s.Set_Name = @set_name
			and avs.Set_Name = @set_name
			and a.Assessment_Id = @assessment_id
	group by a.assessment_id, Question_Group_Heading, Answer_Text 
	order by Question_Group_Heading, Assessment_Id

	select 
	all1.Question_Group_Heading,	
	round((ISNULL(all2.percentage,0) *100),0) average 
	from (
	select distinct Question_Group_Heading,[percentage] = 0
	FROM NEW_QUESTION c 
	join vQUESTION_HEADINGS h on c.Heading_Pair_Id=h.Heading_Pair_Id
	join NEW_QUESTION_SETS s on c.Question_Id=s.Question_Id
	where Set_Name = @set_name)
		all1 left join (		
			select *, cast(qc as float)/cast( ISNULL(nullif(total,0),1) as float) [percentage]
			from (		
				select Assessment_Id, Question_Group_Heading, answer_text,qc, sum(qc) over(partition by assessment_id,question_group_heading) as total
				from #temp
				group by Assessment_Id,Question_Group_Heading, answer_text, qc)  a
		where answer_text = 'Y'		
	) all2 on all1.Question_Group_Heading=all2.Question_Group_Heading
end
else 
begin 
	IF OBJECT_ID('tempdb..#tempR') IS NOT NULL DROP TABLE #tempR	 

	
	select a.Assessment_Id,Standard_Category as Question_Group_Heading, Answer_Text
	,count(answer_text) qc into #tempR
	FROM Analytics_Answers a 
	join NEW_REQUIREMENT c on a.Question_Or_Requirement_Id=c.Requirement_Id
	join REQUIREMENT_SETS s on c.Requirement_Id=s.Requirement_Id	
	join AVAILABLE_STANDARDS avs on a.Assessment_Id=avs.Assessment_Id		
	where a.Answer_Text != 'NA' and a.question_type = 'Requirement' 												
			and s.Set_Name = @set_name
			and avs.Set_Name = @set_name			
			and a.assessment_id= @assessment_id
	group by a.assessment_id, Standard_Category, Answer_Text
	order by Question_Group_Heading, Assessment_Id

	select 
	all1.Question_Group_Heading,	
	round((ISNULL(all2.[percentage],0) *100),0) [percentage]
	from (
	select distinct Standard_Category as Question_Group_Heading, [Percentage] = 0
	FROM NEW_REQUIREMENT c 
	join REQUIREMENT_SETS s on c.Requirement_Id=s.Requirement_Id	
	where Set_Name = @set_name)
		all1 left join (		
			select *, cast(qc as float)/cast( ISNULL(nullif(total,0),1) as float) [percentage]
			from (		
				select Assessment_Id, Question_Group_Heading, answer_text,qc, sum(qc) over(partition by assessment_id,question_group_heading) as total
				from #tempR
				group by Assessment_Id,Question_Group_Heading, answer_text, qc)  a
		where answer_text = 'Y')
	 all2 on all1.Question_Group_Heading=all2.Question_Group_Heading
end
END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[fn_diagramobjects]'
GO

CREATE FUNCTION [dbo].[fn_diagramobjects]	 () 
	RETURNS int
	WITH EXECUTE AS N'dbo'
	AS
	BEGIN
		declare @id_upgraddiagrams		int
		declare @id_sysdiagrams			int
		declare @id_helpdiagrams		int
		declare @id_helpdiagramdefinition	int
		declare @id_creatediagram	int
		declare @id_renamediagram	int
		declare @id_alterdiagram 	int 
		declare @id_dropdiagram		int
		declare @InstalledObjects	int

		select @InstalledObjects = 0

		select 	@id_upgraddiagrams = object_id(N'dbo.sp_upgraddiagrams'),
			@id_sysdiagrams = object_id(N'dbo.sysdiagrams'),
			@id_helpdiagrams = object_id(N'dbo.sp_helpdiagrams'),
			@id_helpdiagramdefinition = object_id(N'dbo.sp_helpdiagramdefinition'),
			@id_creatediagram = object_id(N'dbo.sp_creatediagram'),
			@id_renamediagram = object_id(N'dbo.sp_renamediagram'),
			@id_alterdiagram = object_id(N'dbo.sp_alterdiagram'), 
			@id_dropdiagram = object_id(N'dbo.sp_dropdiagram')

		if @id_upgraddiagrams is not null
			select @InstalledObjects = @InstalledObjects + 1
		if @id_sysdiagrams is not null
			select @InstalledObjects = @InstalledObjects + 2
		if @id_helpdiagrams is not null
			select @InstalledObjects = @InstalledObjects + 4
		if @id_helpdiagramdefinition is not null
			select @InstalledObjects = @InstalledObjects + 8
		if @id_creatediagram is not null
			select @InstalledObjects = @InstalledObjects + 16
		if @id_renamediagram is not null
			select @InstalledObjects = @InstalledObjects + 32
		if @id_alterdiagram  is not null
			select @InstalledObjects = @InstalledObjects + 64
		if @id_dropdiagram is not null
			select @InstalledObjects = @InstalledObjects + 128
		
		return @InstalledObjects 
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NCSF_MIGRATION2]'
GO
CREATE TABLE [dbo].[NCSF_MIGRATION2]
(
[V2id] [int] NULL,
[V2Title] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1Title] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1Id] [int] NULL
) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[sp_alterdiagram]'
GO

CREATE PROCEDURE [dbo].[sp_alterdiagram]	
	(
		@diagramname 	sysname,
		@owner_id	int	= null,
		@version 	int,
		@definition 	varbinary(max)
	)
	WITH EXECUTE AS 'dbo'
	AS
	BEGIN
		set nocount on
	
		declare @theId 			int
		declare @retval 		int
		declare @IsDbo 			int
		
		declare @UIDFound 		int
		declare @DiagId			int
		declare @ShouldChangeUID	int
	
		if(@diagramname is null)
		begin
			RAISERROR ('Invalid ARG', 16, 1)
			return -1
		end
	
		execute as caller;
		select @theId = DATABASE_PRINCIPAL_ID();	 
		select @IsDbo = IS_MEMBER(N'db_owner'); 
		if(@owner_id is null)
			select @owner_id = @theId;
		revert;
	
		select @ShouldChangeUID = 0
		select @DiagId = diagram_id, @UIDFound = principal_id from dbo.sysdiagrams where principal_id = @owner_id and name = @diagramname 
		
		if(@DiagId IS NULL or (@IsDbo = 0 and @theId <> @UIDFound))
		begin
			RAISERROR ('Diagram does not exist or you do not have permission.', 16, 1);
			return -3
		end
	
		if(@IsDbo <> 0)
		begin
			if(@UIDFound is null or USER_NAME(@UIDFound) is null) -- invalid principal_id
			begin
				select @ShouldChangeUID = 1 ;
			end
		end

		-- update dds data			
		update dbo.sysdiagrams set definition = @definition where diagram_id = @DiagId ;

		-- change owner
		if(@ShouldChangeUID = 1)
			update dbo.sysdiagrams set principal_id = @theId where diagram_id = @DiagId ;

		-- update dds version
		if(@version is not null)
			update dbo.sysdiagrams set version = @version where diagram_id = @DiagId ;

		return 0
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[sp_creatediagram]'
GO

CREATE PROCEDURE [dbo].[sp_creatediagram]	
	(
		@diagramname 	sysname,
		@owner_id		int	= null, 	
		@version 		int,
		@definition 	varbinary(max)
	)
	WITH EXECUTE AS 'dbo'
	AS
	BEGIN
		set nocount on
	
		declare @theId int
		declare @retval int
		declare @IsDbo	int
		declare @userName sysname
		if(@version is null or @diagramname is null)
		begin
			RAISERROR (N'E_INVALIDARG', 16, 1);
			return -1
		end
	
		execute as caller;
		select @theId = DATABASE_PRINCIPAL_ID(); 
		select @IsDbo = IS_MEMBER(N'db_owner');
		revert; 
		
		if @owner_id is null
		begin
			select @owner_id = @theId;
		end
		else
		begin
			if @theId <> @owner_id
			begin
				if @IsDbo = 0
				begin
					RAISERROR (N'E_INVALIDARG', 16, 1);
					return -1
				end
				select @theId = @owner_id
			end
		end
		-- next 2 line only for test, will be removed after define name unique
		if EXISTS(select diagram_id from dbo.sysdiagrams where principal_id = @theId and name = @diagramname)
		begin
			RAISERROR ('The name is already used.', 16, 1);
			return -2
		end
	
		insert into dbo.sysdiagrams(name, principal_id , version, definition)
				VALUES(@diagramname, @theId, @version, @definition) ;
		
		select @retval = @@IDENTITY 
		return @retval
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[sp_dropdiagram]'
GO

CREATE PROCEDURE [dbo].[sp_dropdiagram]	
	(
		@diagramname 	sysname,
		@owner_id	int	= null
	)
	WITH EXECUTE AS 'dbo'
	AS
	BEGIN
		set nocount on
		declare @theId 			int
		declare @IsDbo 			int
		
		declare @UIDFound 		int
		declare @DiagId			int
	
		if(@diagramname is null)
		begin
			RAISERROR ('Invalid value', 16, 1);
			return -1
		end
	
		EXECUTE AS CALLER;
		select @theId = DATABASE_PRINCIPAL_ID();
		select @IsDbo = IS_MEMBER(N'db_owner'); 
		if(@owner_id is null)
			select @owner_id = @theId;
		REVERT; 
		
		select @DiagId = diagram_id, @UIDFound = principal_id from dbo.sysdiagrams where principal_id = @owner_id and name = @diagramname 
		if(@DiagId IS NULL or (@IsDbo = 0 and @UIDFound <> @theId))
		begin
			RAISERROR ('Diagram does not exist or you do not have permission.', 16, 1)
			return -3
		end
	
		delete from dbo.sysdiagrams where diagram_id = @DiagId;
	
		return 0;
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[sp_helpdiagramdefinition]'
GO

CREATE PROCEDURE [dbo].[sp_helpdiagramdefinition]	
	(
		@diagramname 	sysname,
		@owner_id	int	= null 		
	)
	WITH EXECUTE AS N'dbo'
	AS
	BEGIN
		set nocount on

		declare @theId 		int
		declare @IsDbo 		int
		declare @DiagId		int
		declare @UIDFound	int
	
		if(@diagramname is null)
		begin
			RAISERROR (N'E_INVALIDARG', 16, 1);
			return -1
		end
	
		execute as caller;
		select @theId = DATABASE_PRINCIPAL_ID();
		select @IsDbo = IS_MEMBER(N'db_owner');
		if(@owner_id is null)
			select @owner_id = @theId;
		revert; 
	
		select @DiagId = diagram_id, @UIDFound = principal_id from dbo.sysdiagrams where principal_id = @owner_id and name = @diagramname;
		if(@DiagId IS NULL or (@IsDbo = 0 and @UIDFound <> @theId ))
		begin
			RAISERROR ('Diagram does not exist or you do not have permission.', 16, 1);
			return -3
		end

		select version, definition FROM dbo.sysdiagrams where diagram_id = @DiagId ; 
		return 0
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[sp_helpdiagrams]'
GO

CREATE PROCEDURE [dbo].[sp_helpdiagrams]	
	(
		@diagramname sysname = NULL,
		@owner_id int = NULL
	)
	WITH EXECUTE AS N'dbo'
	AS
	BEGIN
		DECLARE @user sysname
		DECLARE @dboLogin bit
		EXECUTE AS CALLER;
			SET @user = USER_NAME();
			SET @dboLogin = CONVERT(bit,IS_MEMBER('db_owner'));
		REVERT;
		SELECT
			[Database] = DB_NAME(),
			[Name] = name,
			[ID] = diagram_id,
			[Owner] = USER_NAME(principal_id),
			[OwnerID] = principal_id
		FROM
			sysdiagrams
		WHERE
			(@dboLogin = 1 OR USER_NAME(principal_id) = @user) AND
			(@diagramname IS NULL OR name = @diagramname) AND
			(@owner_id IS NULL OR principal_id = @owner_id)
		ORDER BY
			4, 5, 1
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[sp_renamediagram]'
GO

CREATE PROCEDURE [dbo].[sp_renamediagram]	
	(
		@diagramname 		sysname,
		@owner_id		int	= null,
		@new_diagramname	sysname
	
	)
	WITH EXECUTE AS 'dbo'
	AS
	BEGIN
		set nocount on
		declare @theId 			int
		declare @IsDbo 			int
		
		declare @UIDFound 		int
		declare @DiagId			int
		declare @DiagIdTarg		int
		declare @u_name			sysname
		if((@diagramname is null) or (@new_diagramname is null))
		begin
			RAISERROR ('Invalid value', 16, 1);
			return -1
		end
	
		EXECUTE AS CALLER;
		select @theId = DATABASE_PRINCIPAL_ID();
		select @IsDbo = IS_MEMBER(N'db_owner'); 
		if(@owner_id is null)
			select @owner_id = @theId;
		REVERT;
	
		select @u_name = USER_NAME(@owner_id)
	
		select @DiagId = diagram_id, @UIDFound = principal_id from dbo.sysdiagrams where principal_id = @owner_id and name = @diagramname 
		if(@DiagId IS NULL or (@IsDbo = 0 and @UIDFound <> @theId))
		begin
			RAISERROR ('Diagram does not exist or you do not have permission.', 16, 1)
			return -3
		end
	
		-- if((@u_name is not null) and (@new_diagramname = @diagramname))	-- nothing will change
		--	return 0;
	
		if(@u_name is null)
			select @DiagIdTarg = diagram_id from dbo.sysdiagrams where principal_id = @theId and name = @new_diagramname
		else
			select @DiagIdTarg = diagram_id from dbo.sysdiagrams where principal_id = @owner_id and name = @new_diagramname
	
		if((@DiagIdTarg is not null) and  @DiagId <> @DiagIdTarg)
		begin
			RAISERROR ('The name is already used.', 16, 1);
			return -2
		end		
	
		if(@u_name is null)
			update dbo.sysdiagrams set [name] = @new_diagramname, principal_id = @theId where diagram_id = @DiagId
		else
			update dbo.sysdiagrams set [name] = @new_diagramname where diagram_id = @DiagId
		return 0
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[sp_upgraddiagrams]'
GO

CREATE PROCEDURE [dbo].[sp_upgraddiagrams]	
	AS
	BEGIN
		IF OBJECT_ID(N'dbo.sysdiagrams') IS NOT NULL
			return 0;
	
		CREATE TABLE dbo.sysdiagrams
		(
			name sysname NOT NULL,
			principal_id int NOT NULL,	-- we may change it to varbinary(85)
			diagram_id int PRIMARY KEY IDENTITY,
			version int,
	
			definition varbinary(max)
			CONSTRAINT UK_principal_name UNIQUE
			(
				principal_id,
				name
			)
		);


		/* Add this if we need to have some form of extended properties for diagrams */
		/*
		IF OBJECT_ID(N'dbo.sysdiagram_properties') IS NULL
		BEGIN
			CREATE TABLE dbo.sysdiagram_properties
			(
				diagram_id int,
				name sysname,
				value varbinary(max) NOT NULL
			)
		END
		*/

		IF OBJECT_ID(N'dbo.dtproperties') IS NOT NULL
		begin
			insert into dbo.sysdiagrams
			(
				[name],
				[principal_id],
				[version],
				[definition]
			)
			select	 
				convert(sysname, dgnm.[uvalue]),
				DATABASE_PRINCIPAL_ID(N'dbo'),			-- will change to the sid of sa
				0,							-- zero for old format, dgdef.[version],
				dgdef.[lvalue]
			from dbo.[dtproperties] dgnm
				inner join dbo.[dtproperties] dggd on dggd.[property] = 'DtgSchemaGUID' and dggd.[objectid] = dgnm.[objectid]	
				inner join dbo.[dtproperties] dgdef on dgdef.[property] = 'DtgSchemaDATA' and dgdef.[objectid] = dgnm.[objectid]
				
			where dgnm.[property] = 'DtgSchemaNAME' and dggd.[uvalue] like N'_EA3E6268-D998-11CE-9454-00AA00A3F36E_' 
			return 2;
		end
		return 1;
	END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding constraints to [dbo].[FINDING]'
GO
ALTER TABLE [dbo].[FINDING] ADD CONSTRAINT [CHK_Single_Reference] CHECK ((case  when [Answer_ID] IS NOT NULL then (1) else (0) end+case  when [Assessment_ID] IS NOT NULL then (1) else (0) end=(1)))
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[ASSESSMENT_SECTOR_SUBSECTOR]'
GO
ALTER TABLE [dbo].[ASSESSMENT_SECTOR_SUBSECTOR] ADD CONSTRAINT [FK__ASSESSMEN__Asses__4CCB4BEB] FOREIGN KEY ([Assessment_Id]) REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
GO
ALTER TABLE [dbo].[ASSESSMENT_SECTOR_SUBSECTOR] ADD CONSTRAINT [FK__ASSESSMEN__Indus__4EB3945D] FOREIGN KEY ([IndustryId]) REFERENCES [dbo].[SECTOR_INDUSTRY] ([IndustryId])
GO
ALTER TABLE [dbo].[ASSESSMENT_SECTOR_SUBSECTOR] ADD CONSTRAINT [FK__ASSESSMEN__Secto__4DBF7024] FOREIGN KEY ([SectorId]) REFERENCES [dbo].[SECTOR] ([SectorId])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[FINDING]'
GO
ALTER TABLE [dbo].[FINDING] ADD CONSTRAINT [FK__FINDING__Assessm__1798699D] FOREIGN KEY ([Assessment_ID]) REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[GALLERY_ITEM_USER]'
GO
ALTER TABLE [dbo].[GALLERY_ITEM_USER] ADD CONSTRAINT [FK_GALLERY_ITEM_USER_GALLERY_ITEM] FOREIGN KEY ([Gallery_Item_Guid]) REFERENCES [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid])
GO
ALTER TABLE [dbo].[GALLERY_ITEM_USER] ADD CONSTRAINT [FK_GALLERY_ITEM_USER_USERS] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USERS] ([UserId])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[GROUPING_SELECTION]'
GO
ALTER TABLE [dbo].[GROUPING_SELECTION] ADD CONSTRAINT [FK_GROUP_SELECT_ASSESSMENTS] FOREIGN KEY ([Assessment_Id]) REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GROUPING_SELECTION] ADD CONSTRAINT [FK_GROUP_SELECT_GROUP] FOREIGN KEY ([Grouping_Id]) REFERENCES [dbo].[MATURITY_GROUPINGS] ([Grouping_Id]) ON DELETE CASCADE ON UPDATE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering permissions on  [dbo].[fn_diagramobjects]'
GO
DENY EXECUTE ON  [dbo].[fn_diagramobjects] TO [guest]
GO
GRANT EXECUTE ON  [dbo].[fn_diagramobjects] TO [public]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering permissions on  [dbo].[sp_alterdiagram]'
GO
DENY EXECUTE ON  [dbo].[sp_alterdiagram] TO [guest]
GO
GRANT EXECUTE ON  [dbo].[sp_alterdiagram] TO [public]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering permissions on  [dbo].[sp_creatediagram]'
GO
DENY EXECUTE ON  [dbo].[sp_creatediagram] TO [guest]
GO
GRANT EXECUTE ON  [dbo].[sp_creatediagram] TO [public]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering permissions on  [dbo].[sp_dropdiagram]'
GO
DENY EXECUTE ON  [dbo].[sp_dropdiagram] TO [guest]
GO
GRANT EXECUTE ON  [dbo].[sp_dropdiagram] TO [public]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering permissions on  [dbo].[sp_helpdiagramdefinition]'
GO
DENY EXECUTE ON  [dbo].[sp_helpdiagramdefinition] TO [guest]
GO
GRANT EXECUTE ON  [dbo].[sp_helpdiagramdefinition] TO [public]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering permissions on  [dbo].[sp_helpdiagrams]'
GO
DENY EXECUTE ON  [dbo].[sp_helpdiagrams] TO [guest]
GO
GRANT EXECUTE ON  [dbo].[sp_helpdiagrams] TO [public]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering permissions on  [dbo].[sp_renamediagram]'
GO
DENY EXECUTE ON  [dbo].[sp_renamediagram] TO [guest]
GO
GRANT EXECUTE ON  [dbo].[sp_renamediagram] TO [public]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	PRINT 'The database update failed'
END
GO
