SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL Serializable
GO
BEGIN TRANSACTION

PRINT(N'Update rows in [dbo].[MATURITY_QUESTIONS]')
UPDATE [dbo].[MATURITY_QUESTIONS] SET [Services]=N'<div><a href="https://www.cisa.gov/cisa-tabletop-exercise-packages" target="_blank">CISA Tabletop Exercise Packages</a></div><div><a href="https://www.cisa.gov/sites/default/files/publications/Incident-Response-Plan-Basics_508c.pdf" target="_blank">Incident Response Plan (IRP) Basics</a></div><div><a href="https://www.cisa.gov/critical-infrastructure-exercises" target="_blank">Critical Infrastructure Exercises Support</a></div>' WHERE [Mat_Question_Id] = 8542
UPDATE [dbo].[MATURITY_QUESTIONS] SET [Services]=N'<div><a href="https://www.cisa.gov/resources-tools/resources/foundations-ot-cybersecurity-asset-inventory-guidance-owners-and-operators" target="_blank">Asset Inventory for OT</a></div><div><a href="https://www.cisa.gov/sites/default/files/c3vp/crr_resources_guides/CRR_Resource_Guide-AM.pdf" target="_blank">Asset Management</a></div><div><a href="https://www.cisa.gov/sites/default/files/publications/CISAInsights-Cyber-SecureHighValueAssets_S508C.pdf" target="_blank">CISA Insights: Secure High Value Assets (HVAs)</a></div>' WHERE [Mat_Question_Id] = 8545
UPDATE [dbo].[MATURITY_QUESTIONS] SET [Services]=N'<div><a href="https://www.cisa.gov/sites/default/files/c3vp/crr_resources_guides/CRR_Resource_Guide-CCM.pdf"
          target="_blank">Configuration and Change Management </a></div>' WHERE [Mat_Question_Id] = 8563
PRINT(N'Operation applied to 3 rows out of 5')

PRINT(N'Update rows in [dbo].[MATURITY_MODELS]')
UPDATE [dbo].[MATURITY_MODELS] SET [Questions_Alias]=N'Goals' WHERE [Maturity_Model_Id] = 11
UPDATE [dbo].[MATURITY_MODELS] SET [Questions_Alias]=N'Goals' WHERE [Maturity_Model_Id] = 18
UPDATE [dbo].[MATURITY_MODELS] SET [Questions_Alias]=N'Goals' WHERE [Maturity_Model_Id] = 20
UPDATE [dbo].[MATURITY_MODELS] SET [Questions_Alias]=N'Goals' WHERE [Maturity_Model_Id] = 21
PRINT(N'Operation applied to 4 rows out of 4')

PRINT(N'Add rows to [dbo].[GALLERY_ITEM]')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('7481093d-eefa-423c-8479-025bb74d0d63', N'nerc-cip.png', N'nerc-cip.png', N'{"Sets":["Nerc_Cip_R3"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This NERC-CIP standard was developed to assist industry stakeholders in electric power systems in North America with constructing and implementing their Cyber Security Plan.', NULL, N'NERC CIP-002 through CIP-009 Revision 3 ', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('1d673e6f-ad89-41b3-a264-02b463139030', N'sp800-82.jpeg', N'sp800-82.jpeg', N'{"Sets":["SP800-82 V2"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides guidance for establishing secure industrial control systems (ICS). Many of these controls are based on SP800-53 with minor modifications.', NULL, N'NIST SP 800-82 Revision 2', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('a8c5b590-dee3-4851-8ec0-09f8898954ab', N'critical-infrastructure.png', N'critical-infrastructure.png', N'{"Sets":["HLCIA"],"SALLevel":"Low","QuestionMode":"Questions"}', N'A question set developed to determine high level critical infrastructure cybersecurity, in short 34 question set', NULL, N'High Level Critical Infrastructure Assessment', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('22ae54d0-94a7-4c49-a2e4-0c9a3df0d312', N'cis-v8.png', N'cis-v8.png', N'{"Sets":["CSC_V8_IG1"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The CIS Controls are a prioritized set of safeguards to mitigate the most prevalent cyber-attacks against systems and networks.', NULL, N'CIS Controls Version 8 IG-1', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('faab0432-6285-49f2-a837-0fe66fef4ffa', N'default.jpeg', N'default.jpeg', N'{"Sets":["Standards"],"SALLevel":"Low","QuestionMode":"Questions"}', N'testStandards', NULL, N'All Questions From Standards', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('1092c438-b928-4dda-a104-13506dd360c4', N'tsa-pipeline.png', N'tsa-pipeline.png', N'{"Model":{"ModelName":"SD02 Owner"}}', N'<p>This is a list of the requirements stated in the directive.</p>', NULL, N'Security Directive (SD) Pipeline-2021-02 Series for Owners and Operators Requirements Current to D Release', 0, '2023-09-08 13:10:44.680')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('e4d8c03b-3a33-4f2d-bd72-160040aed1ba', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R5"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This publication contains a comprehensive catalog of technical and nontechnical security and privacy controls.', NULL, N'Draft NIST Special Publication 800-53 Revision 5', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('12d8b693-7ee3-4ada-b4fa-1af7f554f130', N'tsa-pipeline.png', N'tsa-pipeline.png', N'{"Model":{"ModelName":"SD02 Series"}}', N'<p>This assessment is a step by step walk through of the assessment process.</p>', NULL, N'Security Directive (SD) Pipeline-2021-02 Series Preparation Guide Current to D Release', 0, '2023-05-10 09:57:16.437')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('7cf3a4a1-56b6-40ad-ac66-1b1ac936a356', N'tsa-pipeline.png', N'tsa-pipeline.png', N'{"Sets":["TSA2018"],"SALLevel":"Low","QuestionMode":"Questions","HiddenScreens":["sal"]}', N'These basic guidelines are applicable to operational natural gas and hazardous liquid transmission pipeline systems.', NULL, N'Basic TSA Pipeline Security Guidelines March 2018 with April 2021 revision', 0, '2023-01-26 13:15:04.013')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('f8fa1cdc-63ac-4076-b00d-1f5dcb34e3a9', N'acet.png', N'acet.png', N'{"Model":{"ModelName":"ACET"}}', N'Called the Automated Cybersecurity Evaluation Toolbox (ACET), it provides a repeatable, measurable and transparent process.', NULL, N'ACET Maturity Assessment', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('edf05bdf-ed10-42c5-a147-2260a4ae5c16', N'operational_technology.jpeg', N'operational_technology.jpeg', N'{"Model":{"ModelName":"CPG"}}', N'The CPGs are a prioritized subset of IT and operational technology (OT) cybersecurity practices that critical infrastructure owners and operators can implement to meaningfully reduce the likelihood and impact of known risks and adversary techniques. The goals were informed by existing cybersecurity frameworks and guidance, as well as the real-world threats and adversary tactics, techniques, and procedures (TTPs) observed by CISA and its government and industry partners.  This assessment is intended to help organizations determine the extent to which they have implemented the Goals, and to aid in identifying areas for potential future investment.', NULL, N'CISA Cross-Sector Cybersecurity Performance Goals (CPG)', 0, '2022-10-28 15:14:29.693')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('ff43e99b-d6dd-409f-a07f-22f7aa55b9f3', N'CyberFlorida.png', N'CyberFlorida.png', N'{"Sets":["Florida_NCSF_V2"], "QuestionMode":"Questions", "Model":{"ModelName":"CPG"}, "Origin":"CF"}', N'This module was developed on behalf of The Florida Center for Cybersecurity (Cyber Florida).', NULL, N'Cyber Florida Mid-Level Assessment', 0, '2024-08-28 12:34:46.050')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('e7b895a9-a268-4baa-aa46-273319f2a730', N'key.jpeg', N'key.jpeg', N'{"Sets":["Key"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The Key questions are a reduced subset of select questions from the DHS Catalog of Recommendations.', NULL, N'Key Questions', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('f4509fb7-1729-437b-a486-27d7df8c85a8', N'pci.png', N'pci.png', N'{"Sets":["PCIDSS"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This document combines the 12 PCI DSS requirements and corresponding testing procedures into a security assessment tool.', NULL, N'Payment Card Industry (PCI) Data Security Standard', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('251080d8-9858-40fc-80e7-2e32c64c70a1', N'nerc-cip.png', N'nerc-cip.png', N'{"Sets":["Nerc_Cip_R5"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This NERC-CIP standard was developed to assist industry stakeholders with bulk electric power systems in North America.', NULL, N'NERC CIP-002 through CIP-011 Revision 5', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('5d692bd4-87d0-4a8c-ae77-3432f304a6e6', N'RRA.png', N'RRA.png', N'{"Sets":["RA"],"SALLevel":"Low","QuestionMode":"Questions"}', N'Rapid Assessment Control Set for the Public Safety 911 community', NULL, N'Rapid Assessment Control Set', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('dcfcd4a1-5515-48fd-9789-36fb36d46806', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R4_App_J"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard from section Appendix J of SP800-53 Revision 4 includes controls customizable for organization-wide risk management.', NULL, N'NIST SP 800-53 Revision 4 Appendix J', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('ca12d2be-11bb-40d6-bd4f-3def3db34f11', N'cis-v8.png', N'cis-v8.png', N'{"Sets":["CSC_V8_IG2"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The CIS Controls are a prioritized set of safeguards to mitigate the most prevalent cyber-attacks against systems and networks.', NULL, N'CIS Controls Version 8 IG-2', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('c67b4152-4083-48e7-9f8c-3f4baeb8e503', N'cag.jpeg', N'cag.jpeg', N'{"Sets":["Cag"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard contains 20 crucial controls designed to establish a prioritized baseline of information security measures.', NULL, N'Consensus Audit Guidelines (CAG)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('99935f8f-8216-43ae-8a14-40f7e2420ca5', N'cis-v8.png', N'cis-v8.png', N'{"Sets":["CSC_V8_IG3"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The CIS Controls are a prioritized set of safeguards to mitigate the most prevalent cyber-attacks against systems and networks.', NULL, N'CIS Controls Version 8 IG-3', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('588b16e5-ae9a-435e-a6e3-441a7578d64a', N'cmmc.jpeg', N'cmmc.jpeg', N'{"Model":{"ModelName":"CMMC", "Level":1}}', N'The Cybersecurity Maturity Model Certification (CMMC) 1.0 measures cybersecurity maturity with five levels.', NULL, N'Cybersecurity Maturity Model Certification 1.02', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('a3b6d634-b149-41cf-a16f-4bb19db5e6c0', N'wind-cert.png', N'wind-cert.png', N'{"Sets":["Wind_CERT"], "QuestionMode": "Requirements"}', N'Guidelines and best practices tailored for Utility Scale Wind plants.', NULL, N'Wind Cybersecurity Evaluation Risk Tool (Wind-CERT)', 0, '2023-02-13 14:28:25.120')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('2962cbbd-740a-4600-9262-4c3cf80eaa5a', N'VADR.png', N'VADR.png', N'{"Sets":["TSA2018"],"SALLevel":"Low","QuestionMode":"Questions","Model":{"ModelName":"VADR"}}', N'The VADR maturity model enables participants to perform assessments virtually.', NULL, N'TSA Validated Architecture Design Reviews (VADR)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('7ba9f3e0-825f-481a-af3b-50b12638eec5', N'cis-v8.png', N'cis-v8.png', N'{"Sets":["CSC_V8"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The CIS Controls are a prioritized set of safeguards to mitigate the most prevalent cyber-attacks against systems and networks.', NULL, N'CIS Controls Version 8', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('4ee4c330-5a4c-42f0-8584-5188edda4e95', N'faa-maintenance.png', N'faa-maintenance.png', N'{"Sets":["FAA_MAINT"],"SALLevel":"Low","QuestionMode":"Questions"}', N'These questions are targeted at aircraft maintenance activities.', NULL, N'FAA - Portable Electronic Devices Used in Aviation – Maintenance', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('9ad60648-45c4-49a6-aff4-53230008e816', N'Cfats.png', N'Cfats.png', N'{"Sets":["Cfats"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The document presents the risk-based performance standards (RBPSs) for the security of the Nation''s chemical facilities.', NULL, N'CFATS Risk-Based Performance Standards Guide 8-Cyber', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('6580c6bb-d01f-4c05-97fa-53566d35e385', N'CIS.png', N'CIS.png', N'{"Model":{"ModelName":"CIS"}}', N'The CIS goal is to assess the foundational and essential cybersecurity practices of an organization''s critical service.', NULL, N'CISA Cyber Infrastructure Survey (CIS)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('53699862-9ce4-415f-95d8-56246f69d4d1', N'control-systems.png', N'control-systems.png', N'{"Sets":["ISA_62443_4_1"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This document prescribes activities required to perform security risk assessments on a new or existing IACS.', NULL, N'(62443) American National Standard ISA-62443-4-1-2018 Security for Industrial Automation and Control Systems', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('317a8213-7656-4d51-9031-6dd3b6d08135', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["CSC_V6"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The CIS Controls are especially relevant because they are updated by cyber experts based on actual attack data.', NULL, N'CIS Controls Version 6', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('ab9f36f9-b3c2-4c6c-ba60-6e82501d0b3c', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R4_71"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides a catalog of security and privacy controls for federal information systems and organizations.', NULL, N'NIST SP 800-53 Revision 4', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('2ebb851a-9a93-455e-9c12-6f0ee6ea6673', N'default.jpeg', N'default.jpeg', N'{"Sets":[]}', N'Temp holder for orphan assessments', NULL, N'Tmp Holder', 0, '2023-06-21 13:14:42.187')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('b9dca07b-887d-4aaa-aba6-806172581636', N'isa.jpeg', N'isa.jpeg', N'{"Sets":["ISA-62443"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This document prescribes the activities required to perform security risk assessments on a new or existing IACS.', NULL, N'(62443) American National Standard ISA-62443-4-1-2018 Security for Industrial Automation and Control Systems', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('3fe5f3fb-8a6b-48fd-9bcf-815eccae94cd', N'nist-sp-800-161.png', N'nist-sp-800-161.png', N'{"Sets":["C800_161"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This publication provides guidance to federal agencies on identifying, assessing, and mitigating ICT supply chain risks.', NULL, N'NIST SP 800-161 Supply Chain Risk Management', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('6ef7d8e3-cf6e-4a25-9f16-83b3ac569a53', N'csf.png', N'csf.png', N'{"Sets":["NCSF_V1"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This approach is a voluntary risk-based Cybersecurity Framework using a common language to address cybersecurity risk.', NULL, N'NIST CSF: Framework for Improving Critical Infrastructure Cybersecurity v1.1', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('b1e9b990-7388-4d07-8113-8707a9ec729b', N'nerc-cip.png', N'nerc-cip.png', N'{"Sets":["Nerc_Cip_R4"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This NERC-CIP standard was developed to assist industry stakeholders with bulk electric power systems in North America.', NULL, N'NERC CIP-002 through CIP-009 Revision 4', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('b1abc503-08db-4110-b45b-8874ea090527', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R3_App_I_old"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government.', NULL, N'NIST SP 800-53 Revision 3 Appendix I', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('16a06476-1c35-42be-acbf-898e8e7e94ed', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R3_old"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government.', NULL, N'NIST Special Publication 800-53 Revision 3', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('8046f780-a288-45dd-9c77-92c20e3ae324', N'rail-transit.png', N'rail-transit.png', N'{"Sets":["APTA_Rail_V1"],"SALLevel":"Low","QuestionMode":"Questions"}', N'Securing Control and Communications Systems in Rail Transit Environments', NULL, N'Defining a Security Zone Architecture for Rail Transit and Protecting Critical Zones', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('17ddca62-8e52-4f5c-8071-939349cea116', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R3"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government.', NULL, N'NIST SP 800-53 Revision 3', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('a013ce92-ffeb-4526-b5bc-93c6d74d9ce4', N'scert.png', N'scert.png', N'{"Sets":["Solar_CERT"], "QuestionMode": "Requirements"}', N'Guidelines and best practices tailored for Utility Scale Photovoltaic Energy Systems.', NULL, N'Solar Cybersecurity Evaluation Risk Tool (SCERT)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('1788b0d3-59c0-4b9d-aa0e-9f285876a16e', N'VADR.png', N'VADR.png', N'{"Model":{"ModelName":"VADR"}}', N'The basic VADR maturity model enables participants to perform assessments virtually.', NULL, N'Basic TSA Validated Architecture Design Reviews (VADR)', 0, '2023-01-26 12:22:20.143')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('3a17f36a-ec9c-4795-9c3f-9ff78c713466', N'AWWA.png', N'AWWA.png', N'{"Sets":["AWWA"],"SALLevel":"Low","QuestionMode":"Questions"}', N'American Water Works Association (AWWA) tool questions in conjunction with additional questions from CSET.', NULL, N'American Water Works Association', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('6a463c71-fe29-4189-bd7d-a0b1712b582c', N'cmmc.jpeg', N'cmmc.jpeg', N'{"Model":{"ModelName":"CMMC2", "Level": 1}}', N'The new Cybersecurity Maturity Model Certification (CMMC) 2.0 streamlines the number of levels from 5 to 3.', NULL, N'Draft CMMC 2.0 w/SPRS Scorecard', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('58ae1682-53b0-44d3-af02-a8bbc75af802', N'FAA.png', N'FAA.png', N'{"Sets":["FAA"],"SALLevel":"Low","QuestionMode":"Questions"}', N'A catalog of recommendations for securing portable electronic devices for commercial airline carriers', NULL, N'FAA - Portable Electronic Devices Used in Aviation – Operations', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('2f58295a-07f7-4a60-9a7b-b6c7f5b3c6c5', N'EDM.png', N'EDM.png', N'{"Model":{"ModelName":"EDM"}}', N'The External Dependencies Management (EDM) Assessment evaluates an organization''s management of external dependencies. This assessment focuses on the relationship between an organization''s high-value services and assets—such as people, technology, facilities, and information—and evaluates how the organization manages risks derived from its use of the Information and Communications Technology (ICT) Supply Chain in the deliverance of services.', NULL, N'CISA External Dependencies Management (EDM)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('7d7bbb7b-14b5-4d20-8735-c667a9c99da7', N'RRA.png', N'RRA.png', N'{"Model":{"ModelName":"RRA"}}', N'<p>Ransomware poses an increasing threat and continues to rise as a top cyber threat impacting both businesses and government agencies. Ransomware is a type of malicious attack where attackers encrypt an organization''s data and demand payment to restore access. In some instances, attackers may also steal an organization''s information and demand an additional payment in return for not disclosing the information to authorities, competitors, or the public. Ransomware disrupts or halts an organization''s operations and poses a dilemma for management: pay the ransom and hope that the attackers keep their word about restoring access and not disclosing data, or do not pay the ransom and restore operations themselves. The methods used to  access to an organization''s information and systems are common to cyberattacks more broadly, but they are aimed at forcing a ransom to be paid. Ransomware attacks target the organization''s data.</p><p> To understand your cybersecurity posture and assess how well your organization is equipped to defend and recover from a ransomware incident, take the Ransomware Readiness Assessment (RRA).</p>', NULL, N'CISA Ransomware Readiness Assessment (RRA)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('a802be1c-7f3d-42f1-8e15-c739695b5532', N'imr.png', N'imr.png', N'{"Model":{"ModelName":"IMR"}}', N'<p>The IMR is based on the principle that a resilient incident management function can improve an
organization''s overall cyber resilience. The IMR consists of a series of questions, the answers to which
provide insights into how an organization can improve its ability to identify, analyze, and respond to incidents
in a repeatable manner.</p><p>The IMR helps an organization understand and qualitatively measure its incident handling and
response capability and the cybersecurity practices that support it.</p>', NULL, N'CISA Incident Management Review (IMR)', 0, '2023-06-20 13:11:41.343')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('5bd71393-883f-4546-8caa-c7535de9b167', N'cag.jpeg', N'cag.jpeg', N'{"Sets":["CCI_V2"],"SALLevel":"Low","QuestionMode":"Questions"}', N'A CCI is a decomposition of an IA Control or an IA industry best practice into single, actionable statements.', NULL, N'Control Correlation Identifier Specification V2 Release 0.1', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('c3d96f53-22ae-4b70-8b59-cb200904c069', N'pci.png', N'pci.png', N'{"Model":{"ModelName":"CRE+"}}', N'The description will go here', NULL, N'Cyber Resilience Essentials (CRE+)', 0, '2025-05-07 16:16:09.650')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('d002d9c0-949d-4446-a8e4-cb8fc1679944', N'nist-sp-800-82.png', N'nist-sp-800-82.png', N'{"Sets":["C800_82_V1"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides guidance for establishing secure industrial control systems (ICS).', NULL, N'NIST SP 800-82 Revision 1', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('fda63fec-80b9-4c97-8e07-ccd2f1dc58a6', N'mvra.png', N'mvra.png', N'{"Model":{"ModelName":"MVRA"}}', N'MVRA assesses the critical service or services essential to the success of an organization''s mission.', NULL, N'CISA Minimum Viable Resilience Assessment (MVRA) - DRAFT', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('4929452f-a737-4afc-9778-ce8d550df305', N'faa-maintenance.png', N'faa-maintenance.png', N'{"Sets":["FAA_PED_V2"],"SALLevel":"Low","QuestionMode":"Questions"}', N'A security check up and cybersecurity recommendations for securing portable electronic devices for commercial airline carriers.', NULL, N'FAA - Portable Electronic Devices Used in Aviation – Operations 2021', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('33ee6e8e-f317-45c2-9a09-cff50226ca8d', N'CRR.png', N'CRR.png', N'{"Model":{"ModelName":"CRR"}}', N'The CRR is a no-cost, voluntary, non-technical assessment to evaluate an organization''s operational resilience and cybersecurity practices. The CRR may be conducted as a self-assessment or as a facilitated assessment. The CRR assesses enterprise programs and practices across a range of ten domains including risk management, incident management, service continuity, and others. The assessment is designed to measure existing organizational resilience as well as provide a gap analysis for improvement based on recognized best practices.', NULL, N'CISA Cyber Resilience Review (CRR)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('6d705a92-5d8e-4865-aaea-d090570485c1', N'cor-7.jpeg', N'cor-7.jpeg', N'{"Sets":["Cor_7"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This catalog presents a compilation of practices that various industry bodies have recommended to increase the security of control systems.', NULL, N'Catalog of Recommendations Revision 7', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('37e3c5ae-ff95-4dd7-a1da-d25c814abd74', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R3_App_I"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government.', NULL, N'NIST SP 800-53 Revision 3 Appendix I', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('7e650e05-b3c2-4b55-8830-d335ca41eeef', N'tsa-pipeline-april-2011.png', N'tsa-pipeline-april-2011.png', N'{"Sets":["Tsa"],"SALLevel":"Low","QuestionMode":"Questions"}', N'These guidelines are applicable to natural gas and hazardous liquid transmission pipelines and liquefied natural gas facility operators.', NULL, N'TSA Pipeline Security Guidelines April 2011', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('8f3f4431-3482-44c0-92c2-dccbb14dd8aa', N'tsa-pipeline.png', N'tsa-pipeline.png', N'{"Sets":["TSA2018"],"SALLevel":"Low","QuestionMode":"Questions"}', N'These guidelines are applicable to operational natural gas and hazardous liquid transmission pipeline systems.', NULL, N'TSA Pipeline Security Guidelines March 2018 with April 2021 revision', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('5e48de28-156e-47df-9380-e72b482509e2', N'nist-sp-800-171.png', N'nist-sp-800-171.png', N'{"Sets":["C800_171"],"SALLevel":"Low","QuestionMode":"Requirements"}', N'This publication provides agencies with recommended security requirements for protecting the confidentiality of Controlled Unclassified Information (CUI).', NULL, N'NIST SP 800-171 Revision 2: Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('f7cf9b71-d8ef-4fd5-934f-ec94a0666b3c', N'nist-sp-800-53.png', N'nist-sp-800-53.png', N'{"Sets":["C800_53_R4"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides a catalog of security and privacy controls for federal information systems and organizations.', NULL, N'NIST Special Publication 800-53 Revision 4 (old)', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('2f798ad3-24ef-4329-9032-ef65faf0579a', N'nist-sp-800-82.png', N'nist-sp-800-82.png', N'{"Sets":["C800_82"],"SALLevel":"Low","QuestionMode":"Questions"}', N'This standard provides guidance for establishing secure industrial control systems (ICS).', NULL, N'NIST SP 800-82', 0, '2022-09-20 15:26:46.847')
INSERT INTO [dbo].[GALLERY_ITEM] ([Gallery_Item_Guid], [Icon_File_Name_Small], [Icon_File_Name_Large], [Configuration_Setup], [Description], [Configuration_Setup_Client], [Title], [Is_Visible], [CreationDate]) VALUES ('f1fe7bf3-ceb3-4b76-a684-f429abb8f1ae', N'INGAA.png', N'INGAA.png', N'{"Sets":["INGAA"],"SALLevel":"Low","QuestionMode":"Questions"}', N'The purpose of this document is to provide guidance on addressing the control system cyber security plans section of the natural gas pipeline operators TSA required CSP.', NULL, N'INGAA Control Systems Cyber Security Guidelines for the Natural Gas Pipeline Industry', 0, '2022-09-20 15:26:46.847')
PRINT(N'Operation applied to 61 rows out of 61')
COMMIT TRANSACTION
GO
