//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSESSMENTS_REQUIRED_DOCUMENTATION
    {
        public int Assessment_Id { get; set; }
        public int Documentation_Id { get; set; }
        public string Answer { get; set; }
    
        public virtual ASSESSMENT ASSESSMENT { get; set; }
        public virtual REQUIRED_DOCUMENTATION REQUIRED_DOCUMENTATION { get; set; }
    }
}
