//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMOGRAPHIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEMOGRAPHIC()
        {
            this.DOCUMENT_FILE = new HashSet<DOCUMENT_FILE>();
        }
    
        public int Assessment_Id { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public string Size { get; set; }
        public string AssetValue { get; set; }
        public bool NeedsPrivacy { get; set; }
        public bool NeedsSupplyChain { get; set; }
        public bool NeedsICS { get; set; }
    
        public virtual ASSESSMENT ASSESSMENT { get; set; }
        public virtual SECTOR SECTOR { get; set; }
        public virtual DEMOGRAPHICS_ASSET_VALUES DEMOGRAPHICS_ASSET_VALUES { get; set; }
        public virtual DEMOGRAPHICS_SIZE DEMOGRAPHICS_SIZE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENT_FILE> DOCUMENT_FILE { get; set; }
    }
}


