//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAL_HOURS_COMPONENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FINANCIAL_HOURS_COMPONENT()
        {
            this.FINANCIAL_HOURS = new HashSet<FINANCIAL_HOURS>();
        }
    
        public string Component { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> PresentationOrder { get; set; }
    
        public virtual FINANCIAL_DOMAINS FINANCIAL_DOMAINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINANCIAL_HOURS> FINANCIAL_HOURS { get; set; }
    }
}
