//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAL_QUESTIONS
    {
        public int StmtNumber { get; set; }
        public int Question_Id { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual FINANCIAL_DETAILS FINANCIAL_DETAILS { get; set; }
        public virtual NEW_QUESTION NEW_QUESTION { get; set; }
    }
}
