//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINDING_CONTACT
    {
        public int Finding_Id { get; set; }
        public Nullable<int> IgnoreThis { get; set; }
        public int Assessment_Contact_Id { get; set; }
        public Nullable<System.Guid> Id { get; set; }
    
        public virtual FINDING FINDING { get; set; }
        public virtual ASSESSMENT_CONTACTS ASSESSMENT_CONTACTS { get; set; }
        public virtual USER_DETAIL_INFORMATION USER_DETAIL_INFORMATION { get; set; }
    }
}


