//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRAMEWORK_TIER_DEFINITIONS
    {
        public string Tier { get; set; }
        public string TierType { get; set; }
        public string TierQuestion { get; set; }
    
        public virtual FRAMEWORK_TIERS FRAMEWORK_TIERS { get; set; }
    }
}


