//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAVIGATION_STATE
    {
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsError { get; set; }
        public bool IsVisited { get; set; }
        public bool IsAvailable { get; set; }
        public double PercentCompletion { get; set; }
    }
}


