//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCSF_FUNCTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NCSF_FUNCTIONS()
        {
            this.NCSF_CATEGORY = new HashSet<NCSF_CATEGORY>();
        }
    
        public string NCSF_Function_ID { get; set; }
        public string NCSF_Function_Name { get; set; }
        public Nullable<int> NCSF_Function_Order { get; set; }
        public int NCSF_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NCSF_CATEGORY> NCSF_CATEGORY { get; set; }
    }
}


