//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_QUESTION_LEVELS
    {
        public string Universal_Sal_Level { get; set; }
        public int New_Question_Set_Id { get; set; }
    
        public virtual UNIVERSAL_SAL_LEVEL UNIVERSAL_SAL_LEVEL1 { get; set; }
        public virtual NEW_QUESTION_SETS NEW_QUESTION_SETS { get; set; }
    }
}


