//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_GROUP_HEADING
    {
        public string Question_Group_Heading1 { get; set; }
        public string Std_Ref { get; set; }
        public int Universal_Weight { get; set; }
        public int Question_Group_Heading_Id { get; set; }
    }
}


