//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_GROUP_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTION_GROUP_TYPE()
        {
            this.NEW_QUESTION = new HashSet<NEW_QUESTION>();
        }
    
        public int Question_Group_Id { get; set; }
        public string Group_Name { get; set; }
        public string Scoring_Group { get; set; }
        public string Scoring_Type { get; set; }
        public string Group_Header { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEW_QUESTION> NEW_QUESTION { get; set; }
    }
}


