//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_STANDARDS_SELECTION
    {
        public int Assesment_Id { get; set; }
        public string Report_Set_Entity_Name { get; set; }
        public int Report_Section_Order { get; set; }
        public bool Is_Selected { get; set; }
    
        public virtual ASSESSMENT ASSESSMENT { get; set; }
        public virtual SET SET { get; set; }
    }
}


