//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUIREMENT_SOURCE_FILES
    {
        public int Requirement_Id { get; set; }
        public int Gen_File_Id { get; set; }
        public string Section_Ref { get; set; }
        public Nullable<int> Page_Number { get; set; }
        public string Destination_String { get; set; }
    
        public virtual GEN_FILE GEN_FILE { get; set; }
        public virtual NEW_REQUIREMENT NEW_REQUIREMENT { get; set; }
    }
}


