//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUIREMENT_LEVELS
    {
        public int Requirement_Id { get; set; }
        public string Standard_Level { get; set; }
        public string Level_Type { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual REQUIREMENT_LEVEL_TYPE REQUIREMENT_LEVEL_TYPE { get; set; }
        public virtual STANDARD_SPECIFIC_LEVEL STANDARD_SPECIFIC_LEVEL { get; set; }
        public virtual NEW_REQUIREMENT NEW_REQUIREMENT { get; set; }
    }
}


