//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIVERSAL_SUB_CATEGORY_HEADINGS
    {
        public string Sub_Heading_Question_Description { get; set; }
        public Nullable<bool> Display_Radio_Buttons { get; set; }
        public int Question_Group_Heading_Id { get; set; }
        public int Universal_Sub_Category_Id { get; set; }
        public int Heading_Pair_Id { get; set; }
        public string Set_Name { get; set; }
    
        public virtual SET SETS { get; set; }
    }
}
