//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.ASSESSMENT_CONTACTS = new HashSet<ASSESSMENT_CONTACTS>();
            this.ASSESSMENTS = new HashSet<ASSESSMENTS>();
        }
    
        public string PrimaryEmail { get; set; }
        public int UserId { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public bool IsSuperUser { get; set; }
        public bool PasswordResetRequired { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSESSMENT_CONTACTS> ASSESSMENT_CONTACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSESSMENTS> ASSESSMENTS { get; set; }
        public virtual USER_DETAIL_INFORMATION USER_DETAIL_INFORMATION { get; set; }
        public virtual USER_SECURITY_QUESTIONS USER_SECURITY_QUESTIONS { get; set; }
    }
}
