// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Org.BouncyCastle.Bcpg.OpenPgp;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_GetQuestionsResult
    {
        public string CategoryAndNumber { get; set; }
        public string ShortName { get; set; }
        public string Category { get; set; }
        public string QuestionText { get; set; }

          /// <summary>
          /// The ID of the related question.  Null if this is a requirement.
          /// </summary>
          public Nullable<int> QuestionId { get; set; }

          /// <summary>
          /// The ID of the related requirement.  Null if this is a question.
          /// </summary>
          public Nullable<int> RequirementId { get; set; }

          /// <summary>
          /// The question or requirement that the answer is tied to
          /// </summary>
          public int QuestionOrRequirementID { get; set; }
          public int AnswerID { get; set; }

          public string AnswerText { get; set; }
          public string Level { get; set; }
          public string QuestionRef { get; set; }
    }
}
