---
services:
  postgresql:
    container_name: cset-postgres
    hostname: postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: csetweb
      POSTGRES_USER: cset
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - cset-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  sqlserver:
    container_name: cset-mssql
    hostname: mssql
    image: "mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1433:1433"
    networks:
      - cset-network
    volumes:
      - mssql_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
      - ./DatabaseScripts:/var/opt/mssql/scripts

networks:
  cset-network:
    driver: bridge

volumes:
  postgres-data:
  mssql_data:
