//////////////////////////////// 
// 
//   Copyright 2018 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchIndex2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG_RECOMMENDATIONS_DATA
    {
        public int Data_Id { get; set; }
        public Nullable<int> Req_Oracle_Id { get; set; }
        public Nullable<int> Parent_Heading_Id { get; set; }
        public string Heading { get; set; }
        public string Heading_Html { get; set; }
        public string Section_Long_Number { get; set; }
        public string Section_Short_Number { get; set; }
        public string Topic_Name { get; set; }
        public string Section_Short_Name { get; set; }
        public string Requirement_Text { get; set; }
        public string Supplemental_Guidance { get; set; }
        public string Supplemental_Guidance_Html { get; set; }
        public string Requirement { get; set; }
        public string Requirement_Html { get; set; }
        public string Enhancement { get; set; }
        public string Enhancement_Html { get; set; }
        public string Flow_Document { get; set; }
    
        public virtual CATALOG_RECOMMENDATIONS_HEADINGS CATALOG_RECOMMENDATIONS_HEADINGS { get; set; }
    }
}


