// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SearchIndex2
{
    /// <summary>
    /// A collection of CATALOG_RECOMMENDATIONS_HEADINGS records
    /// </summary>
    public partial class CATALOG_RECOMMENDATIONS_HEADINGS
    {
        public CATALOG_RECOMMENDATIONS_HEADINGS()
        {
            CATALOG_RECOMMENDATIONS_DATAs = new HashSet<CATALOG_RECOMMENDATIONS_DATA>();
        }

        /// <summary>
        /// The Id is used to
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// The Heading Num is used to
        /// </summary>
        public int Heading_Num { get; set; }
        /// <summary>
        /// The Heading Name is used to
        /// </summary>
        public string Heading_Name { get; set; }

        public virtual ICollection<CATALOG_RECOMMENDATIONS_DATA> CATALOG_RECOMMENDATIONS_DATAs { get; set; }
    }
}