// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SearchIndex2
{
    /// <summary>
    /// A collection of GEN_FILE records
    /// </summary>
    public partial class GEN_FILE
    {
        public GEN_FILE()
        {
            FILE_KEYWORDs = new HashSet<FILE_KEYWORDS>();
        }

        /// <summary>
        /// The Gen File Id is used to
        /// </summary>
        public int Gen_File_Id { get; set; }
        /// <summary>
        /// The File Type Id is used to
        /// </summary>
        public decimal? File_Type_Id { get; set; }
        /// <summary>
        /// The File Name is used to
        /// </summary>
        public string File_Name { get; set; }
        /// <summary>
        /// The Title is used to
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// The Name is used to
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// The File Size is used to
        /// </summary>
        public double? File_Size { get; set; }
        /// <summary>
        /// The Doc Num is used to
        /// </summary>
        public string Doc_Num { get; set; }
        /// <summary>
        /// The Comments is used to
        /// </summary>
        public string Comments { get; set; }
        /// <summary>
        /// The Description is used to
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// The Short Name is used to
        /// </summary>
        public string Short_Name { get; set; }
        /// <summary>
        /// The Publish Date is used to
        /// </summary>
        public DateTime? Publish_Date { get; set; }
        /// <summary>
        /// The Doc Version is used to
        /// </summary>
        public string Doc_Version { get; set; }
        /// <summary>
        /// The Summary is used to
        /// </summary>
        public string Summary { get; set; }
        /// <summary>
        /// The Source Type is used to
        /// </summary>
        public string Source_Type { get; set; }
        public byte[] Data { get; set; }
        public bool? Is_Uploaded { get; set; }

        public virtual FILE_REF_KEYS Doc_NumNavigation { get; set; }
        public virtual ICollection<FILE_KEYWORDS> FILE_KEYWORDs { get; set; }
    }
}