//////////////////////////////// 
// 
//   Copyright 2024 Battelle Energy Alliance, LLC  
// 
// 
//////////////////////////////// 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace CSETWebCore.Business.AssessmentIO.Models.AutoGenerated
{
//automatically generated
    public class jACCESS_KEY
    {
        [Required]
        public String AccessKey { get; set; }
        [Required]
        public DateTime GeneratedDate { get; set; }
        [Required]
        public Boolean PreventEncrypt { get; set; }
        [Required]
        public Boolean CisaAssessorWorkflow { get; set; }
        [Required]
        public String Lang { get; set; }
    }

    public class jACCESS_KEY_ASSESSMENT
    {
        [Required]

        public String AccessKey { get; set; }
        [Required]

        public Int32 Assessment_Id { get; set; }
    }

    public class jADDRESS
    {
        public String PrimaryEmail { get; set; }
        [Required]

        public String AddressType { get; set; }
        [Required]

        public Guid Id { get; set; }
        public String City { get; set; }
        public String Country { get; set; }
        public String Line1 { get; set; }
        public String Line2 { get; set; }
        public String State { get; set; }
        public String Zip { get; set; }
    }

    public class jAGGREGATION_ASSESSMENT
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Aggregation_Id { get; set; }
        public Int32? Sequence { get; set; }
        public String Alias { get; set; }
    }

    public class jANSWER
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Answer_Id { get; set; }
        [Required]

        public Int32 Question_Or_Requirement_Id { get; set; }
        public Boolean? Mark_For_Review { get; set; }
        public String Comment { get; set; }
        public String Alternate_Justification { get; set; }
        public Int32? Question_Number { get; set; }
        [Required]

        public String Answer_Text { get; set; }
        [Required]

        public Guid Component_Guid { get; set; }
        public String Custom_Question_Guid { get; set; }
        public Int32? Old_Answer_Id { get; set; }
        [Required]

        public Boolean Reviewed { get; set; }
        public String FeedBack { get; set; }
        [Required]

        public String Question_Type { get; set; }
        public Boolean? Is_Requirement { get; set; }
        public Boolean? Is_Component { get; set; }
        public Boolean? Is_Framework { get; set; }
        public Boolean? Is_Maturity { get; set; }
        public String Free_Response_Answer { get; set; }
        public Int32? Mat_Option_Id { get; set; }
    }

    public class jANSWER_PROFILE
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Profile_Id { get; set; }
        public String ProfileName { get; set; }
        [Required]

        public DateTime Profile_Date { get; set; }
    }

    public class jASSESSMENT_CONTACTS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        public String PrimaryEmail { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        [Required]

        public Boolean Invited { get; set; }
        [Required]

        public Int32 AssessmentRoleId { get; set; }
        public Int32? UserId { get; set; }
        [Required]

        public Int32 Assessment_Contact_Id { get; set; }
        public String Title { get; set; }
        public String Phone { get; set; }
        [Required]

        public Boolean Is_Primary_POC { get; set; }
        public String Site_Name { get; set; }
        public String Organization_Name { get; set; }
        public String Cell_Phone { get; set; }
        public String Reports_To { get; set; }
        public String Emergency_Communications_Protocol { get; set; }
        [Required]

        public Boolean Is_Site_Participant { get; set; }
    }

    public class jASSESSMENT_DIAGRAM_COMPONENTS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Guid Component_Guid { get; set; }
        [Required]

        public Int32 Component_Symbol_Id { get; set; }
        public String label { get; set; }
        public String DrawIO_id { get; set; }
        public Int32? Zone_Id { get; set; }
        public Int32? Layer_Id { get; set; }
        public String Parent_DrawIO_Id { get; set; }
    }

    public class jASSESSMENT_IRP
    {
        [Required]

        public Int32 Answer_Id { get; set; }
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 IRP_Id { get; set; }
        public Int32? Response { get; set; }
        public String Comment { get; set; }
    }

    public class jASSESSMENT_IRP_HEADER
    {
        public Int32? HEADER_RISK_LEVEL_ID { get; set; }
        [Required]

        public Int32 ASSESSMENT_ID { get; set; }
        [Required]

        public Int32 IRP_HEADER_ID { get; set; }
        public Int32? RISK_LEVEL { get; set; }
        public String COMMENT { get; set; }
    }

    public class jASSESSMENT_SELECTED_LEVELS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Level_Name { get; set; }
        [Required]

        public String Standard_Specific_Sal_Level { get; set; }
    }

    public class jASSESSMENTS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public DateTime AssessmentCreatedDate { get; set; }
        public Int32? AssessmentCreatorId { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public String Alias { get; set; }
        [Required]

        public Guid Assessment_GUID { get; set; }
        [Required]

        public DateTime Assessment_Date { get; set; }
        public String CreditUnionName { get; set; }
        public String Charter { get; set; }
        public String Assets { get; set; }
        public Int32? IRPTotalOverride { get; set; }
        public String IRPTotalOverrideReason { get; set; }
        [Required]

        public Boolean MatDetail_targetBandOnly { get; set; }
        public String Diagram_Markup { get; set; }
        [Required]

        public Int32 LastUsedComponentNumber { get; set; }
        public String Diagram_Image { get; set; }
        [Required]

        public Boolean AnalyzeDiagram { get; set; }
        [Required]

        public Boolean UseDiagram { get; set; }
        [Required]

        public Boolean UseStandard { get; set; }
        [Required]

        public Boolean UseMaturity { get; set; }
        public DateTime? AssessmentEffectiveDate { get; set; }
        public Guid? GalleryItemGuid { get; set; }
        public Boolean? ISE_StateLed { get; set; }
        [Required]

        public Boolean Is_PCII { get; set; }
        public String PCII_Number { get; set; }
        [Required]

        public Boolean ModifiedSinceLastExport { get; set; }
    }

    public class jASSESSMENTS_REQUIRED_DOCUMENTATION
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Documentation_Id { get; set; }
        [Required]

        public String Answer { get; set; }
        public String Comment { get; set; }
    }

    public class jAVAILABLE_MATURITY_MODELS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Boolean Selected { get; set; }
        [Required]

        public Int32 model_id { get; set; }
    }

    public class jAVAILABLE_STANDARDS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Set_Name { get; set; }
        [Required]

        public Boolean Selected { get; set; }
        public String Suppress_Mode { get; set; }
    }

    public class jCIS_CSI_ORGANIZATION_DEMOGRAPHICS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Boolean Motivation_CRR { get; set; }
        public String Motivation_CRR_Description { get; set; }
        [Required]

        public Boolean Motivation_RRAP { get; set; }
        public String Motivation_RRAP_Description { get; set; }
        [Required]

        public Boolean Motivation_Organization_Request { get; set; }
        public String Motivation_Organization_Request_Description { get; set; }
        [Required]

        public Boolean Motivation_Law_Enforcement_Request { get; set; }
        public String Motivation_Law_Enforcement_Description { get; set; }
        [Required]

        public Boolean Motivation_Direct_Threats { get; set; }
        public String Motivation_Direct_Threats_Description { get; set; }
        [Required]

        public Boolean Motivation_Special_Event { get; set; }
        public String Motivation_Special_Event_Description { get; set; }
        [Required]

        public Boolean Motivation_Other { get; set; }
        public String Motivation_Other_Description { get; set; }
        public String Parent_Organization { get; set; }
        public String Organization_Name { get; set; }
        public String Site_Name { get; set; }
        public String Street_Address { get; set; }
        public DateTime? Visit_Date { get; set; }
        [Required]

        public Boolean Completed_For_SLTT { get; set; }
        [Required]

        public Boolean Completed_For_Federal { get; set; }
        [Required]

        public Boolean Completed_For_National_Special_Event { get; set; }
        public String CIKR_Sector { get; set; }
        public String Sub_Sector { get; set; }
        public String IT_ICS_Staff_Count { get; set; }
        public String Cybersecurity_IT_ICS_Staff_Count { get; set; }
    }

    public class jCIS_CSI_SERVICE_COMPOSITION
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        public String Networks_Description { get; set; }
        public String Services_Description { get; set; }
        public String Applications_Description { get; set; }
        public String Connections_Description { get; set; }
        public String Personnel_Description { get; set; }
        public String Other_Defining_System_Description { get; set; }
        public Int32? Primary_Defining_System { get; set; }
    }

    public class jCIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Defining_System_Id { get; set; }
    }

    public class jCIS_CSI_SERVICE_DEMOGRAPHICS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        public String Critical_Service_Name { get; set; }
        public String Critical_Service_Description { get; set; }
        public String IT_ICS_Name { get; set; }
        [Required]

        public Boolean Multi_Site { get; set; }
        public String Multi_Site_Description { get; set; }
        public String Budget_Basis { get; set; }
        public String Authorized_Organizational_User_Count { get; set; }
        public String Authorized_Non_Organizational_User_Count { get; set; }
        public String Customers_Count { get; set; }
        public String IT_ICS_Staff_Count { get; set; }
        public String Cybersecurity_IT_ICS_Staff_Count { get; set; }
    }

    public class jCIS_CSI_USER_COUNTS
    {
        [Required]

        public String User_Count { get; set; }
        [Required]

        public Int32 Sequence { get; set; }
    }

    public class jCNSS_CIA_JUSTIFICATIONS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String CIA_Type { get; set; }
        [Required]

        public String DropDownValueLevel { get; set; }
        [Required]

        public String Justification { get; set; }
    }

    public class jCOUNTY_ANSWERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String County_FIPS { get; set; }
    }

    public class jCSAF_FILE
    {
        [Required]

        public String File_Name { get; set; }
        public Byte[] Data { get; set; }
        public Double File_Size { get; set; }
        public DateTime? Upload_Date { get; set; }
    }

    public class jCSET_VERSION
    {
        [Required]

        public Int32 Id { get; set; }
        [Required]

        public Decimal Version_Id { get; set; }
        [Required]

        public String Cset_Version1 { get; set; }
        public String Build_Number { get; set; }
    }

    public class jCUSTOM_BASE_STANDARDS
    {
        [Required]

        public String Custom_Questionaire_Name { get; set; }
        [Required]

        public String Base_Standard { get; set; }
    }

    public class jCUSTOM_QUESTIONAIRE_QUESTIONS
    {
        [Required]

        public String Custom_Questionaire_Name { get; set; }
        [Required]

        public Int32 Question_Id { get; set; }
    }

    public class jCUSTOM_QUESTIONAIRES
    {
        [Required]

        public String Custom_Questionaire_Name { get; set; }
        public String Description { get; set; }
        [Required]

        public String Set_Name { get; set; }
    }

    public class jCUSTOM_STANDARD_BASE_STANDARD
    {
        [Required]

        public String Custom_Questionaire_Name { get; set; }
        [Required]

        public String Base_Standard { get; set; }
        [Required]

        public Int32 Custom_Standard_Base_Standard_Id { get; set; }
    }

    public class jDEMOGRAPHIC_ANSWERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        public String Employees { get; set; }
        public String CustomersSupported { get; set; }
        public String GeographicScope { get; set; }
        public String CIOExists { get; set; }
        public String CISOExists { get; set; }
        public String CyberTrainingProgramExists { get; set; }
        public Int32? SectorId { get; set; }
        public Int32? SubSectorId { get; set; }
        public String CyberRiskService { get; set; }
    }

    public class jDEMOGRAPHICS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        public Int32? SectorId { get; set; }
        public Int32? IndustryId { get; set; }
        public String Size { get; set; }
        public String AssetValue { get; set; }
        [Required]

        public Boolean NeedsPrivacy { get; set; }
        [Required]

        public Boolean NeedsSupplyChain { get; set; }
        [Required]

        public Boolean NeedsICS { get; set; }
        public String OrganizationName { get; set; }
        public String Agency { get; set; }
        public Int32? OrganizationType { get; set; }
        public Int32? Facilitator { get; set; }
        public Int32? PointOfContact { get; set; }
        public Boolean? IsScoped { get; set; }
        public String CriticalService { get; set; }
    }

    public class jDETAILS_DEMOGRAPHICS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String DataItemName { get; set; }
        public String StringValue { get; set; }
        public Int32? IntValue { get; set; }
        public Double? FloatValue { get; set; }
        public Boolean? BoolValue { get; set; }
        public DateTime? DateTimeValue { get; set; }
    }

    public class jDIAGRAM_CONTAINER
    {
        [Required]

        public Int32 Container_Id { get; set; }
        [Required]

        public String ContainerType { get; set; }
        [Required]

        public String Name { get; set; }
        [Required]

        public Boolean Visible { get; set; }
        [Required]

        public String DrawIO_id { get; set; }
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Universal_Sal_Level { get; set; }
        [Required]

        public Int32 Parent_Id { get; set; }
        public String Parent_Draw_IO_Id { get; set; }
    }

    public class jDOCUMENT_ANSWERS
    {
        [Required]

        public Int32 Document_Id { get; set; }
        [Required]

        public Int32 Answer_Id { get; set; }
    }

    public class jDOCUMENT_FILE
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Document_Id { get; set; }
        public String Path { get; set; }
        public String Title { get; set; }
        public String FileMd5 { get; set; }
        public String ContentType { get; set; }
        [Required]

        public DateTime CreatedTimestamp { get; set; }
        [Required]

        public DateTime UpdatedTimestamp { get; set; }
        public String Name { get; set; }
        public Byte[] Data { get; set; }
    }

    public class jFINANCIAL_ASSESSMENT_VALUES
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String AttributeName { get; set; }
        public String AttributeValue { get; set; }
    }

    public class jFINANCIAL_DOMAIN_FILTERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 DomainId { get; set; }
        [Required]

        public Boolean B { get; set; }
        [Required]

        public Boolean E { get; set; }
        [Required]

        public Boolean Int { get; set; }
        [Required]

        public Boolean A { get; set; }
        [Required]

        public Boolean Inn { get; set; }
    }

    public class jFINANCIAL_DOMAIN_FILTERS_V2
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 DomainId { get; set; }
        [Required]

        public Int32 Financial_Level_Id { get; set; }
        [Required]

        public Boolean IsOn { get; set; }
    }

    public class jFINANCIAL_HOURS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Component { get; set; }
        [Required]

        public String ReviewType { get; set; }
        [Required]

        public Decimal Hours { get; set; }
        public String OtherSpecifyValue { get; set; }
    }

    public class jFINDING
    {
        [Required]

        public Int32 Answer_Id { get; set; }
        [Required]

        public Int32 Finding_Id { get; set; }
        public String Summary { get; set; }
        public String Issue { get; set; }
        public String Impact { get; set; }
        public String Recommendations { get; set; }
        public String Vulnerabilities { get; set; }
        public DateTime? Resolution_Date { get; set; }
        public Int32? Importance_Id { get; set; }
        public String Title { get; set; }
        public String Type { get; set; }
        public String Description { get; set; }
        public Int32? Auto_Generated { get; set; }
        public String Citations { get; set; }
        public String Risk_Area { get; set; }
        public String Sub_Risk { get; set; }
        public String ActionItems { get; set; }
        public String Supp_Guidance { get; set; }
    }

    public class jFINDING_CONTACT
    {
        [Required]

        public Int32 Finding_Id { get; set; }
        [Required]

        public Int32 Assessment_Contact_Id { get; set; }
        public Int32? IgnoreThis { get; set; }
        public Guid? Id { get; set; }
    }

    public class jFRAMEWORK_TIER_TYPE_ANSWER
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String TierType { get; set; }
        [Required]

        public String Tier { get; set; }
    }

    public class jGENERAL_SAL
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Sal_Name { get; set; }
        [Required]

        public Int32 Slider_Value { get; set; }
    }

    public class jHYDRO_DATA_ACTIONS
    {
        [Required]

        public Int32 Answer_Id { get; set; }
        [Required]

        public Int32 Progress_Id { get; set; }
        public String Comment { get; set; }
    }

    public class jINFORMATION
    {
        [Required]

        public Int32 Id { get; set; }
        [Required]

        public String Assessment_Name { get; set; }
        public String Facility_Name { get; set; }
        public String City_Or_Site_Name { get; set; }
        public String State_Province_Or_Region { get; set; }
        public String Assessor_Name { get; set; }
        public String Assessor_Email { get; set; }
        public String Assessor_Phone { get; set; }
        public String Assessment_Description { get; set; }
        public String Additional_Notes_And_Comments { get; set; }
        public String Additional_Contacts { get; set; }
        public String Executive_Summary { get; set; }
        public String Enterprise_Evaluation_Summary { get; set; }
        public String Real_Property_Unique_Id { get; set; }
        public Int32? eMass_Document_Id { get; set; }
        public Boolean? IsAcetOnly { get; set; }
        public String Workflow { get; set; }
        public Int32? Baseline_Assessment_Id { get; set; }
        public String Origin { get; set; }
        public String Postal_Code { get; set; }
        public Int32? Region_Code { get; set; }
        public Boolean? Ise_Submitted { get; set; }
        public DateTime? Submitted_Date { get; set; }
    }

    public class jISE_ACTIONS_FINDINGS
    {
        [Required]

        public Int32 Finding_Id { get; set; }
        [Required]

        public Int32 Mat_Question_Id { get; set; }
        [Required]

        public String Action_Items_Override { get; set; }
    }

    public class jMALCOLM_ANSWERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Question_Or_Requirement_Id { get; set; }
        [Required]

        public String Answer_Text { get; set; }
        [Required]

        public Int32 Malcolm_Id { get; set; }
        [Required]

        public Int32 Malcolm_Answer_Id { get; set; }
        public Int32? Mat_Option_Id { get; set; }
    }

    public class jMATURITY_DOMAIN_REMARKS
    {
        [Required]

        public Int32 Grouping_ID { get; set; }
        [Required]

        public Int32 Assessment_Id { get; set; }
        public String DomainRemarks { get; set; }
    }

    public class jMETRO_ANSWERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Metro_FIPS { get; set; }
    }

    public class jNETWORK_WARNINGS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Id { get; set; }
        public String WarningText { get; set; }
        public Int32? Rule_Violated { get; set; }
    }

    public class jNIST_SAL_INFO_TYPES
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Type_Value { get; set; }
        [Required]

        public Boolean Selected { get; set; }
        public String Confidentiality_Value { get; set; }
        public String Confidentiality_Special_Factor { get; set; }
        public String Integrity_Value { get; set; }
        public String Integrity_Special_Factor { get; set; }
        public String Availability_Value { get; set; }
        public String Availability_Special_Factor { get; set; }
        public String Area { get; set; }
        public String NIST_Number { get; set; }
    }

    public class jNIST_SAL_QUESTION_ANSWERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Question_Id { get; set; }
        [Required]

        public String Question_Answer { get; set; }
    }

    public class jPARAMETER_ASSESSMENT
    {
        [Required]

        public Int32 Parameter_ID { get; set; }
        [Required]

        public Int32 Assessment_ID { get; set; }
        public String Parameter_Value_Assessment { get; set; }
    }

    public class jPARAMETER_VALUES
    {
        [Required]

        public Int32 Answer_Id { get; set; }
        [Required]

        public Int32 Parameter_Id { get; set; }
        public String Parameter_Value { get; set; }
        [Required]

        public Boolean Parameter_Is_Default { get; set; }
    }

    public class jREGION_ANSWERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String State { get; set; }
        [Required]

        public String RegionCode { get; set; }
    }

    public class jREPORT_DETAIL_SECTION_SELECTION
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Report_Section_Id { get; set; }
        [Required]

        public Int32 Report_Section_Order { get; set; }
        [Required]

        public Boolean Is_Selected { get; set; }
    }

    public class jREPORT_OPTIONS_SELECTION
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Report_Option_Id { get; set; }
        [Required]

        public Boolean Is_Selected { get; set; }
    }

    public class jSTANDARD_SELECTION
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public String Application_Mode { get; set; }
        [Required]

        public String Selected_Sal_Level { get; set; }
        public String Last_Sal_Determination_Type { get; set; }
        public String Sort_Set_Name { get; set; }
        [Required]

        public Boolean Is_Advanced { get; set; }
        [Required]

        public Boolean Only_Mode { get; set; }
        public String Hidden_Screens { get; set; }
    }

    public class jSUB_CATEGORY_ANSWERS
    {
        [Required]

        public Int32 Assessment_Id { get; set; }
        [Required]

        public Int32 Heading_Pair_Id { get; set; }
        [Required]

        public Boolean Is_Component { get; set; }
        [Required]

        public Boolean Is_Override { get; set; }
        [Required]

        public String Answer_Text { get; set; }
        [Required]

        public String Component_Guid { get; set; }
    }

    public class jUSER_DETAIL_INFORMATION
    {
        public jUSER_DETAIL_INFORMATION()
        {
            jADDRESSes = new List<jADDRESS>();
        }
        public List<jADDRESS> jADDRESSes { get; set; }
        [Required]

        public Guid Id { get; set; }
        public String CellPhone { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String HomePhone { get; set; }
        public String OfficePhone { get; set; }
        public String ImagePath { get; set; }
        public String JobTitle { get; set; }
        public String Organization { get; set; }
        public String PrimaryEmail { get; set; }
        public String SecondaryEmail { get; set; }
    }
}
