WITH AllCustomRowCounts as 
(
	SELECT COUNT(*) as RowCnt FROM [NEW_REQUIREMENT]
	UNION ALL
	SELECT COUNT(*) FROM [NEW_QUESTION]
	UNION ALL
	SELECT COUNT(*) FROM [NEW_QUESTION_SETS]
	UNION ALL
	SELECT COUNT(*) FROM [UNIVERSAL_SUB_CATEGORY_HEADINGS]
	UNION ALL
	SELECT COUNT(*) FROM [UNIVERSAL_SUB_CATEGORIES]
)
SELECT SUM(RowCnt) as TotalCustomRowCount from AllCustomRowCounts