import { Component, OnInit } from '@angular/core';
import { AuthenticationExternalService } from '../services/authentication-external.service';
import { Router } from '@angular/router';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { ConfigService } from '../services/config.service';
import { firstValueFrom } from 'rxjs';
import { AuthenticationService, LoginResponse } from '../services/authentication.service';
import { TranslocoService } from '@jsverse/transloco';
import { AssessmentService } from '../services/assessment.service';

@Component({
  selector: 'app-callback',
  imports: [],
  templateUrl: './callback.component.html',
  styleUrl: './callback.component.scss',
})
export class CallbackComponent implements OnInit {

  constructor(
    private authExtSvc: AuthenticationExternalService,
    private authSvc: AuthenticationService,
    private assessSvc: AssessmentService,
    private router: Router,
    private configSvc: ConfigService,
    private http: HttpClient,
    private tSvc: TranslocoService
  ) {

  }

  /**
   * 
   */
  async ngOnInit() {
    // this refreshes the configuration so that HTTPS is not required in development mode
    this.authExtSvc.initializeOAuth();

    try {
      await this.authExtSvc.oauthService.loadDiscoveryDocumentAndTryLogin();

      const claims = this.authExtSvc.oauthService.getIdentityClaims();

      const expTimeUnix = claims.exp;
      const nowUtcUnix = Math.floor(new Date().getTime() / 1000);
      if (nowUtcUnix > expTimeUnix) {
        throw new Error('Login token expired');
      }


      const accessToken = this.authExtSvc.oauthService.getAccessToken();
      const idToken = this.authExtSvc.oauthService.getIdToken();
      sessionStorage.setItem('oidc-token', accessToken);
      sessionStorage.setItem('oidc-id-token', idToken);


      // Send token to your backend
      this.logUserIn(accessToken);

    } catch (error) {
      console.error('Login failed:', error);
    }
  }

  /**
   * Passes the authorization token generated by the IdP
   * to the API.  The API will validate the token, find 
   * the user in question and log them in.
   */
  async logUserIn(accessToken: string) {
    const headers = new HttpHeaders({
      'Authorization': `Bearer ${accessToken}`,
      'cset-tzoffset': new Date().getTimezoneOffset().toString(),
      'cset-scope': 'CSET'
    });

    const obs = this.http.post(this.configSvc.apiUrl + 'auth/token-login', {}, { headers });
    const prom = firstValueFrom(obs);

    return prom.then(
      (response: LoginResponse) => {
        this.authSvc.isLocal = false;
        this.authSvc.storeUserData(response);


        // if there's a language for the user, set it
        if (!!response?.lang) {
          this.tSvc.setActiveLang(response.lang);
          this.tSvc.load(response.lang);
        }

        localStorage.setItem('cset.isLocal', this.authSvc.isLocal + '');

        localStorage.setItem('cset.linkerDate', response?.linkerTime);

        // If the response contains a userId, we assume we are authenticated at this point and can configure the CISA assessor workflow switch
        // Otherwise, this will be configured after calling auth/login (non-standalone login)
        if (response?.userId) {
          this.authSvc.configureCisaAssessorWorkflow(response);
        }

        sessionStorage.removeItem('cset-assessments-page');

        this.assessSvc.dropAssessment();
        this.router.navigate(['/home'], { queryParamsHandling: 'preserve' });
      },
      (error) => {

      }
    );
  }
}
