USE [CSETWeb]
GO
/****** Object:  Table [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET]    Script Date: 6/28/2018 8:21:22 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET](
	[GM_FingerType] [varchar](200) NOT NULL,
	[Id] [int] NOT NULL,
 CONSTRAINT [PK_COMPONENT_SYMBOLS_GM_TO_CSET] PRIMARY KEY CLUSTERED 
(
	[GM_FingerType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'ADA Control', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'AIMPP Hello', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'AIMPP Port Req', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Allen Bradley\Allen Bradley Web Server', 36)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Allen Bradley\Allen Bradley Web Server Device Description', 36)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Allen Bradley\Allen Bradley Web Server Device Name', 36)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Bizware CTP Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Bizware PlantMetrics Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Bizware Production Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Bizware Server Manager', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Bizware Task Manager', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Building Automation and Control Networks', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'CAMP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'CNRP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'CT Discovery Protocol', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'CTI Program Load', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'CTI System Message', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Cutler-Hammer IP Port', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Data Acquisition and Control', 10)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'DLIP', 27)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'DNP3 TCP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'DNP3 TCP Master', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'DNP3 TCP Slave', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'DNP3 UDP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'DNP3 UDP Master', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'DNP3 UDP Slave', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP (CIP) Explicit Messaging (TCP) - Replier', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP (CIP) Explicit Messaging (TCP) - Requester', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP (CIP) Explicit Messaging (UDP) - Replier', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP (CIP) Explicit Messaging (UDP) - Requester', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP UDP List Identity Response Device Type', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP UDP List Identity Response Product Code', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP UDP List Identity Response Product Name', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP UDP List Identity Response Serial Number', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'EtherNetIP UDP List Identity Response Vendor ID', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Extensible Automation', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Factory Talk Directory Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Factory Talk Directory Server File Transfer', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Factory Talk Event Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FactoryTalk Alarming Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FactoryTalk Event Multiplexor', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FactoryTalk Object RPC', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FactoryTalk Server Health', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FactoryTalk Service control', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Fagordnc', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FF Annunciation', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FF Fieldbus Message Specification', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FF LAN Redundancy Port', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FF SYstem Management', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'fingerprints.csv', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FlexLM Server', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'FODMS FLIP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'GE 9030 Device', 21)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'GE 9030 Engineering  workstation', 7)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'HMS HICP Port', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'I-NET 2000-NPR', 23)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'IBM MQSeries SCADA', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Invensys Sigma Port', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'IP Control Systems Ltd', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'IT Environmental Monitor', 24)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'JAUS Robots', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'LonWorks', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'LonWorks2', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'MocanaSSH2', 15)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'MODBUS TCP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'MODBUS TCP Master', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'MODBUS TCP Slave', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'MODBUS UDP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'MODBUS UDP Client', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'MODBUS UDP Server', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Network Time Protocol', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Novar Alarm', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Novar Data', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Novar Global', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'OMF Data b', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'OMF data h', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'OMF data l', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'OMF Data M', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'OneHome Remote Access', 22)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'OneHome Service Port', 22)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'PNBSCADA', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'PROFInet Context Manager', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'PROFInet RT Multicast', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'PROFInet RT Unicast', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'RNRP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Rockwell CSP1', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Rockwell CSP2', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Rockwell CSP3', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Rockwell Encapsulation', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'RSSql Compression Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'RSSql Configuration Server', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'RSSql Transaction Manager', 2)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'RSVIEWSE HMI Activation', 10)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'RSViewSE HMI Server', 10)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'RSViewSE Server Framework', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'SEL\SEL-351A Device Info From ID Cmd', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Server View dmbs Access', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'ServerStart RemoteControl', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Siemens AuD SCP', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Simple Network Management Protocol', 30)
GO
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'TCIM-control', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Trio Motion Control Port', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Trivial File Transfer Protocol', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Trivial Network Management', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'Undocumented usage by Intelligent Instrumentation EDAS unites', 30)
INSERT [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] ([GM_FingerType], [Id]) VALUES (N'WWIO Talk', 30)
ALTER TABLE [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET]  WITH NOCHECK ADD  CONSTRAINT [FK_COMPONENT_SYMBOLS_GM_TO_CSET_COMPONENT_SYMBOLS] FOREIGN KEY([Id])
REFERENCES [dbo].[COMPONENT_SYMBOLS] ([Id])
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS_GM_TO_CSET] CHECK CONSTRAINT [FK_COMPONENT_SYMBOLS_GM_TO_CSET_COMPONENT_SYMBOLS]
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS_GM_TO_CSET'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS_GM_TO_CSET'
GO
