USE [CSETWeb]
GO
/****** Object:  Table [dbo].[USER_SECURITY_QUESTIONS]    Script Date: 6/28/2018 8:21:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_SECURITY_QUESTIONS](
	[UserId] [int] NOT NULL,
	[SecurityQuestionID] [int] NOT NULL,
	[SecurityAnswer] [varchar](500) NULL,
 CONSTRAINT [PK_USER_SECURITY_QUESTIONS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[SecurityQuestionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[USER_SECURITY_QUESTIONS] ([UserId], [SecurityQuestionID], [SecurityAnswer]) VALUES (27, 17, N'bar')
ALTER TABLE [dbo].[USER_SECURITY_QUESTIONS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SECURITY_QUESTIONS_SECURITY_QUESTION] FOREIGN KEY([SecurityQuestionID])
REFERENCES [dbo].[SECURITY_QUESTION] ([SecurityQuestionId])
GO
ALTER TABLE [dbo].[USER_SECURITY_QUESTIONS] CHECK CONSTRAINT [FK_USER_SECURITY_QUESTIONS_SECURITY_QUESTION]
GO
ALTER TABLE [dbo].[USER_SECURITY_QUESTIONS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SECURITY_QUESTIONS_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_SECURITY_QUESTIONS] CHECK CONSTRAINT [FK_USER_SECURITY_QUESTIONS_USERS]
GO
