USE [CSETWeb]
GO
/****** Object:  Table [dbo].[ASSESSMENT_CONTACTS]    Script Date: 6/28/2018 8:21:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASSESSMENT_CONTACTS](
	[Assessment_Id] [int] NOT NULL,
	[PrimaryEmail] [varchar](150) NOT NULL,
	[FirstName] [varchar](150) NULL,
	[LastName] [varchar](150) NULL,
	[Invited] [bit] NOT NULL,
	[AssessmentRoleId] [int] NOT NULL,
	[UserId] [int] NULL,
	[Contact_Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_ASSESSMENT_CONTACTS_1] PRIMARY KEY CLUSTERED 
(
	[Assessment_Id] ASC,
	[PrimaryEmail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ASSESSMENT_CONTACTS] ON 

SET IDENTITY_INSERT [dbo].[ASSESSMENT_CONTACTS] OFF
/****** Object:  Index [IX_ASSESSMENT_CONTACTS]    Script Date: 6/28/2018 8:21:31 AM ******/
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS] ADD  CONSTRAINT [IX_ASSESSMENT_CONTACTS] UNIQUE NONCLUSTERED 
(
	[Contact_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS] ADD  CONSTRAINT [DF_ASSESSMENT_CONTACTS_AssessmentRole]  DEFAULT ((0)) FOR [AssessmentRoleId]
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS]  WITH CHECK ADD  CONSTRAINT [FK_ASSESSMENT_CONTACTS_ASSESSMENT_ROLES] FOREIGN KEY([AssessmentRoleId])
REFERENCES [dbo].[ASSESSMENT_ROLES] ([AssessmentRoleId])
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS] CHECK CONSTRAINT [FK_ASSESSMENT_CONTACTS_ASSESSMENT_ROLES]
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS]  WITH CHECK ADD  CONSTRAINT [FK_ASSESSMENT_CONTACTS_ASSESSMENTS] FOREIGN KEY([Assessment_Id])
REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS] CHECK CONSTRAINT [FK_ASSESSMENT_CONTACTS_ASSESSMENTS]
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS]  WITH NOCHECK ADD  CONSTRAINT [FK_ASSESSMENT_CONTACTS_USERS] FOREIGN KEY([PrimaryEmail])
REFERENCES [dbo].[USERS] ([PrimaryEmail])
NOT FOR REPLICATION 
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS] NOCHECK CONSTRAINT [FK_ASSESSMENT_CONTACTS_USERS]
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS]  WITH CHECK ADD  CONSTRAINT [FK_ASSESSMENT_CONTACTS_USERS1] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ASSESSMENT_CONTACTS] CHECK CONSTRAINT [FK_ASSESSMENT_CONTACTS_USERS1]
GO
