USE [CSETWeb]
GO
/****** Object:  Table [dbo].[CNSS_CIA_JUSTIFICATIONS]    Script Date: 11/14/2018 3:57:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CNSS_CIA_JUSTIFICATIONS](
	[Assessment_Id] [int] NOT NULL,
	[CIA_Type] [varchar](50) NOT NULL,
	[DropDownValueLevel] [varchar](50) NOT NULL,
	[Justification] [varchar](1500) NOT NULL,
 CONSTRAINT [PK_CNSS_CIA_JUSTIFICATIONS] PRIMARY KEY CLUSTERED 
(
	[Assessment_Id] ASC,
	[CIA_Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CNSS_CIA_JUSTIFICATIONS]  WITH CHECK ADD  CONSTRAINT [FK_CNSS_CIA_JUSTIFICATIONS_ASSESSMENTS] FOREIGN KEY([Assessment_Id])
REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CNSS_CIA_JUSTIFICATIONS] CHECK CONSTRAINT [FK_CNSS_CIA_JUSTIFICATIONS_ASSESSMENTS]
GO
ALTER TABLE [dbo].[CNSS_CIA_JUSTIFICATIONS]  WITH CHECK ADD  CONSTRAINT [FK_CNSS_CIA_JUSTIFICATIONS_CNSS_CIA_TYPES] FOREIGN KEY([CIA_Type])
REFERENCES [dbo].[CNSS_CIA_TYPES] ([CIA_Type])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CNSS_CIA_JUSTIFICATIONS] CHECK CONSTRAINT [FK_CNSS_CIA_JUSTIFICATIONS_CNSS_CIA_TYPES]
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CNSS_CIA_JUSTIFICATIONS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CNSS_CIA_JUSTIFICATIONS'
GO
