USE [CSETWeb]
GO
/****** Object:  Table [dbo].[INFORMATION]    Script Date: 6/28/2018 8:21:24 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INFORMATION](
	[Id] [int] NOT NULL,
	[Assessment_Name] [nvarchar](100) NOT NULL,
	[Assessment_Date] [datetime] NOT NULL,
	[Facility_Name] [nvarchar](100) NULL,
	[City_Or_Site_Name] [nvarchar](100) NULL,
	[State_Province_Or_Region] [nvarchar](100) NULL,
	[Assessor_Name] [nvarchar](100) NULL,
	[Assessor_Email] [nvarchar](100) NULL,
	[Assessor_Phone] [nvarchar](100) NULL,
	[Assessment_Description] [nvarchar](4000) NULL,
	[Additional_Notes_And_Comments] [nvarchar](4000) NULL,
	[Additional_Contacts] [ntext] NULL,
	[Executive_Summary] [ntext] NULL,
	[Enterprise_Evaluation_Summary] [ntext] NULL,
	[Real_Property_Unique_Id] [nvarchar](70) NULL,
	[eMass_Document_Id] [int] NULL,
 CONSTRAINT [PK__Information__000000000000023C] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (4, N'Review for Rick', CAST(N'2018-04-06T00:21:48.347' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (5, N'February Review', CAST(N'2018-04-06T16:29:03.240' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (6, N'Initial Review', CAST(N'2018-04-06T17:17:13.867' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (25, N'This is a test from quicktest', CAST(N'2018-05-08T06:00:00.000' AS DateTime), N'Barry''s House', N'IDaho Falls', N'ID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (26, N'Not Mitch''s Assessment', CAST(N'2018-05-16T07:07:26.500' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (27, N'Assessment NCC-1701-C', CAST(N'2017-05-16T18:00:00.000' AS DateTime), N'Headquarters 12345', N'St. Louis', N'MO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (28, N'Mitch''s Assessment', CAST(N'2018-05-18T00:25:30.437' AS DateTime), N'The Mucky Duck', N'Sheboygan', N'WI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (29, N'Test', CAST(N'2018-05-21T10:15:59.803' AS DateTime), N'Test1', N'Test2', N'Test3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (30, N'New Assessment', CAST(N'2018-05-22T12:24:46.010' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (32, N'New Assessment', CAST(N'2018-06-06T10:16:23.937' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (33, N'1', CAST(N'2018-06-10T19:05:42.047' AS DateTime), NULL, N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (34, N'New Assessment', CAST(N'2018-06-11T13:11:12.020' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (35, N'New Assessment', CAST(N'2018-06-11T07:23:40.973' AS DateTime), N'fac name', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (36, N'New Assessment', CAST(N'2018-06-11T07:30:51.403' AS DateTime), N'test', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (37, N'New Assessment', CAST(N'2018-06-11T13:31:21.637' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (38, N'New Assessment', CAST(N'2018-06-11T07:33:10.860' AS DateTime), N'test', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (39, N'Test', CAST(N'2018-06-12T06:00:00.000' AS DateTime), N'Test Fac', N'Idaho Falls', N'ID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (40, N'NewTest Assessment', CAST(N'2018-06-11T07:50:10.580' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (41, N'New Assessment', CAST(N'2018-06-11T13:54:50.180' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (42, N'New Assessment', CAST(N'2018-06-11T13:59:11.577' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (43, N'NewTest Assessment', CAST(N'2018-06-11T08:01:00.373' AS DateTime), N'Facilyt Test Name', N'Idaho Falls', N'ID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (44, N'New Assessment', CAST(N'2018-06-11T14:03:34.020' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (45, N'New Assessment', CAST(N'2018-06-11T14:08:38.447' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (46, N'Today''s Assessment', CAST(N'2018-06-11T09:09:02.687' AS DateTime), N'Another facility', N'Granite Flats', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (47, N'My new assessment', CAST(N'2017-06-08T06:00:00.000' AS DateTime), N'Another facility', N'Granite Flats', N'CO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (48, N'New Assessment', CAST(N'2018-06-11T15:21:07.640' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (49, N'New Assessment', CAST(N'2018-06-11T15:23:30.237' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (50, N'New Assessment', CAST(N'2018-06-11T15:27:43.320' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (51, N'New Assessment', CAST(N'2018-06-11T15:31:41.743' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (52, N'New Assessment', CAST(N'2018-06-11T15:41:27.663' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (53, N'New Assessment', CAST(N'2018-06-11T09:43:15.103' AS DateTime), N'this text should be saved', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (54, N'New Assessment', CAST(N'2018-06-11T09:46:10.387' AS DateTime), N'Barry''s House', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (55, N'New Assessment', CAST(N'2018-06-12T08:39:56.470' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (56, N'New Assessment', CAST(N'2018-06-12T08:52:00.500' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (57, N'New Assessment', CAST(N'2018-06-12T13:39:07.440' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (58, N'New Assessment', CAST(N'2018-06-12T13:39:19.363' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (59, N'New Assessment', CAST(N'2018-06-12T13:49:12.967' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (60, N'New Assessment', CAST(N'2018-06-12T13:52:11.300' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (61, N'New Assessment', CAST(N'2018-06-12T13:57:32.867' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (62, N'New Assessment', CAST(N'2018-06-12T14:02:29.873' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (63, N'New Assessment', CAST(N'2018-06-12T14:06:12.627' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (64, N'New Assessment', CAST(N'2018-06-12T14:08:47.020' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (65, N'New Assessment', CAST(N'2018-06-12T14:13:55.870' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (66, N'New Assessment', CAST(N'2018-06-12T14:15:31.810' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (67, N'New Assessment', CAST(N'2018-06-12T14:15:38.030' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (68, N'New Assessment', CAST(N'2018-06-12T14:15:42.560' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (69, N'New Assessment', CAST(N'2018-06-12T14:15:43.387' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (70, N'New Assessment', CAST(N'2018-06-12T14:15:44.903' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (71, N'New Assessment', CAST(N'2018-06-12T14:16:07.607' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (72, N'New Assessment', CAST(N'2018-06-12T14:16:09.733' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (73, N'New Assessment', CAST(N'2018-06-12T14:16:55.733' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (74, N'New Assessment', CAST(N'2018-06-12T14:16:57.547' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (75, N'New Assessment', CAST(N'2018-06-12T14:22:35.303' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (76, N'New Assessment', CAST(N'2018-06-12T14:25:34.320' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (77, N'New Assessment', CAST(N'2018-06-12T14:41:55.927' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (78, N'New Assessment', CAST(N'2018-06-12T14:41:56.553' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (79, N'New Assessment', CAST(N'2018-06-12T14:41:57.053' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (80, N'New Assessment', CAST(N'2018-06-12T14:41:57.553' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (81, N'New Assessment', CAST(N'2018-06-12T14:41:58.007' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (82, N'New Assessment', CAST(N'2018-06-12T14:41:58.383' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (83, N'New Assessment', CAST(N'2018-06-12T14:41:58.930' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (84, N'New Assessment', CAST(N'2018-06-12T14:41:59.320' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (85, N'New Assessment', CAST(N'2018-06-13T08:29:52.037' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (86, N'New Assessment', CAST(N'2018-06-13T13:16:30.473' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (87, N'New Assessment', CAST(N'2018-06-13T13:16:33.380' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (88, N'New Assessment', CAST(N'2018-06-13T13:16:33.927' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (89, N'New Assessment', CAST(N'2018-06-13T13:16:34.147' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (90, N'New Assessment', CAST(N'2018-06-13T13:16:34.333' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (91, N'New Assessment', CAST(N'2018-06-13T13:16:34.490' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (92, N'New Assessment', CAST(N'2018-06-13T13:16:42.990' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (93, N'New Assessment', CAST(N'2018-06-13T14:52:29.163' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (94, N'New Assessment', CAST(N'2018-06-13T14:52:54.773' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (95, N'New Assessment', CAST(N'2018-06-13T16:36:48.907' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (96, N'New Assessment Friday', CAST(N'2018-06-13T10:37:33.457' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (97, N'New Assessment', CAST(N'2018-06-13T16:46:54.920' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (98, N'New Assessment DELETE ME', CAST(N'2018-06-13T10:48:38.657' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (99, N'New Assessment', CAST(N'2018-06-15T13:31:02.223' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (100, N'New Assessment', CAST(N'2018-06-15T13:33:01.993' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (101, N'blah', CAST(N'2018-06-15T07:33:14.823' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (102, N'New Assessment', CAST(N'2018-06-15T13:37:51.180' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[INFORMATION] ([Id], [Assessment_Name], [Assessment_Date], [Facility_Name], [City_Or_Site_Name], [State_Province_Or_Region], [Assessor_Name], [Assessor_Email], [Assessor_Phone], [Assessment_Description], [Additional_Notes_And_Comments], [Additional_Contacts], [Executive_Summary], [Enterprise_Evaluation_Summary], [Real_Property_Unique_Id], [eMass_Document_Id]) VALUES (103, N'New Assessment', CAST(N'2018-06-18T10:41:54.727' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ALTER TABLE [dbo].[INFORMATION] ADD  CONSTRAINT [DF_INFORMATION_Assessment_Date]  DEFAULT (getdate()) FOR [Assessment_Date]
GO
ALTER TABLE [dbo].[INFORMATION]  WITH NOCHECK ADD  CONSTRAINT [FK_INFORMATION_DOCUMENT_FILE1] FOREIGN KEY([eMass_Document_Id])
REFERENCES [dbo].[DOCUMENT_FILE] ([Document_Id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[INFORMATION] CHECK CONSTRAINT [FK_INFORMATION_DOCUMENT_FILE1]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Assessment Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Assessment_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Assessment Date is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Assessment_Date'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Facility Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Facility_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The City Or Site Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'City_Or_Site_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The State Province Or Region is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'State_Province_Or_Region'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Assessor Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Assessor_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Assessor Email is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Assessor_Email'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Assessor Phone is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Assessor_Phone'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Assessment Description is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Assessment_Description'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Additional Notes And Comments is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Additional_Notes_And_Comments'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Additional Contacts is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Additional_Contacts'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Executive Summary is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Executive_Summary'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Enterprise Evaluation Summary is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION', @level2type=N'COLUMN',@level2name=N'Enterprise_Evaluation_Summary'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'INFORMATION'
GO
