USE [CSETWeb]
GO
/****** Object:  Table [dbo].[ADDRESS]    Script Date: 11/14/2018 3:57:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADDRESS](
	[PrimaryEmail] [varchar](150) NULL,
	[AddressType] [varchar](50) NOT NULL,
	[Id] [uniqueidentifier] NOT NULL,
	[City] [varchar](150) NULL,
	[Country] [varchar](150) NULL,
	[Line1] [varchar](150) NULL,
	[Line2] [varchar](150) NULL,
	[State] [varchar](150) NULL,
	[Zip] [varchar](150) NULL,
 CONSTRAINT [PK_ADDRESS_1] PRIMARY KEY CLUSTERED 
(
	[AddressType] ASC,
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ADDRESS_USER_DETAIL_INFORMATION1] FOREIGN KEY([Id])
REFERENCES [dbo].[USER_DETAIL_INFORMATION] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ADDRESS] CHECK CONSTRAINT [FK_ADDRESS_USER_DETAIL_INFORMATION1]
GO
