USE [CSETWeb]
GO
/****** Object:  Table [dbo].[FINDING_CONTACT]    Script Date: 6/28/2018 8:21:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FINDING_CONTACT](
	[Finding_Id] [int] NOT NULL,
	[Contact_Id] [int] NOT NULL,
	[IgnoreThis] [int] NULL,
 CONSTRAINT [PK_FINDING_CONTACT_1] PRIMARY KEY CLUSTERED 
(
	[Finding_Id] ASC,
	[Contact_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[FINDING_CONTACT] ([Finding_Id], [Contact_Id], [IgnoreThis]) VALUES (3, 15, NULL)
INSERT [dbo].[FINDING_CONTACT] ([Finding_Id], [Contact_Id], [IgnoreThis]) VALUES (3, 55, NULL)
INSERT [dbo].[FINDING_CONTACT] ([Finding_Id], [Contact_Id], [IgnoreThis]) VALUES (5, 9, NULL)
INSERT [dbo].[FINDING_CONTACT] ([Finding_Id], [Contact_Id], [IgnoreThis]) VALUES (5, 10, NULL)
ALTER TABLE [dbo].[FINDING_CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_FINDING_CONTACT_ASSESSMENT_CONTACTS] FOREIGN KEY([Contact_Id])
REFERENCES [dbo].[ASSESSMENT_CONTACTS] ([Contact_Id])
GO
ALTER TABLE [dbo].[FINDING_CONTACT] CHECK CONSTRAINT [FK_FINDING_CONTACT_ASSESSMENT_CONTACTS]
GO
ALTER TABLE [dbo].[FINDING_CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_FINDING_INDIVIDUAL_FINDING1] FOREIGN KEY([Finding_Id])
REFERENCES [dbo].[FINDING] ([Finding_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FINDING_CONTACT] CHECK CONSTRAINT [FK_FINDING_INDIVIDUAL_FINDING1]
GO
