USE [CSETWeb]
GO
/****** Object:  Table [dbo].[FINDING]    Script Date: 11/14/2018 3:57:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FINDING](
	[Answer_Id] [int] NOT NULL,
	[Finding_Id] [int] IDENTITY(1,1) NOT NULL,
	[Summary] [varchar](max) NULL,
	[Issue] [varchar](max) NULL,
	[Impact] [varchar](max) NULL,
	[Recommendations] [varchar](max) NULL,
	[Vulnerabilities] [varchar](max) NULL,
	[Resolution_Date] [datetime2](7) NULL,
	[Importance_Id] [int] NULL,
 CONSTRAINT [PK_FINDING] PRIMARY KEY CLUSTERED 
(
	[Finding_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FINDING]  WITH CHECK ADD  CONSTRAINT [FK_FINDING_ANSWER] FOREIGN KEY([Answer_Id])
REFERENCES [dbo].[ANSWER] ([Answer_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FINDING] CHECK CONSTRAINT [FK_FINDING_ANSWER]
GO
ALTER TABLE [dbo].[FINDING]  WITH NOCHECK ADD  CONSTRAINT [FK_FINDING_IMPORTANCE1] FOREIGN KEY([Importance_Id])
REFERENCES [dbo].[IMPORTANCE] ([Importance_Id])
ON UPDATE CASCADE
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[FINDING] CHECK CONSTRAINT [FK_FINDING_IMPORTANCE1]
GO
