USE [CSETWeb]
GO
/****** Object:  Table [dbo].[USER_SECURITY_QUESTIONS]    Script Date: 11/14/2018 3:57:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_SECURITY_QUESTIONS](
	[UserId] [int] NOT NULL,
	[SecurityQuestion1] [varchar](250) NULL,
	[SecurityAnswer1] [varchar](250) NULL,
	[SecurityQuestion2] [varchar](250) NULL,
	[SecurityAnswer2] [varchar](250) NULL,
 CONSTRAINT [PK_USER_SECURITY_QUESTIONS_1] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_SECURITY_QUESTIONS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SECURITY_QUESTIONS_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_SECURITY_QUESTIONS] CHECK CONSTRAINT [FK_USER_SECURITY_QUESTIONS_USERS]
GO
