USE [CSETWeb]
GO
/****** Object:  Table [dbo].[COMPONENT_SYMBOLS]    Script Date: 6/28/2018 8:21:22 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPONENT_SYMBOLS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Diagram_Type_Xml] [varchar](50) NOT NULL,
	[File_Name] [varchar](100) NOT NULL,
	[Component_Family_Name] [varchar](150) NOT NULL,
	[Symbol_Group_Id] [int] NOT NULL,
	[Abbreviation] [varchar](5) NULL,
	[IsService] [bit] NOT NULL,
	[Long_Name] [varchar](100) NOT NULL,
	[Display_Name] [varchar](100) NOT NULL,
 CONSTRAINT [PK_COMPONENT_SYMBOLS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[COMPONENT_SYMBOLS] ON 

INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (1, N'Wireless', N'Wireless Network', N'wireless_network.xaml', N'Comm/Network', 2, N'WI', 1, N'Wireless Network', N'Wireless Network')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (2, N'ApplicationServer', N'Application Server', N'application_server.xaml', N'Servers', 2, N'AS', 1, N'Application Server', N'Application Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (3, N'Clock', N'Clock', N'clock.xaml', N'Other', 2, N'CLK', 1, N'Clock', N'Clock')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (4, N'Connector', N'Connector', N'connector.xaml', N'Non-Question', 5, N'CON', 0, N'Connector', N'Connector')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (5, N'DatabaseServer', N'Database Server', N'database_server.xaml', N'Servers', 2, N'DB', 1, N'Database Server', N'DB Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (6, N'DCS', N'DCS', N'dcs.xaml', N'Control Units', 1, N'DCS', 1, N'Distributed Control System', N'DCS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (7, N'EngineeringWorkstation', N'Engineering Workstation', N'ews.xaml', N'Servers', 1, N'EW', 1, N'Engineering Workstation', N'EWS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (8, N'Firewall', N'Firewall', N'firewall.xaml', N'Security', 2, N'FW', 1, N'Firewall', N'Firewall')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (9, N'FrontEndProcessor', N'Front End Processor', N'front_end_processor.xaml', N'Control Units', 1, N'FEP', 1, N'Front End Processor', N'FEP')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (10, N'HMI', N'HMI', N'hmi.xaml', N'Servers', 1, N'HMI', 1, N'Human Machine Interface', N'HMI')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (11, N'Hub', N'Hub', N'hub.xaml', N'Comm/Network', 2, N'HUB', 1, N'Hub', N'Hub')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (12, N'IDS', N'IDS', N'ids.xaml', N'Security', 2, N'IDS', 1, N'Intrusion Detection System', N'IDS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (13, N'IED', N'IED', N'ied.xaml', N'Control Units', 1, N'IED', 1, N'Intelligent Embedded Device', N'IED')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (14, N'IPS', N'IPS', N'ips.xaml', N'Security', 2, N'IPS', 1, N'Intrusion Prevention System', N'IPS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (15, N'LinkEncryption', N'Link Encryption', N'link_encryption.xaml', N'Security', 2, N'LE', 1, N'Link Encryption', N'Link Encryption')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (16, N'Modem', N'Modem', N'modem.xaml', N'Comm/Network', 2, N'MOD', 1, N'Modem', N'Modem')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (17, N'MTU', N'MTU', N'mtu.xaml', N'Control Units', 1, N'MTU', 1, N'Master Terminal Unit', N'MTU')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (18, N'NetworkPrinter', N'Network Printer', N'network_printer.xaml', N'Other', 2, N'NP', 1, N'Network Printer', N'Network Printer')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (19, N'OpticalRingSystem', N'Optical Ring System', N'optical_ring.xaml', N'Comm/Network', 2, N'ORS', 1, N'Optical Ring System', N'Optical Ring')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (20, N'Partner', N'Partner', N'partner.xaml', N'Non-Question', 5, N'PA', 0, N'Partner', N'Partner')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (21, N'PLC', N'PLC', N'plc.xaml', N'Control Units', 1, N'PLC', 1, N'Programmable Logic Controller', N'PLC')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (22, N'RemoteAccessServer', N'Remote Access Server', N'remote_access_server.xaml', N'Servers', 2, N'RAS', 1, N'Remote Access Server', N'RAS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (23, N'Router', N'Router', N'router.xaml', N'Comm/Network', 2, N'RTR', 1, N'Router', N'Router')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (24, N'RTU', N'RTU', N'rtu.xaml', N'Control Units', 1, N'RTU', 1, N'Remote Terminal Unit', N'RTU')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (25, N'SerialRadio', N'Serial Radio', N'serial_radio.xaml', N'Comm/Network', 2, N'SR', 1, N'Serial Radio', N'Serial Radio')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (26, N'SerialSwitch', N'Serial Switch', N'serial_switch.xaml', N'Comm/Network', 2, N'SSW', 1, N'Serial Switch', N'Serial Switch')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (27, N'Switch', N'Switch', N'switch.xaml', N'Comm/Network', 2, N'SW', 1, N'Switch', N'Switch')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (28, N'TerminalServer', N'Terminal Server', N'terminal_server.xaml', N'Servers', 1, N'TS', 1, N'Terminal Server', N'Terminal Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (29, N'UnidirectionalDevice', N'Unidirectional Device', N'unidirectional_device.xaml', N'Comm/Network', 1, N'UD', 1, N'Unidirectional Device', N'Unidirectional Device')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (30, N'Unknown', N'Unknown', N'unknown.xaml', N'Non-Question', 5, N'UN', 1, N'Unknown', N'Unknown')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (31, N'Vendor', N'Vendor', N'vendor.xaml', N'Non-Question', 5, N'VE', 0, N'Vendor', N'Vendor')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (32, N'VLANRouter', N'VLAN Router', N'vlan_router.xaml', N'Comm/Network', 2, N'VLANR', 1, N'Virtual Local Area Network Router', N'VLAN Router')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (33, N'VLANSwitch', N'VLAN Switch', N'vlan_switch.xaml', N'Comm/Network', 2, N'VLANS', 1, N'Virtual Local Area Network Switch', N'VLAN Switch')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (34, N'VPN', N'VPN', N'vpn.xaml', N'Security', 2, N'VPN', 1, N'Virtual Private Network', N'VPN')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (35, N'Web', N'Web', N'web.xaml', N'Non-Question', 5, N'WEB', 0, N'Web', N'Web')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (36, N'WebServer', N'Web Server', N'web_server.xaml', N'Servers', 2, N'WEBS', 1, N'Web Server', N'Web Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (37, N'SafetyInstrumentedSystem', N'Safety Instrumented System', N'sis.xaml', N'Other', 1, N'SIS', 1, N'Safety Instrumented System', N'SIS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (38, N'HandHeld', N'Handheld Wireless Device', N'handheld_wireless_device.xaml', N'Other', 2, N'HW', 1, N'Handheld Wireless Device', N'Handheld Wireless Device')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (44, N'ActiveDirectory', N'Active Directory', N'active_directory.xaml', N'Other', 2, N'AD', 1, N'Active Directory', N'Active Directory')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (45, N'IPCamera', N'IP Camera', N'ip_camera.xaml', N'Other', 2, N'IPC', 1, N'Internet Protocol Camera', N'IP Camera')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (46, N'IPPhone', N'IP Phone', N'ip_phone.xaml', N'Other', 2, N'IPP', 1, N'Internet Protocol Phone', N'IP Phone')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (47, N'PC', N'PC', N'pc.xaml', N'Servers', 2, N'PC', 1, N'Personal Computer', N'PC')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (48, N'Server', N'Server', N'server.xaml', N'Servers', 2, N'SVR', 1, N'Server', N'Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (49, N'MultipleServicesComponent', N'Multiple Services Component', N'multiple_services_component.xaml', N'Servers', 2, N'MSC', 0, N'Multiple Services Component', N'Multiple Services Component')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (51, N'WirelessModem', N'Wireless Modem', N'wireless_modem.xaml', N'Comm/Network', 2, N'WM', 1, N'Wireless Modem', N'Wireless Modem')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (53, N'DNSServer', N'DNS Server', N'dns_server.xaml', N'Servers', 2, N'DNS', 1, N'Domain Name System Server', N'DNS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (54, N'MailServer', N'Mail Server', N'mail_server.xaml', N'Servers', 2, N'MAIL', 1, N'Email Server', N'Mail Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (55, N'Historian', N'Historian', N'historian.xaml', N'Servers', 1, N'HIST', 1, N'Historian', N'Historian')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (57, N'ConfigurationServer', N'Configuration Server', N'configuration_server.xaml', N'Servers', 1, N'CNFIG', 1, N'Configuration Server', N'Configuration Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (59, N'ImagingModalitiesAndEquipment', N'Imaging Modalities and Equipment', N'imaging_modalities_and_equipment.xaml', N'Other', 4, N'IME', 1, N'Imaging Modalities and Equipment', N'IME')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (60, N'PhysiologicalMonitoringDevice', N'Physiological Monitoring System', N'physiological_monitoring_system.xaml', N'Other', 4, N'PMD', 1, N'Physiological Monitoring System', N'Medical Monitoring Device')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (61, N'ElectronicSecuritySystem', N'Electronic Security System', N'electronic_security_system.xaml', N'Other', 2, N'ESS', 1, N'Electronic Security System', N'ESS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (62, N'VideoTeleconferencingEquipment', N'Video Teleconferencing Equipment', N'video_teleconferencing_equipment.xaml', N'Other', 2, N'VTC', 1, N'Video Teleconferencing Equipment', N'VTC')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (63, N'BuildingAutomationManagementSystems', N'Building Automation Management Systems', N'building_automation_management_systems.xaml', N'Other', 2, N'BAS', 1, N'Building Automation Management Systems', N'BAS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (64, N'InteractiveTelevisionSystem', N'Interactive Television System', N'interactive_television_system.xaml', N'Other', 2, N'ITV', 1, N'Interactive Television System', N'ITV')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (66, N'UninterruptiblePowerSupply', N'Uninterruptible Power Supply', N'uninterruptible_power_supply.xaml', N'Other', 2, N'UPS', 1, N'Uninterruptible Power Supply', N'UPS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (67, N'NetworkScannerAndCopier', N'Network Scanner And Copier', N'network_scanner_and_copier.xaml', N'Other', 2, N'NSC', 1, N'Network Scanner And Copier', N'NSC')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (68, N'PublicKiosk', N'Public Kiosk', N'public_kiosk.xaml', N'Other', 2, N'KIO', 1, N'Public Kiosk', N'Kiosk')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (69, N'RFIDTransmitter', N'RFID Transmitter', N'rfid_transmitter.xaml', N'Other', 2, N'RFID', 1, N'RFID Transmitter', N'RFID')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (70, N'RealTimeLocationSystem', N'Real Time Location System', N'real_time_location_system.xaml', N'Other', 4, N'RTLS', 1, N'Real Time Location System', N'RTLS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (72, N'ImagingServer', N'Imaging Server', N'imaging_server.xaml', N'Servers', 4, N'IMG', 1, N'Imaging Server', N'Imaging Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (73, N'EmergencyMedicalServiceCommunicationsHardware', N'Emergency Medical Service Communications Hardware', N'emergency_medical_service_communications_hardware.xaml', N'Other', 4, N'EMS', 1, N'Emergency Medical Service Communications Hardware', N'EMS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (74, N'MicrowaveBackhaul', N'Microwave Backhaul', N'microwave_backhaul.xaml', N'Comm/Network', 3, N'MB', 1, N'Microwave Backhaul', N'Microwave Backhaul')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (76, N'T1Backhaul', N'T1 Backhaul', N't1_backhaul.xaml', N'Comm/Network', 3, N'T1', 1, N'T1 Backhaul', N'T1 Backhaul')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (77, N'EthernetBackhaul', N'Ethernet Backhaul', N'ethernet_backhaul.xaml', N'Comm/Network', 3, N'EB', 1, N'Ethernet Backhaul', N'Ethernet Backhaul')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (78, N'TDMBackhaul', N'TDM Backhaul', N'tdm_backhaul.xaml', N'Comm/Network', 3, N'TDM', 1, N'TDM Backhaul', N'TDM Backhaul')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (79, N'AudioSwitch', N'Audio Switch', N'audio_switch.xaml', N'Comm/Network', 3, N'AudS', 1, N'Audio Switch', N'Audio Switch')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (80, N'RelayPanel', N'Relay Panel', N'relay_panel.xaml', N'Comm/Network', 3, N'RP', 1, N'Relay Panel', N'Relay Panel')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (81, N'RadioSite', N'Radio Site', N'radio_site.xaml', N'Comm/Network', 3, N'RS', 1, N'Radio Site', N'Radio Site')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (82, N'SubscriberRadio', N'Subscriber Radio', N'subscriber_radio.xaml', N'Comm/Network', 3, N'SubR', 1, N'Subscriber Radio', N'Subscriber Radio')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (83, N'DispatchConsole', N'Dispatch Console', N'dispatch_console.xaml', N'Comm/Network', 3, N'DC', 1, N'Dispatch Console', N'Dispatch Console')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (84, N'MasterSite', N'Master Site', N'master_site.xaml', N'Comm/Network', 3, N'MS', 1, N'Master Site', N'Master Site')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (85, N'VirtualMachineServer', N'Virtual Machine Server', N'virtual_machine_server.xaml', N'Servers', 2, N'VM', 1, N'Virtual Machine Server', N'Virtual Machine Server')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (86, N'WirelessRouter', N'Wireless Router', N'wireless_router.xaml', N'Comm/Network', 2, N'WR', 1, N'Wireless Router', N'Wireless Router')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (87, N'MagneticResonanceImaging', N'Magnetic Resonance Imaging', N'magnetic_resonance_imaging.xaml', N'Other', 4, N'MRI', 1, N'Magnetic Resonance Imaging Equipment', N'MRI')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (88, N'XRayGenerator', N'XRay Generator', N'xray_generator.xaml', N'Other', 4, N'XRay', 1, N'XRay Generator', N'Xray')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (89, N'CT Scanner', N'CT Scanner', N'ct_scanner.xaml', N'Other', 4, N'CT', 1, N'CT Scanner', N'CT Scan')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (90, N'Ultrasound', N'Ultrasound', N'ultrasound.xaml', N'Other', 4, N'US', 1, N'Ultrasound', N'Ultrasound')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (91, N'LinearParticalAccelerator', N'Linear Partical Accelerator', N'linear_partical_accelerator.xaml', N'Other', 4, N'Linac', 1, N'Linear Partical Accelerator', N'Linac')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (92, N'EndoscopySystem', N'Endoscopy System', N'endoscopy_system.xaml', N'Other', 4, N'Endo', 1, N'Endoscopy System', N'Endoscopy')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (93, N'Electroencephalograph', N'EEG', N'eeg.xaml', N'Other', 4, N'EEG', 1, N'Electroencephalograph', N'EEG')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (94, N'Electrocardiograph', N'ECG', N'ecg.xaml', N'Other', 4, N'ECG', 1, N'Electrocardiograph', N'ECG')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (95, N'Electromyograph', N'EMG', N'emg.xaml', N'Other', 4, N'EMG', 1, N'Electromyograph', N'EMG')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (98, N'UrodynamicDiagnosticEquipment', N'Urodynamic Diagnostic Equipment', N'urodynamic_diagnostic_equipment.xaml', N'Other', 4, N'UDE', 1, N'Urodynamic Diagnostic Equipment', N'Urodynamic Equipment')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (99, N'DoorAccessDoorControlUnit', N'Door Access Door Control Unit', N'door_access_door_control_unit.xaml', N'Other', 2, N'DCU', 1, N'Door Access Door Control Unit', N'Door Control Unit')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (100, N'InfantProtectionRemoteDisplayUnit', N'Infant Protection Remote Display Unit', N'infant_protection_remote_display_unit.xaml', N'Other', 4, N'IPRDU', 1, N'Infant Protection Remote Display Unit', N'Remote Display Unit')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (101, N'InfusionPump', N'Infusion Pump', N'infusion_pump.xaml', N'Other', 4, N'IVPMP', 1, N'IV Infusion Pump', N'Infusion Pump')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (102, N'MedicalPipedGasSupplySystem', N'Medical Gas System', N'medical_gas_system.xaml', N'Other', 4, N'MPGSS', 1, N'Medical Piped Gas Supply System', N'Medical Gas')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (113, N'MultiProtocolLabelSwitching', N'Multi Protocol Label Switching', N'multi_protocol_label_switching.xaml', N'Comm/Network', 2, N'MPLS', 1, N'Multi Protocol Label Switching', N'MPLS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (118, N'PowerOverEthernet', N'Power Over Ethernet', N'power_over_ethernet.xaml', N'Comm/Network', 2, N'POE', 1, N'Power Over Ethernet', N'Power Over Ethernet')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (119, N'SecurityInfoAndEventMgmtSystem', N'Security Information And Event Management System', N'security_information_and_event_management_system.xaml', N'Comm/Network', 2, N'SIEMS', 1, N'Security Information and Event Management System', N'SIEMS')
INSERT [dbo].[COMPONENT_SYMBOLS] ([Id], [Name], [Diagram_Type_Xml], [File_Name], [Component_Family_Name], [Symbol_Group_Id], [Abbreviation], [IsService], [Long_Name], [Display_Name]) VALUES (120, N'WindowsUpdateServer', N'Windows Update Server', N'windows_update_server.xaml', N'Comm/Network', 2, N'WUS', 1, N'Windows Update Server', N'Windows Update Server')
SET IDENTITY_INSERT [dbo].[COMPONENT_SYMBOLS] OFF
ALTER TABLE [dbo].[COMPONENT_SYMBOLS] ADD  CONSTRAINT [DF_COMPONENT_SYMBOLS_HasService]  DEFAULT ((0)) FOR [IsService]
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS] ADD  CONSTRAINT [DF_COMPONENT_SYMBOLS_Long_Name]  DEFAULT ('') FOR [Long_Name]
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS] ADD  CONSTRAINT [DF_COMPONENT_SYMBOLS_Display_Name]  DEFAULT ('') FOR [Display_Name]
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS]  WITH CHECK ADD  CONSTRAINT [FK_COMPONENT_SYMBOLS_COMPONENT_FAMILY] FOREIGN KEY([Component_Family_Name])
REFERENCES [dbo].[COMPONENT_FAMILY] ([Component_Family_Name])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS] CHECK CONSTRAINT [FK_COMPONENT_SYMBOLS_COMPONENT_FAMILY]
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS]  WITH CHECK ADD  CONSTRAINT [FK_COMPONENT_SYMBOLS_CSET_DIAGRAM_TYPES] FOREIGN KEY([Diagram_Type_Xml])
REFERENCES [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS] CHECK CONSTRAINT [FK_COMPONENT_SYMBOLS_CSET_DIAGRAM_TYPES]
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS]  WITH CHECK ADD  CONSTRAINT [FK_COMPONENT_SYMBOLS_SYMBOL_GROUPS] FOREIGN KEY([Symbol_Group_Id])
REFERENCES [dbo].[SYMBOL_GROUPS] ([Id])
GO
ALTER TABLE [dbo].[COMPONENT_SYMBOLS] CHECK CONSTRAINT [FK_COMPONENT_SYMBOLS_SYMBOL_GROUPS]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS', @level2type=N'COLUMN',@level2name=N'Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS', @level2type=N'COLUMN',@level2name=N'Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Csetname Xml is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS', @level2type=N'COLUMN',@level2name=N'Diagram_Type_Xml'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The File Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS', @level2type=N'COLUMN',@level2name=N'File_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Component Family Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS', @level2type=N'COLUMN',@level2name=N'Component_Family_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Symbol Group Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS', @level2type=N'COLUMN',@level2name=N'Symbol_Group_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Abbreviation is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS', @level2type=N'COLUMN',@level2name=N'Abbreviation'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'COMPONENT_SYMBOLS'
GO
