USE [CSETWeb]
GO
/****** Object:  Table [dbo].[PROCUREMENT_DEPENDENCY]    Script Date: 11/14/2018 3:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROCUREMENT_DEPENDENCY](
	[Procurement_Id] [int] NOT NULL,
	[Dependencies_Id] [int] NOT NULL,
 CONSTRAINT [PK_PROCUREMENT_DEPENDENCY] PRIMARY KEY CLUSTERED 
(
	[Procurement_Id] ASC,
	[Dependencies_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (434, 440)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (435, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (437, 434)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (437, 440)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (438, 446)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (438, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (438, 450)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (439, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (440, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (441, 434)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (441, 440)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 454)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 455)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 456)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 457)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 458)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 459)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 460)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 461)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 462)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (442, 463)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (443, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (444, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (447, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (447, 443)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (447, 446)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (449, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (450, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (453, 433)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (453, 434)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (453, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 433)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 436)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 450)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 451)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 452)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 453)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 458)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 459)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 460)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 461)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 462)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 463)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 464)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 465)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 466)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (454, 467)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 433)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 435)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 436)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 450)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 451)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 452)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 453)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 458)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 459)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 460)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 461)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 462)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 463)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 464)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 465)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 466)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (455, 467)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 433)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 435)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 436)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 450)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 451)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 452)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 453)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 458)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 459)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 460)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 461)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 462)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 463)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 464)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 465)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 466)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (456, 467)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 433)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 436)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 450)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 451)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 452)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 453)
GO
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 458)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 459)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 460)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 461)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 462)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 463)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 464)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 465)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 466)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (457, 467)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 433)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 436)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 450)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 451)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 452)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 459)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 464)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 465)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 466)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (458, 467)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 433)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 436)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 450)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 451)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 452)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 453)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 454)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 455)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 456)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 457)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 458)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 464)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 465)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 466)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (459, 467)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (460, 434)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (460, 439)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (460, 440)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (460, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (460, 468)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (460, 469)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (461, 442)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (461, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (461, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (462, 438)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (462, 439)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (462, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (462, 468)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (462, 469)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (463, 444)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (463, 449)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (464, 436)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (466, 467)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (467, 468)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (467, 469)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (468, 439)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (468, 440)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (468, 441)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (468, 462)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (469, 439)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (469, 440)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (470, 474)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (471, 473)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (474, 470)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (475, 477)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (477, 470)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (477, 473)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (477, 474)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (478, 476)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (478, 479)
INSERT [dbo].[PROCUREMENT_DEPENDENCY] ([Procurement_Id], [Dependencies_Id]) VALUES (479, 473)
ALTER TABLE [dbo].[PROCUREMENT_DEPENDENCY]  WITH NOCHECK ADD  CONSTRAINT [FK_PROCUREMENT_DEPENDENCY_PROCUREMENT_LANGUAGE_DATA] FOREIGN KEY([Procurement_Id])
REFERENCES [dbo].[PROCUREMENT_LANGUAGE_DATA] ([Procurement_Id])
GO
ALTER TABLE [dbo].[PROCUREMENT_DEPENDENCY] CHECK CONSTRAINT [FK_PROCUREMENT_DEPENDENCY_PROCUREMENT_LANGUAGE_DATA]
GO
ALTER TABLE [dbo].[PROCUREMENT_DEPENDENCY]  WITH NOCHECK ADD  CONSTRAINT [FK_PROCUREMENT_DEPENDENCY_PROCUREMENT_LANGUAGE_DATA1] FOREIGN KEY([Dependencies_Id])
REFERENCES [dbo].[PROCUREMENT_LANGUAGE_DATA] ([Procurement_Id])
GO
ALTER TABLE [dbo].[PROCUREMENT_DEPENDENCY] CHECK CONSTRAINT [FK_PROCUREMENT_DEPENDENCY_PROCUREMENT_LANGUAGE_DATA1]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Procurement Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_DEPENDENCY', @level2type=N'COLUMN',@level2name=N'Procurement_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Dependencies Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_DEPENDENCY', @level2type=N'COLUMN',@level2name=N'Dependencies_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_DEPENDENCY'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_DEPENDENCY'
GO
