USE [CSETWeb]
GO
/****** Object:  Table [dbo].[CUSTOM_STANDARD_BASE_STANDARD]    Script Date: 6/28/2018 8:21:22 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOM_STANDARD_BASE_STANDARD](
	[Custom_Questionaire_Name] [varchar](50) NOT NULL,
	[Base_Standard] [varchar](50) NOT NULL,
	[Custom_Standard_Base_Standard_Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_CUSTOM_STANDARD_BASE_STANDARD] PRIMARY KEY CLUSTERED 
(
	[Custom_Standard_Base_Standard_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOM_STANDARD_BASE_STANDARD]  WITH NOCHECK ADD  CONSTRAINT [FK_CUSTOM_STANDARD_BASE_STANDARD_SETS] FOREIGN KEY([Base_Standard])
REFERENCES [dbo].[SETS] ([Set_Name])
GO
ALTER TABLE [dbo].[CUSTOM_STANDARD_BASE_STANDARD] CHECK CONSTRAINT [FK_CUSTOM_STANDARD_BASE_STANDARD_SETS]
GO
ALTER TABLE [dbo].[CUSTOM_STANDARD_BASE_STANDARD]  WITH NOCHECK ADD  CONSTRAINT [FK_CUSTOM_STANDARD_BASE_STANDARD_SETS1] FOREIGN KEY([Custom_Questionaire_Name])
REFERENCES [dbo].[SETS] ([Set_Name])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CUSTOM_STANDARD_BASE_STANDARD] CHECK CONSTRAINT [FK_CUSTOM_STANDARD_BASE_STANDARD_SETS1]
GO
