USE [CSETWeb]
GO
/****** Object:  Table [dbo].[SECTOR_INDUSTRY]    Script Date: 11/14/2018 3:57:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECTOR_INDUSTRY](
	[SectorId] [int] NOT NULL,
	[IndustryId] [int] NOT NULL,
	[IndustryName] [varchar](150) NOT NULL,
 CONSTRAINT [PK_SECTOR_INDUSTRY] PRIMARY KEY CLUSTERED 
(
	[SectorId] ASC,
	[IndustryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (1, 1, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (1, 78, N'Basic Chemicals')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (1, 79, N'Specialty Products')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (1, 80, N'Pharmaceutical Products')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (1, 81, N'Consumer Products')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (1, 82, N'Agricultural Products')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 2, N'Entertainment and Media')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 3, N'Gaming')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 4, N'Lodging')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 5, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 6, N'Outdoor Events')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 7, N'Public Assembly')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 8, N'Real Estate')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 9, N'Retail')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (2, 10, N'Sports Leagues')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (3, 11, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (3, 12, N'Telecommunications')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (3, 13, N'Wireless Communications Service Providers')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (3, 83, N'Broadcasting')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (3, 84, N'Cable')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (3, 85, N'Satellite')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (3, 86, N'Wireline')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (4, 14, N'Electrical Equipment, Appliance and Component Manufacturing')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (4, 15, N'Machinery Manufacturing')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (4, 16, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (4, 17, N'Primary Metal Manufacturing')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (4, 18, N'Transportation and Heavy Equipment Manufacturing')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (4, 87, N'Manufacturing')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (4, 88, N'Heavy Machinery Manufacturing')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (5, 19, N'Dams')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (5, 20, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (5, 21, N'Private Hydropower Facilities in the US')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (5, 89, N'Levees')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (5, 90, N'Navigation Locks')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (5, 91, N'Tailings and Waste Impoundments')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 22, N'Aircraft Industry')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 23, N'Ammunition')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 24, N'Combat Vehicle')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 25, N'Communications')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 26, N'Defense Contractors    ')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 27, N'Electrical Industry Commodities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 28, N'Electronics')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 29, N'Mechanical Industry Commodities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 30, N'Missile Industry')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 31, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 32, N'Research and Development Facilities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 33, N'Shipbuilding Industry')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 34, N'Space')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 35, N'Structural Industry Commodities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 36, N'Troop Support')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (6, 37, N'Weapons')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (7, 38, N'Emergency Management')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (7, 39, N'Emergency Medical Services')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (7, 40, N'Fire and Rescue Services')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (7, 41, N'Law Enforcement    ')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (7, 42, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (7, 43, N'Public Works')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (8, 44, N'Electric Power Generation, Transmission and Distribution      ')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (8, 45, N'Natural Gas      ')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (8, 46, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (8, 47, N'Petroleum Refineries')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (8, 92, N'Oil and Natural Gas')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (9, 48, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (9, 49, N'US Banks')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (9, 50, N'US Credit Unions')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (9, 93, N'Consumer Services')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (9, 94, N'Credit and Liquidity Products')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (9, 95, N'Investment Products')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (9, 96, N'Risk Transfer Products')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 51, N'Beverage Manufacturing Plants')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 52, N'Food Manufacturing Plants')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 53, N'Food Services')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 54, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 97, N'Supply')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 98, N'Processing, Packaging, and Production')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 99, N'Product Storage')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 100, N'Product Transportation')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 101, N'Product Distribution')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (10, 102, N'Supporting Facilities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (11, 55, N'Local Governments')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (11, 56, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (11, 57, N'State Governments')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (11, 58, N'Territorial Governments')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (11, 59, N'Tribal Governments')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (11, 103, N'Public Facilities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (11, 104, N'Non-Public Facilities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 60, N'Hospitals')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 61, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 62, N'Residential Care Facilities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 105, N'Direct Patient Care')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 106, N'Health IT')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 107, N'Health Plans and Payers')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 108, N'Fatality Management Services')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 109, N'Medical Materials')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (12, 110, N'Support Services')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 63, N'Information Technology')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 64, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 111, N'IT Production')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 112, N'DNS Services')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 113, N'Identity and Trust Support Management')
GO
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 114, N'Internet Content and Service Providers')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 115, N'Internet Routing and Connection')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (13, 116, N'Incident Management')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (14, 65, N'Operating Nuclear Power Plants')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (14, 66, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (14, 117, N'Fuel Cycle Facilities')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (14, 118, N'Nuclear Materials Transport')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (14, 119, N'Radioactive Waste')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (14, 120, N'Radioactive Materials')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 67, N'Aviation')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 68, N'Freight Rail')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 69, N'Highway (truck transportation)')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 70, N'Maritime')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 71, N'Mass Transit and Passenger Rail')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 72, N'Municipalities with Traffic Control Systems')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 73, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (15, 74, N'Pipelines (carries natural gas, hazardous liquids, and various chemicals.)')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (16, 75, N'Other')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (16, 76, N'Public Water Systems')
INSERT [dbo].[SECTOR_INDUSTRY] ([SectorId], [IndustryId], [IndustryName]) VALUES (16, 77, N'Publicly Owned Treatment Works')
ALTER TABLE [dbo].[SECTOR_INDUSTRY]  WITH CHECK ADD  CONSTRAINT [FK_SECTOR_INDUSTRY_SECTOR] FOREIGN KEY([SectorId])
REFERENCES [dbo].[SECTOR] ([SectorId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SECTOR_INDUSTRY] CHECK CONSTRAINT [FK_SECTOR_INDUSTRY_SECTOR]
GO
