USE [CSETWeb]
GO
/****** Object:  Table [dbo].[NERC_RISK_RANKING]    Script Date: 11/14/2018 3:57:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NERC_RISK_RANKING](
	[Question_id] [int] NULL,
	[Requirement_Id] [int] NULL,
	[Compliance_Risk_Rank] [int] NOT NULL,
	[Violation_Risk_Factor] [varchar](50) NOT NULL,
 CONSTRAINT [PK_NERC_RISK_RANKING] PRIMARY KEY CLUSTERED 
(
	[Compliance_Risk_Rank] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14905, 10, N'High')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3413, NULL, 20, N'High')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (43, NULL, 30, N'High')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (65, NULL, 31, N'High')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14925, 40, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (38, NULL, 41, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3434, NULL, 42, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3435, NULL, 43, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (61, NULL, 44, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1239, NULL, 45, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1240, NULL, 46, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1241, NULL, 47, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14921, 50, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1231, NULL, 51, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (360, NULL, 52, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (361, NULL, 53, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14922, 60, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1232, NULL, 61, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (442, NULL, 62, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (443, NULL, 63, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (444, NULL, 64, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1233, NULL, 65, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1234, NULL, 66, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14917, 70, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (291, NULL, 71, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3429, NULL, 72, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (253, NULL, 73, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (292, NULL, 74, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14923, 80, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1235, NULL, 81, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3432, NULL, 82, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (591, NULL, 83, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (593, NULL, 84, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (601, NULL, 85, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (603, NULL, 86, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14924, 90, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3433, NULL, 91, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (580, NULL, 92, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (41, NULL, 93, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (64, NULL, 94, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (788, NULL, 95, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (801, NULL, 96, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14916, 100, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (331, NULL, 101, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (332, NULL, 102, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (389, NULL, 103, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14907, 110, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3416, NULL, 111, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (81, NULL, 112, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3415, NULL, 113, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1, NULL, 114, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (24, NULL, 115, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (106, NULL, 116, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14909, 120, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3419, NULL, 121, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (112, NULL, 122, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14919, 130, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (492, NULL, 131, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (493, NULL, 132, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (495, NULL, 133, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14914, 140, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (470, NULL, 141, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3426, NULL, 142, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3427, NULL, 143, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3428, NULL, 144, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (199, NULL, 145, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (201, NULL, 146, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (204, NULL, 147, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (207, NULL, 148, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (212, NULL, 149, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (239, NULL, 150, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (248, NULL, 151, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (252, NULL, 152, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (472, NULL, 153, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14918, 154, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3430, NULL, 155, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (245, NULL, 156, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (474, NULL, 157, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (476, NULL, 158, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (487, NULL, 159, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (488, NULL, 160, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14935, 162, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (692, NULL, 163, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (566, NULL, 164, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (690, NULL, 165, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1894, NULL, 166, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14913, 170, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (170, NULL, 171, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3425, NULL, 172, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (171, NULL, 173, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (172, NULL, 174, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1203, NULL, 175, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14920, 180, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3431, NULL, 181, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14932, 190, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (29, NULL, 191, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (52, NULL, 192, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (69, NULL, 193, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (85, NULL, 194, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (86, NULL, 195, N'Medium')
GO
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (88, NULL, 196, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (534, NULL, 197, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14915, 200, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1205, NULL, 201, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (174, NULL, 202, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (177, NULL, 203, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (180, NULL, 204, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14933, 210, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (532, NULL, 211, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3442, NULL, 212, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (533, NULL, 213, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14929, 220, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (71, NULL, 221, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3439, NULL, 222, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (89, NULL, 223, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (113, NULL, 224, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (661, NULL, 225, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (662, NULL, 226, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (668, NULL, 227, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1250, NULL, 228, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14934, 230, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (124, NULL, 231, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (68, NULL, 232, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1444, NULL, 233, N'Medium')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14926, 240, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (72, NULL, 241, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3436, NULL, 242, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (115, NULL, 243, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (116, NULL, 244, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (615, NULL, 245, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1247, NULL, 246, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1248, NULL, 247, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14927, 250, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3437, NULL, 251, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (100, NULL, 252, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (103, NULL, 253, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1249, NULL, 254, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14906, 260, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3414, NULL, 261, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (75, NULL, 262, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14908, 270, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3417, NULL, 271, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3418, NULL, 272, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14928, 280, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3438, NULL, 281, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (102, NULL, 282, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (99, NULL, 283, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14936, 290, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1242, NULL, 291, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (35, NULL, 292, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (683, NULL, 293, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1957, NULL, 294, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1958, NULL, 295, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3206, NULL, 296, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14911, 300, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (33, NULL, 301, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3422, NULL, 302, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (57, NULL, 303, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1431, NULL, 304, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14930, 310, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3440, NULL, 311, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (92, NULL, 312, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14912, 320, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3423, NULL, 321, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3424, NULL, 322, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (190, NULL, 323, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1092, NULL, 324, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1202, NULL, 325, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1276, NULL, 326, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1568, NULL, 327, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14931, 330, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (94, NULL, 331, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3441, NULL, 332, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (98, NULL, 333, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (NULL, 14910, 340, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3420, NULL, 341, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (1190, NULL, 342, N'Lower')
INSERT [dbo].[NERC_RISK_RANKING] ([Question_id], [Requirement_Id], [Compliance_Risk_Rank], [Violation_Risk_Factor]) VALUES (3421, NULL, 343, N'Lower')
ALTER TABLE [dbo].[NERC_RISK_RANKING]  WITH NOCHECK ADD  CONSTRAINT [FK_NERC_RISK_RANKING_NEW_QUESTION] FOREIGN KEY([Question_id])
REFERENCES [dbo].[NEW_QUESTION] ([Question_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NERC_RISK_RANKING] CHECK CONSTRAINT [FK_NERC_RISK_RANKING_NEW_QUESTION]
GO
ALTER TABLE [dbo].[NERC_RISK_RANKING]  WITH NOCHECK ADD  CONSTRAINT [FK_NERC_RISK_RANKING_NEW_REQUIREMENT] FOREIGN KEY([Requirement_Id])
REFERENCES [dbo].[NEW_REQUIREMENT] ([Requirement_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NERC_RISK_RANKING] CHECK CONSTRAINT [FK_NERC_RISK_RANKING_NEW_REQUIREMENT]
GO
