USE [CSETWeb]
GO
/****** Object:  Table [dbo].[CUSTOM_QUESTIONAIRES]    Script Date: 6/28/2018 8:21:22 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOM_QUESTIONAIRES](
	[Custom_Questionaire_Name] [varchar](50) NOT NULL,
	[Description] [varchar](800) NULL,
	[Set_Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CUSTOM_QUESTIONAIRES] PRIMARY KEY CLUSTERED 
(
	[Custom_Questionaire_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
