USE [CSETWeb]
GO
/****** Object:  Table [dbo].[REPORT_OPTIONS_SELECTION]    Script Date: 11/14/2018 3:57:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPORT_OPTIONS_SELECTION](
	[Assessment_Id] [int] NOT NULL,
	[Report_Option_Id] [int] NOT NULL,
	[Is_Selected] [bit] NOT NULL,
 CONSTRAINT [PK_REPORT_OPTIONS_SELECTION] PRIMARY KEY CLUSTERED 
(
	[Assessment_Id] ASC,
	[Report_Option_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPORT_OPTIONS_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_OPTIONS_SELECTION_ASSESSMENTS] FOREIGN KEY([Assessment_Id])
REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[REPORT_OPTIONS_SELECTION] CHECK CONSTRAINT [FK_REPORT_OPTIONS_SELECTION_ASSESSMENTS]
GO
ALTER TABLE [dbo].[REPORT_OPTIONS_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_OPTIONS_SELECTION_REPORT_OPTIONS] FOREIGN KEY([Report_Option_Id])
REFERENCES [dbo].[REPORT_OPTIONS] ([Report_Option_Id])
GO
ALTER TABLE [dbo].[REPORT_OPTIONS_SELECTION] CHECK CONSTRAINT [FK_REPORT_OPTIONS_SELECTION_REPORT_OPTIONS]
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REPORT_OPTIONS_SELECTION'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REPORT_OPTIONS_SELECTION'
GO
