USE [CSETWeb]
GO
/****** Object:  Table [dbo].[PROCUREMENT_REFERENCES]    Script Date: 11/14/2018 3:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROCUREMENT_REFERENCES](
	[Procurement_Id] [int] NOT NULL,
	[Reference_Id] [int] NOT NULL,
 CONSTRAINT [PK_Procurement_References] PRIMARY KEY CLUSTERED 
(
	[Procurement_Id] ASC,
	[Reference_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (433, 2099)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (433, 2100)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (433, 2101)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (433, 2102)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (434, 2103)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (434, 2104)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (434, 2105)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (434, 2106)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (434, 2107)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (434, 2108)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (434, 2109)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (435, 2110)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (435, 2111)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (436, 2112)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (436, 2113)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (437, 2114)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (438, 2115)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (438, 2116)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (438, 2117)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (439, 2118)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (439, 2119)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (439, 2120)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (439, 2121)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (439, 2122)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (440, 2123)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (440, 2124)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (440, 2125)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (440, 2126)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (440, 2127)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (441, 2128)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (442, 2129)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (442, 2130)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (442, 2131)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (443, 2132)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (443, 2133)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (443, 2134)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (443, 2135)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (443, 2136)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2137)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2138)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2139)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2140)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2141)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2142)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2143)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (444, 2144)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2145)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2146)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2147)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2148)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2149)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2150)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2151)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (445, 2152)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (446, 2153)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (446, 2154)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (446, 2155)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (446, 2156)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (446, 2157)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (446, 2158)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (447, 2159)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (448, 2160)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (448, 2161)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (448, 2162)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (449, 2163)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (449, 2164)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (449, 2165)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (450, 2166)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (451, 2167)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (452, 2168)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (452, 2169)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (452, 2170)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (453, 2171)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (453, 2172)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2173)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2174)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2175)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2176)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2177)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2178)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2179)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2180)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2181)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2182)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2183)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (454, 2184)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2185)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2186)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2187)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2188)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2189)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2190)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2191)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2192)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2193)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2194)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2195)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (455, 2196)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2197)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2198)
GO
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2199)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2200)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2201)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2202)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2203)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2204)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2205)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2206)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (456, 2207)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2208)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2209)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2210)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2211)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2212)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2213)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2214)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2215)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2216)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (457, 2217)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (458, 2218)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (458, 2219)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (458, 2220)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (458, 2221)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (458, 2222)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (458, 2223)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (458, 2224)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2225)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2226)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2227)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2228)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2229)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2230)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2231)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (459, 2232)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2233)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2234)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2235)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2236)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2237)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2238)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2239)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2240)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2241)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2242)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2243)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (460, 2244)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (462, 2245)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (462, 2246)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (462, 2247)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (462, 2248)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (462, 2249)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (464, 2250)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (465, 2251)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (465, 2252)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (466, 2253)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (466, 2254)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (467, 2255)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (467, 2256)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (468, 2257)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (468, 2258)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (469, 2259)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (469, 2260)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (469, 2261)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2262)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2263)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2264)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2265)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2266)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2267)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2268)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (470, 2269)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (471, 2270)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (471, 2271)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (471, 2272)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (471, 2273)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (472, 2274)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (472, 2275)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (472, 2276)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (472, 2277)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (472, 2278)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (472, 2279)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (472, 2280)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2281)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2282)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2283)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2284)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2285)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2286)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2287)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2288)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2290)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2291)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (473, 2292)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (474, 2293)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (474, 2294)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (474, 2295)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (474, 2296)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (474, 2297)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (474, 2298)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (474, 2299)
GO
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (475, 2300)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (475, 2301)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (475, 2302)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (475, 2303)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (476, 2304)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (476, 2305)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (476, 2306)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (476, 2307)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (477, 2308)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (477, 2309)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (477, 2310)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (477, 2311)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (478, 2312)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (478, 2313)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (478, 2315)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (478, 2316)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (479, 2317)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (479, 2318)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (479, 2319)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (479, 2320)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (480, 2321)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (480, 2322)
INSERT [dbo].[PROCUREMENT_REFERENCES] ([Procurement_Id], [Reference_Id]) VALUES (480, 2323)
ALTER TABLE [dbo].[PROCUREMENT_REFERENCES]  WITH NOCHECK ADD  CONSTRAINT [FK_Procurement_References_Procurement_Language_Data] FOREIGN KEY([Procurement_Id])
REFERENCES [dbo].[PROCUREMENT_LANGUAGE_DATA] ([Procurement_Id])
GO
ALTER TABLE [dbo].[PROCUREMENT_REFERENCES] CHECK CONSTRAINT [FK_Procurement_References_Procurement_Language_Data]
GO
ALTER TABLE [dbo].[PROCUREMENT_REFERENCES]  WITH CHECK ADD  CONSTRAINT [FK_Procurement_References_References_Data] FOREIGN KEY([Reference_Id])
REFERENCES [dbo].[REFERENCES_DATA] ([Reference_Id])
GO
ALTER TABLE [dbo].[PROCUREMENT_REFERENCES] CHECK CONSTRAINT [FK_Procurement_References_References_Data]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Procurement Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_REFERENCES', @level2type=N'COLUMN',@level2name=N'Procurement_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Reference Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_REFERENCES', @level2type=N'COLUMN',@level2name=N'Reference_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_REFERENCES'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PROCUREMENT_REFERENCES'
GO
