USE [CSETWeb]
GO
/****** Object:  Table [dbo].[DEMOGRAPHICS]    Script Date: 11/14/2018 3:57:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEMOGRAPHICS](
	[Assessment_Id] [int] NOT NULL,
	[SectorId] [int] NULL,
	[IndustryId] [int] NULL,
	[Size] [varchar](50) NULL,
	[AssetValue] [varchar](50) NULL,
	[NeedsPrivacy] [bit] NOT NULL,
	[NeedsSupplyChain] [bit] NOT NULL,
	[NeedsICS] [bit] NOT NULL,
 CONSTRAINT [PK_DEMOGRAPHICS] PRIMARY KEY CLUSTERED 
(
	[Assessment_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] ADD  CONSTRAINT [DF_DEMOGRAPHICS_NeedsPrivacy]  DEFAULT ((0)) FOR [NeedsPrivacy]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] ADD  CONSTRAINT [DF_DEMOGRAPHICS_NeedsSupplyChain]  DEFAULT ((0)) FOR [NeedsSupplyChain]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] ADD  CONSTRAINT [DF_DEMOGRAPHICS_NeedsICS]  DEFAULT ((0)) FOR [NeedsICS]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS]  WITH CHECK ADD  CONSTRAINT [FK_DEMOGRAPHICS_ASSESSMENTS] FOREIGN KEY([Assessment_Id])
REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] CHECK CONSTRAINT [FK_DEMOGRAPHICS_ASSESSMENTS]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS]  WITH CHECK ADD  CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS_ASSET_VALUES] FOREIGN KEY([AssetValue])
REFERENCES [dbo].[DEMOGRAPHICS_ASSET_VALUES] ([AssetValue])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] CHECK CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS_ASSET_VALUES]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS]  WITH CHECK ADD  CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS_SIZE] FOREIGN KEY([Size])
REFERENCES [dbo].[DEMOGRAPHICS_SIZE] ([Size])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] CHECK CONSTRAINT [FK_DEMOGRAPHICS_DEMOGRAPHICS_SIZE]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS]  WITH CHECK ADD  CONSTRAINT [FK_DEMOGRAPHICS_SECTOR] FOREIGN KEY([SectorId])
REFERENCES [dbo].[SECTOR] ([SectorId])
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] CHECK CONSTRAINT [FK_DEMOGRAPHICS_SECTOR]
GO
ALTER TABLE [dbo].[DEMOGRAPHICS]  WITH CHECK ADD  CONSTRAINT [FK_DEMOGRAPHICS_SECTOR_INDUSTRY] FOREIGN KEY([IndustryId])
REFERENCES [dbo].[SECTOR_INDUSTRY] ([IndustryId])
GO
ALTER TABLE [dbo].[DEMOGRAPHICS] CHECK CONSTRAINT [FK_DEMOGRAPHICS_SECTOR_INDUSTRY]
GO
