USE [CSETWeb]
GO
/****** Object:  Table [dbo].[PARAMETER_ASSESSMENT]    Script Date: 11/14/2018 3:57:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARAMETER_ASSESSMENT](
	[Parameter_ID] [int] NOT NULL,
	[Assessment_ID] [int] NOT NULL,
	[Parameter_Value_Assessment] [varchar](2000) NOT NULL,
 CONSTRAINT [PK_ASSESSMENT_PARAMETERS] PRIMARY KEY CLUSTERED 
(
	[Parameter_ID] ASC,
	[Assessment_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PARAMETER_ASSESSMENT]  WITH CHECK ADD  CONSTRAINT [FK_ASSESSMENT_PARAMETERS_ASSESSMENTS] FOREIGN KEY([Assessment_ID])
REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PARAMETER_ASSESSMENT] CHECK CONSTRAINT [FK_ASSESSMENT_PARAMETERS_ASSESSMENTS]
GO
ALTER TABLE [dbo].[PARAMETER_ASSESSMENT]  WITH CHECK ADD  CONSTRAINT [FK_ASSESSMENT_PARAMETERS_PARAMETERS] FOREIGN KEY([Parameter_ID])
REFERENCES [dbo].[PARAMETERS] ([Parameter_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PARAMETER_ASSESSMENT] CHECK CONSTRAINT [FK_ASSESSMENT_PARAMETERS_PARAMETERS]
GO
