USE [CSETWeb]
GO
/****** Object:  Table [dbo].[REPORT_DETAIL_SECTION_SELECTION]    Script Date: 6/28/2018 8:21:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPORT_DETAIL_SECTION_SELECTION](
	[Assessment_Id] [int] NOT NULL,
	[Report_Section_Id] [int] NOT NULL,
	[Report_Section_Order] [int] NOT NULL,
	[Is_Selected] [bit] NOT NULL,
 CONSTRAINT [PK_REPORT_DETAIL_SECTION_SELECTION] PRIMARY KEY CLUSTERED 
(
	[Assessment_Id] ASC,
	[Report_Section_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPORT_DETAIL_SECTION_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_DETAIL_SECTION_SELECTION_ASSESSMENTS] FOREIGN KEY([Assessment_Id])
REFERENCES [dbo].[ASSESSMENTS] ([Assessment_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[REPORT_DETAIL_SECTION_SELECTION] CHECK CONSTRAINT [FK_REPORT_DETAIL_SECTION_SELECTION_ASSESSMENTS]
GO
ALTER TABLE [dbo].[REPORT_DETAIL_SECTION_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_DETAIL_SECTION_SELECTION_REPORT_DETAIL_SECTIONS] FOREIGN KEY([Report_Section_Id])
REFERENCES [dbo].[REPORT_DETAIL_SECTIONS] ([Report_Section_Id])
GO
ALTER TABLE [dbo].[REPORT_DETAIL_SECTION_SELECTION] CHECK CONSTRAINT [FK_REPORT_DETAIL_SECTION_SELECTION_REPORT_DETAIL_SECTIONS]
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REPORT_DETAIL_SECTION_SELECTION'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REPORT_DETAIL_SECTION_SELECTION'
GO
