USE [CSETWeb]
GO
/****** Object:  Table [dbo].[CUSTOM_BASE_STANDARDS]    Script Date: 6/28/2018 8:21:22 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOM_BASE_STANDARDS](
	[Custom_Questionaire_Name] [varchar](50) NOT NULL,
	[Base_Standard] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CUSTOM_BASE_STANDARDS_1] PRIMARY KEY CLUSTERED 
(
	[Custom_Questionaire_Name] ASC,
	[Base_Standard] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOM_BASE_STANDARDS]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOM_BASE_STANDARD_CUSTOM_QUESTIONAIRES] FOREIGN KEY([Custom_Questionaire_Name])
REFERENCES [dbo].[CUSTOM_QUESTIONAIRES] ([Custom_Questionaire_Name])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CUSTOM_BASE_STANDARDS] CHECK CONSTRAINT [FK_CUSTOM_BASE_STANDARD_CUSTOM_QUESTIONAIRES]
GO
