USE [CSETWeb]
GO
/****** Object:  Table [dbo].[NAVIGATION_STATE]    Script Date: 6/28/2018 8:21:24 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NAVIGATION_STATE](
	[Name] [varchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsError] [bit] NOT NULL,
	[IsVisited] [bit] NOT NULL,
	[IsAvailable] [bit] NOT NULL,
	[PercentCompletion] [float] NOT NULL,
 CONSTRAINT [PK_NAVIGATION_STATE] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NAVIGATION_STATE] ADD  CONSTRAINT [DF_NAVIGATION_STATE_IsAvailable]  DEFAULT ((1)) FOR [IsAvailable]
GO
