USE [CSETWeb]
GO
/****** Object:  Table [dbo].[SETS]    Script Date: 6/28/2018 8:21:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SETS](
	[Set_Name] [varchar](50) NOT NULL,
	[Full_Name] [varchar](250) NOT NULL,
	[Short_Name] [varchar](50) NOT NULL,
	[Is_Displayed] [bit] NOT NULL,
	[Is_Pass_Fail] [bit] NOT NULL,
	[Old_Std_Name] [varchar](50) NULL,
	[Set_Category_Id] [int] NULL,
	[Order_In_Category] [int] NULL,
	[Report_Order_Section_Number] [int] NULL,
	[Aggregation_Standard_Number] [int] NULL,
	[Is_Question] [bit] NOT NULL,
	[Is_Requirement] [bit] NOT NULL,
	[Order_Framework_Standards] [int] NOT NULL,
	[Standard_ToolTip] [varchar](800) NULL,
	[Is_Deprecated] [bit] NOT NULL,
	[Upgrade_Set_Name] [varchar](50) NULL,
	[Is_Custom] [bit] NOT NULL,
	[Date] [datetime] NULL,
	[IsEncryptedModule] [bit] NOT NULL,
	[IsEncryptedModuleOpen] [bit] NOT NULL,
 CONSTRAINT [PK_SETS] PRIMARY KEY CLUSTERED 
(
	[Set_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'APTA_Rail_V1', N'Defining a Security Zone Architecture for Rail Transit and Protecting Critical Zones', N'APTA Rail', 1, 0, NULL, 3, 2, 22, 37, 1, 1, 36, N'Securing Control and Communications Systems in Rail Transit Environments', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C2M2_V11', N'Cybersecurity Capability Maturity Model (C2M2)', N'C2M2', 1, 0, NULL, 10, 1, 22, 5, 1, 1, 29, N'The C2M2 focuses on the implementation and management of cybersecurity practices associated with the information technology (IT) and operations technology (OT) assets and the environments in which they operate.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_161', N'NIST SP800-161 Supply Chain Risk Management', N'SP800-161', 1, 0, NULL, 6, 1, 22, 31, 1, 1, 31, N'This publication provides guidance to federal agencies on identifying, assessing, and mitigating ICT supply chain risks at all levels of their organizations. The publication integrates ICT supply chain risk management (SCRM) into federal agency risk management activities by applying a multitiered, SCRM-specific approach, including guidance on assessing supply chain risk and applying mitigation activities.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_171', N'NIST Special Publication 800-171', N'SP800-171', 1, 0, NULL, 10, 4, 22, 32, 1, 1, 32, N'NIST SP800-171 is the standard that all DoD vendors, contractors, and suppliers will be required to be compliant with starting in September 2016.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_53_R3', N'NIST Special Publication 800-53 Rev 3', N'SP800-53 R3', 1, 0, N'NIST SP800-53 R3F', 4, 1, 22, 1, 1, 1, 4, N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government. The guidelines apply to all components of an information system that process, store, or transmit federal information.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_53_R3_App_I', N'NIST Special Publication 800-53 Rev 3 App I', N'SP800-53 R3 App I', 1, 0, N'NIST SP800-53 R3-AppI', 5, 1, 22, 2, 1, 1, 5, N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government. The guidelines apply to all components of an information system that process, store, or transmit federal information.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_53_R3_App_I_old', N'NIST Special Publication 800-53 Rev 3 App I', N'SP800-53 R3 App I', 0, 0, N'NIST SP800-53 R3-AppI', NULL, NULL, 22, 2, 0, 0, 5, N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government. The guidelines apply to all components of an information system that process, store, or transmit federal information.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_53_R3_old', N'NIST Special Publication 800-53 Rev 3', N'SP800-53 R3', 0, 0, N'NIST SP800-53 R3F', NULL, NULL, 22, 1, 0, 0, 4, N'This standard provides guidelines for selecting and specifying security controls for information systems supporting the executive agencies of the federal government. The guidelines apply to all components of an information system that process, store, or transmit federal information.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_53_R4', N'NIST Special Publication 800-53 Rev 4 (old)', N'SP800-53 R4 (old)', 1, 0, NULL, 4, 2, 22, 3, 1, 1, 1, N'This standard provides a catalog of security and privacy controls for federal information systems and organizations and a process for selecting controls to protect organizational operations, organizational assets, individuals, other organizations, and the Nation from a diverse set of threats including hostile cyber attacks, natural disasters, structural failures, and human errors.', 1, N'C800_53_R4_71', 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_53_R4_71', N'NIST Special Publication 800-53 Rev 4', N'SP800-53 R4', 1, 0, NULL, 4, 2, 22, 3, 1, 1, 1, N'This standard provides a catalog of security and privacy controls for federal information systems and organizations and a process for selecting controls to protect organizational operations, organizational assets, individuals, other organizations, and the Nation from a diverse set of threats including hostile cyber attacks, natural disasters, structural failures, and human errors.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_53_R4_App_J', N'NIST Special Publication 800-53 Rev 4 App J', N'SP800-53 R4 App J', 1, 0, NULL, 4, 3, 22, 4, 1, 1, 6, N'This standard from section Appendix J of SP800-53 Revision 4 includes controls that are customizable and implemented as part of an organization-wide process that manages information security and privacy risk.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_82', N'NIST Special Publication 800-82', N'SP800-82', 1, 1, N'NIST SP800-82', 5, 2, 22, 25, 1, 1, 2, N'This standard provides guidance for establishing secure industrial control systems (ICS). Many of these controls are based on SP800-53 with minor modifications.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'C800_82_V1', N'NIST Special Publication 800-82 Rev 1', N'SP800-82 V1', 1, 1, NULL, 5, 3, 22, 26, 1, 1, 7, N'This standard provides guidance for establishing secure industrial control systems (ICS). Many of these controls are based on SP800-53 with minor modifications.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Cag', N'Consensus Audit Guidelines (CAG)', N'CAG', 1, 1, N'CAG', 10, 2, 22, 6, 0, 1, 8, N'This standard contains 20 crucial controls designed to begin the process of establishing a prioritized baseline of information security measures and controls that can be applied across Federal enterprise environments.  The consensus effort that has produced this document has identified 20 specific technical security controls that are viewed as effective in blocking currently known high-priority attacks, as well as those attack types expected in the near future.', 1, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'CCI_V2', N'Control Correlation Identifier Specification V2 release 0.1', N'CCI', 1, 1, NULL, 10, 5, 22, 33, 1, 1, 35, N'A CCI is a decomposition of an IA Control or an IA industry best practice into single, actionable
statements. The CCI List is a collection of CCI Items, which express common IA practices or
controls.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Cfats', N'CFATS Risk-Based Performance Standards Guide 8-Cyber', N'CFATS', 1, 0, N'CFATS-RBPS', 1, 1, 22, 7, 1, 1, 9, N'The document presents the risk-based performance standards (RBPSs) for the security of the Nation''s chemical facilities using a tier approach. High-risk chemical facilities can use this document both to help them gain a sense of what types and combinations of security measures and processes are likely to satisfy a given RBPS for a facility at their tier level and to help them identify and select processes, measures, and activities that they may choose to implement to secure their facility.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Cnssi_1253', N'CNSSI No. 1253 Baseline', N'CNSSI 1253', 1, 0, NULL, 9, 3, 22, 8, 0, 1, 10, N'This Instruction serves as a companion document to NIST SP 800-53 for organizations that employ national security systems (NSS). It establishes the processes for categorizing NSS and the information they process and for appropriately selecting security controls for NSS from NIST SP 800-53. This Instruction applies to all components of NSS. For NSS, where differences between the NIST documentation and this Instruction occur, this Instruction is authoritative.', 1, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Cnssi_1253_V2', N'CNSSI No. 1253 Baseline V2 March 27, 2014', N'CNSSI 1253 V2', 1, 0, NULL, 9, 4, 22, 9, 0, 1, 13, N'This Instruction serves as a companion document to NIST SP 800-53 for organizations that employ national security systems (NSS). It establishes the processes for categorizing NSS and the information they process and for appropriately selecting security controls for NSS from NIST SP 800-53. This Instruction applies to all components of NSS. For NSS, where differences between the NIST documentation and this Instruction occur, this Instruction is authoritative.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Cnssi_Ics_Pit', N'CNSSI No. 1253 Industrial Control System (ICS) Overlay', N'CNSSI ICS', 1, 0, NULL, 9, 5, 22, 14, 0, 1, 11, N'This Instruction serves as a companion document to NIST SP 800-53 for organizations that employ national security systems (NSS). It establishes the processes for categorizing NSS and the information they process and for appropriately selecting security controls for NSS from NIST SP 800-53. This Instruction applies to all components of NSS. For NSS, where differences between the NIST documentation and this Instruction occur, this Instruction is authoritative.', 1, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Cnssi_Ics_V1', N'CNSSI No. 1253 (ICS) Overlay Version 1', N'CNSSI ICS V1', 1, 0, NULL, 9, 6, 22, 15, 0, 1, 12, N'This Instruction serves as a companion document to NIST SP 800-53 for organizations that employ national security systems (NSS). It establishes the processes for categorizing NSS and the information they process and for appropriately selecting security controls for NSS from NIST SP 800-53. This Instruction applies to all components of NSS. For NSS, where differences between the NIST documentation and this Instruction occur, this Instruction is authoritative.', 1, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Components', N'Network Components', N'Components', 0, 0, N'Components', NULL, NULL, 23, 10, 1, 0, 14, NULL, 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Cor_7', N'Catalog of Recommendations Rev 7', N'COR 7', 1, 0, N'CoR_V7', 10, 3, 22, 11, 0, 1, 3, N'This catalog presents a compilation of practices that various industry bodies have recommended to increase the security of control systems from both physical and cyber attacks. The recommendations in this catalog are grouped into 19 families, or categories, that have similar emphasis.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'CSC_V6', N'Critical Security Controls Version 6', N'CSC', 1, 0, NULL, 1, 10, 22, 34, 1, 1, 33, N'The CIS Controls are especially relevant because they are updated by cyber experts based on actual attack data pulled from a variety of public and private threat sources. Version 6 incorporates recommended changes from the cybersecurity community to reflect the latest technologies and threats. The new Controls include a new Control for "Email and Web Browser Protections," a deleted Control on "Secure Network Engineering," and a re-ordering to make "Controlled Use of Administration Privileges" higher in priority. This version also includes a new metrics companion guide.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Dod', N'DoD Instruction 8500.2', N'DoDI 8500.2', 1, 0, N'CS2SAT_DODI', 9, 2, 22, 12, 0, 1, 15, N'This instruction implements policy, assigns responsibilities, and prescribes procedures for applying integrated, layered protection of the Department of Defense (DoD) information systems and networks.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'DODI_8510', N'DoD Instruction 8510.01', N'DoDI 8510.01', 1, 0, NULL, 9, 1, 22, 13, 1, 1, 31, N'Risk Management Framework (RMF) for DoD Information Technology (IT)', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'FAA', N'FAA - Portable Electronic Devices used in Aviation – Operations', N'FAA PEDs', 1, 0, NULL, 3, 1, 22, 36, 1, 1, 34, N'A catalog of recommendations for securing portable electronic devices for commercial airline carriers', 0, NULL, 0, NULL, 1, 0)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'FAA_MAINT', N'FAA - Portable Electronic Devices used in Aviation – Maintenance', N'FAA Maintenance', 1, 1, NULL, 3, 3, 22, 37, 1, 1, 37, N'These questions are targeted at aircraft maintenance activities.', 0, NULL, 0, CAST(N'2017-01-09T00:00:00.000' AS DateTime), 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'HIPAA', N'Health Insurance Portability and Accountability Act Security Rule', N'HIPAA', 1, 0, NULL, 7, 1, 22, 35, 1, 1, 33, N'The HIPAA Privacy Rule establishes national standards to protect individuals'' medical records and other personal health information and applies to health plans, health care clearinghouses, and those health care providers that conduct certain health care transactions electronically', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'INGAA', N'INGAA Control Systems Cyber Security Guidelines for the Natural Gas Pipeline Industry', N'INGAA', 1, 0, NULL, 1, 2, 22, 16, 1, 1, 16, N'The purpose of this document is to provide guidance on addressing the control system cyber security plans section of the natural gas pipeline operators TSA required CSP. It is a set of guidelines to assist operators of natural gas pipelines in managing their control systems cyber security requirements.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Key', N'Key Questions', N'Key', 1, 0, N'Key Requirements', 11, 1, 22, 17, 1, 0, 17, N'The Key questions are a reduced subset of select questions from the DHS Catalog of Recommendations for standards developers.  This catalog presents a compilation of practices that various industry bodies have recommended to increase the security of control systems from both physical and cyber attacks. The recommendations in this catalog are grouped into 19 families, or categories, that have similar emphasis.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'NCSF_V1', N'Framework for Improving Critical Infrastructure Cybersecurity', N'Cybersecurity Framework', 1, 1, NULL, 13, 1, 22, 29, 0, 0, 18, N'This approach is a voluntary risk-based Cybersecurity Framework – a set of industry standards and best practices to help organizations manage cybersecurity risks. The resulting Framework, created through collaboration between government and the private sector, uses a common language to address and manage cybersecurity risk in a cost-effective way based on business needs without placing additional regulatory requirements on businesses.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'NEI_0809', N'NEI 08-09 Cyber Security Plan for Nuclear Power Reactors', N'NEI 08-09', 1, 1, NULL, 8, 1, 22, 18, 1, 1, 19, N'This assessment standard was developed to assist nuclear plant licensees in constructing and implementing their Cyber Security Plan license submittal as required by 10 CFR 73.54.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Nerc_Cip_R3', N'NERC CIP-002 through CIP-009 Rev 3 ', N'NERC Rev 3', 1, 1, N'NERC-CIP', 2, 1, 22, 19, 1, 1, 20, N'This NERC-CIP standard was developed to assist industry stakeholders in electric power systems in North America with constructing and implementing their Cyber Security Plan.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Nerc_Cip_R4', N'NERC CIP-002 through CIP-009 Rev 4', N'NERC Rev 4', 1, 1, NULL, 2, 2, 22, 20, 1, 1, 21, N'This NERC-CIP standard was developed to assist industry stakeholders with bulk electric power systems in North America with constructing and implementing their Cyber Security Plan.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Nerc_Cip_R5', N'NERC CIP-002 through CIP-011 Rev 5', N'NERC Rev 5', 1, 1, NULL, 2, 3, 22, 21, 1, 1, 22, N'This NERC-CIP standard was developed to assist industry stakeholders with bulk electric power systems in North America with constructing and implementing their Cyber Security Plan.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'NISTIR_7628', N'NISTIR 7628 Guidelines for Smart Grid Cyber Security: Vol. 1', N'NISTIR 7628', 1, 0, NULL, 2, 4, 22, 22, 1, 1, 23, N'These set of guidelines are intended primarily for individuals and organizations responsible for addressing cyber security for Smart Grid systems and the constituent subsystems of hardware and software components.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'NISTIR_7628_R1', N'NISTIR 7628 Guidelines for Smart Grid Cyber Security: Vol. 1 Rev 1', N'NISTIR 7628 R1', 1, 1, NULL, 2, 5, 22, 23, 1, 1, 30, N'Guidelines for Smart Grid Cybersecurity, presents an analytical framework that organizations can use to develop effective cybersecurity strategies tailored to their particular combinations of smart grid-related characteristics, risks, and vulnerabilities. Organizations in the diverse community of smart grid stakeholders—from utilities to providers of energy management services to manufacturers of electric vehicles and charging stations—can use the methods and supporting information presented in this report as guidance for assessing risk and identifying and applying appropriate security requirements. This approach recognizes that the electric grid is changing from a relatively closed system to a complex, highly interconnected environment.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Nrc_571', N'NRC Regulatory Guide 5.71', N'NRC 5.71', 1, 1, N'NRC RG 5-71', 8, 2, 22, 24, 1, 1, 24, N'This regulatory guide 5.71 applies to operating nuclear reactors licensed in accordance with 10 CFR Part 50, and 10 CFR Part 52. Licensees and applicants should consider this guidance in preparing an application for a combined operating license under 10 CFR Part 52. Licensees and applicants bear the sole responsibility for assessing and managing the potential for adverse effects on safety, security, and emergency preparedness (SSEP) so as to provide high assurance that critical functions are adequately protected from cyber attacks.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'PCIDSS', N'Payment Card Industry (PCI)
Data Security Standard', N'PCIDSS', 1, 1, NULL, 10, 6, 22, 38, 1, 1, 38, N'This document, PCI Data Security Standard Requirements and Security Assessment Procedures, combines the 12 PCI DSS requirements and corresponding testing procedures into a security assessment tool. It is designed for use during PCI DSS compliance assessments as part of an entity’s validation process.', 0, NULL, 0, CAST(N'2018-05-21T00:00:00.000' AS DateTime), 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'SP800-82 V2', N'NIST Special Publication 800-82 Rev 2', N'SP800-82 V2', 1, 1, NULL, 5, 4, 22, 30, 1, 1, 28, N'This standard provides guidance for establishing secure industrial control systems (ICS). Many of these controls are based on SP800-53 with minor modifications.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Standards', N'All Questions From Standards', N'All Standards', 0, 0, NULL, NULL, NULL, NULL, 0, 0, 0, 25, NULL, 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Tsa', N'TSA Pipeline Security Guidelines April 2011', N'TSA', 1, 0, NULL, 1, 3, 22, 27, 1, 1, 26, N'These guidelines are applicable to natural gas and hazardous liquid transmission pipelines, natural gas distribution pipelines, and to liquefied natural gas facility operators. Additionally, they apply to pipeline systems that transport materials categorized as toxic inhalation hazards (TIH). These guidelines provide agency recommendations for pipeline industry security practices.', 0, NULL, 0, NULL, 0, 1)
INSERT [dbo].[SETS] ([Set_Name], [Full_Name], [Short_Name], [Is_Displayed], [Is_Pass_Fail], [Old_Std_Name], [Set_Category_Id], [Order_In_Category], [Report_Order_Section_Number], [Aggregation_Standard_Number], [Is_Question], [Is_Requirement], [Order_Framework_Standards], [Standard_ToolTip], [Is_Deprecated], [Upgrade_Set_Name], [Is_Custom], [Date], [IsEncryptedModule], [IsEncryptedModuleOpen]) VALUES (N'Universal', N'Universal Questions', N'Universal', 1, 0, NULL, 11, 2, 22, 28, 1, 0, 27, N'This catalog presents a compilation of practices that various industry bodies have recommended to increase the security of control systems from both physical and cyber attacks. The recommendations in this catalog are grouped into 19 families, or categories, that have similar emphasis.', 0, NULL, 0, NULL, 0, 1)
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_Short_Name]  DEFAULT ('NO SHORT NAME') FOR [Short_Name]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_Is_Displayed]  DEFAULT ((1)) FOR [Is_Displayed]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_Is_Pass_Fail]  DEFAULT ((0)) FOR [Is_Pass_Fail]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_Is_Question]  DEFAULT ((0)) FOR [Is_Question]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_Is_Requirement]  DEFAULT ((0)) FOR [Is_Requirement]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_Is_Deprecated]  DEFAULT ((0)) FOR [Is_Deprecated]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_Is_Custom]  DEFAULT ((0)) FOR [Is_Custom]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_IsEncryptedModuleClosed]  DEFAULT ((0)) FOR [IsEncryptedModule]
GO
ALTER TABLE [dbo].[SETS] ADD  CONSTRAINT [DF_SETS_IsEncryptedModuleOpen]  DEFAULT ((1)) FOR [IsEncryptedModuleOpen]
GO
ALTER TABLE [dbo].[SETS]  WITH CHECK ADD  CONSTRAINT [FK_SETS_Sets_Category] FOREIGN KEY([Set_Category_Id])
REFERENCES [dbo].[SETS_CATEGORY] ([Set_Category_Id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[SETS] CHECK CONSTRAINT [FK_SETS_Sets_Category]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Set Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SETS', @level2type=N'COLUMN',@level2name=N'Set_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Full Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SETS', @level2type=N'COLUMN',@level2name=N'Full_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Is Pass Fail is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SETS', @level2type=N'COLUMN',@level2name=N'Is_Pass_Fail'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Old Std Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SETS', @level2type=N'COLUMN',@level2name=N'Old_Std_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SETS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SETS'
GO
