USE [CSETWeb]
GO
/****** Object:  Table [dbo].[USER_DETAIL_INFORMATION]    Script Date: 6/28/2018 8:21:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_DETAIL_INFORMATION](
	[Id] [uniqueidentifier] NOT NULL,
	[CellPhone] [varchar](150) NULL,
	[FirstName] [varchar](150) NOT NULL,
	[LastName] [varchar](150) NOT NULL,
	[HomePhone] [varchar](150) NULL,
	[OfficePhone] [varchar](150) NULL,
	[ImagePath] [varchar](150) NULL,
	[JobTitle] [varchar](150) NULL,
	[Organization] [varchar](150) NULL,
	[PrimaryEmail] [varchar](150) NOT NULL,
	[SecondaryEmail] [varchar](150) NULL,
 CONSTRAINT [PK_USER_DETAIL_INFORMATION] PRIMARY KEY CLUSTERED 
(
	[PrimaryEmail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_DETAIL_INFORMATION]  WITH CHECK ADD  CONSTRAINT [FK_USER_DETAIL_INFORMATION_USERS] FOREIGN KEY([PrimaryEmail])
REFERENCES [dbo].[USERS] ([PrimaryEmail])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_DETAIL_INFORMATION] CHECK CONSTRAINT [FK_USER_DETAIL_INFORMATION_USERS]
GO
