USE [CSETWeb]
GO
/****** Object:  Table [dbo].[IMPORTANCE]    Script Date: 11/14/2018 3:57:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPORTANCE](
	[Importance_Id] [int] IDENTITY(1,1) NOT NULL,
	[Value] [varchar](50) NULL,
 CONSTRAINT [PK_IMPORTANCE_1] PRIMARY KEY CLUSTERED 
(
	[Importance_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[IMPORTANCE] ON 

INSERT [dbo].[IMPORTANCE] ([Importance_Id], [Value]) VALUES (1, N'Low')
INSERT [dbo].[IMPORTANCE] ([Importance_Id], [Value]) VALUES (2, N'Medium')
INSERT [dbo].[IMPORTANCE] ([Importance_Id], [Value]) VALUES (3, N'High')
SET IDENTITY_INSERT [dbo].[IMPORTANCE] OFF
