USE [CSETWeb]
GO
/****** Object:  Table [dbo].[NIST_SAL_QUESTION_ANSWERS]    Script Date: 11/14/2018 3:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS](
	[Assessment_Id] [int] NOT NULL,
	[Question_Id] [int] NOT NULL,
	[Question_Answer] [varchar](50) NOT NULL,
 CONSTRAINT [PK_NIST_SAL_QUESTION_ANSWERS] PRIMARY KEY CLUSTERED 
(
	[Assessment_Id] ASC,
	[Question_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS] ADD  CONSTRAINT [DF_NIST_SAL_QUESTION_ANSWERS_Question_Answer]  DEFAULT ('No') FOR [Question_Answer]
GO
ALTER TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS]  WITH CHECK ADD  CONSTRAINT [FK_NIST_SAL_QUESTION_ANSWERS_NIST_SAL_QUESTIONS] FOREIGN KEY([Question_Id])
REFERENCES [dbo].[NIST_SAL_QUESTIONS] ([Question_Id])
GO
ALTER TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS] CHECK CONSTRAINT [FK_NIST_SAL_QUESTION_ANSWERS_NIST_SAL_QUESTIONS]
GO
ALTER TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS]  WITH CHECK ADD  CONSTRAINT [FK_NIST_SAL_QUESTION_ANSWERS_STANDARD_SELECTION] FOREIGN KEY([Assessment_Id])
REFERENCES [dbo].[STANDARD_SELECTION] ([Assessment_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS] CHECK CONSTRAINT [FK_NIST_SAL_QUESTION_ANSWERS_STANDARD_SELECTION]
GO
ALTER TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS]  WITH CHECK ADD  CONSTRAINT [CK_NIST_SAL_QUESTION_ANSWERS] CHECK  (([Question_Answer]='No' OR [Question_Answer]='Yes'))
GO
ALTER TABLE [dbo].[NIST_SAL_QUESTION_ANSWERS] CHECK CONSTRAINT [CK_NIST_SAL_QUESTION_ANSWERS]
GO
