USE [CSETWeb]
GO
/****** Object:  Table [dbo].[PARAMETER_VALUES]    Script Date: 11/14/2018 3:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARAMETER_VALUES](
	[Answer_Id] [int] NOT NULL,
	[Parameter_Id] [int] NOT NULL,
	[Parameter_Value] [varchar](2000) NOT NULL,
	[Parameter_Is_Default] [bit] NOT NULL,
 CONSTRAINT [PK_PARAMETER_VALUES] PRIMARY KEY CLUSTERED 
(
	[Answer_Id] ASC,
	[Parameter_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PARAMETER_VALUES] ADD  CONSTRAINT [DF_PARAMETER_VALUES_Parameter_Is_Default_1]  DEFAULT ((0)) FOR [Parameter_Is_Default]
GO
ALTER TABLE [dbo].[PARAMETER_VALUES]  WITH CHECK ADD  CONSTRAINT [FK_PARAMETER_VALUES_ANSWER] FOREIGN KEY([Answer_Id])
REFERENCES [dbo].[ANSWER] ([Answer_Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PARAMETER_VALUES] CHECK CONSTRAINT [FK_PARAMETER_VALUES_ANSWER]
GO
ALTER TABLE [dbo].[PARAMETER_VALUES]  WITH CHECK ADD  CONSTRAINT [FK_PARAMETER_VALUES_PARAMETERS] FOREIGN KEY([Parameter_Id])
REFERENCES [dbo].[PARAMETERS] ([Parameter_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PARAMETER_VALUES] CHECK CONSTRAINT [FK_PARAMETER_VALUES_PARAMETERS]
GO
