USE [CSETWeb]
GO
/****** Object:  Table [dbo].[DIAGRAM_TYPES_XML]    Script Date: 11/14/2018 3:57:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIAGRAM_TYPES_XML](
	[Diagram_Type_XML] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CSET_DIAGRAM_TYPES] PRIMARY KEY CLUSTERED 
(
	[Diagram_Type_XML] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Active Directory')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Application Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Audio Switch')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Building Automation Management Systems')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Clock')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Configuration Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Connector')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'CT Scanner')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Database Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'DCS')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Dispatch Console')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'DNS Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Door Access Door Control Unit')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'ECG')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'EEG')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Electronic Security System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Ellipse')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Emergency Medical Service Communications Hardware')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'EMG')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Endoscopy System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Engineering Workstation')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Ethernet Backhaul')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Firewall')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Front End Processor')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Handheld Wireless Device')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Hexagon')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Historian')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'HMI')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Hub')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'IDS')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'IED')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Imaging Modalities and Equipment')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Imaging Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Infant Protection Remote Display Unit')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Infusion Pump')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Interactive Television System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'IP Camera')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'IP Phone')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'IPS')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Linear Partical Accelerator')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Link Encryption')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Magnetic Resonance Imaging')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Mail Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Master Site')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Medical Gas System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Microwave Backhaul')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Modem')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'MTU')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Multi Protocol Label Switching')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Multiple Services Component')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Network Printer')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Network Scanner And Copier')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Octagon')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Optical Ring System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Partner')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'PC')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Pentagon')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Physiological Monitoring System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'PLC')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Plus')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Power Over Ethernet')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Public Kiosk')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Radio Site')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Real Time Location System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Rectangle')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Relay Panel')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Remote Access Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'RFID Transmitter')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'RightTriangle')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'RoundedRectangle')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Router')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'RTU')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Safety Instrumented System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Security Information And Event Management System')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Serial Radio')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Serial Switch')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Star')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Subscriber Radio')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Switch')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'T1 Backhaul')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'TDM Backhaul')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Terminal Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Triangle')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Ultrasound')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Unidirectional Device')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Uninterruptible Power Supply')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Unknown')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Urodynamic Diagnostic Equipment')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Vendor')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Video Teleconferencing Equipment')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Virtual Machine Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'VLAN Router')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'VLAN Switch')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'VPN')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Web')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Web Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Windows Update Server')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Wireless Modem')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Wireless Network')
GO
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'Wireless Router')
INSERT [dbo].[DIAGRAM_TYPES_XML] ([Diagram_Type_XML]) VALUES (N'XRay Generator')
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DIAGRAM_TYPES_XML'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DIAGRAM_TYPES_XML'
GO
