USE [CSETWeb]
GO
/****** Object:  Table [dbo].[REF_LIBRARY_PATH]    Script Date: 11/14/2018 3:57:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REF_LIBRARY_PATH](
	[Lib_Path_Id] [numeric](38, 0) NOT NULL,
	[Parent_Path_Id] [numeric](38, 0) NULL,
	[Path_Name] [varchar](60) NULL,
 CONSTRAINT [REF_LIBRARY_PATH_PK] PRIMARY KEY CLUSTERED 
(
	[Lib_Path_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(1 AS Numeric(38, 0)), NULL, N'Guidance')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(2 AS Numeric(38, 0)), NULL, N'Reports')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(3 AS Numeric(38, 0)), NULL, N'Templates')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(4 AS Numeric(38, 0)), NULL, N'Standards')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(5 AS Numeric(38, 0)), NULL, N'Publisher')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(6 AS Numeric(38, 0)), NULL, N'Publication Year')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(8 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Access Control')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(10 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Assets')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(11 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Access Control')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(13 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Communications')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(14 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Auditing & Assessment')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(15 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Access Control')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(17 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Case Study')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(20 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Communications')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(22 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Categorization')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(23 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Cryptography & Encryption')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(29 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Incidents')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(32 AS Numeric(38, 0)), CAST(353 AS Numeric(38, 0)), N'Architecture')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(35 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Control System Security')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(40 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Chemical Industry')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(42 AS Numeric(38, 0)), CAST(35 AS Numeric(38, 0)), N'Cyber Exercise')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(43 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Processes & Procedures')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(46 AS Numeric(38, 0)), CAST(353 AS Numeric(38, 0)), N'Intellectual Property Incident')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(48 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Emergency Communications')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(50 AS Numeric(38, 0)), CAST(35 AS Numeric(38, 0)), N'Defense-in-Depth')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(53 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Security Plans')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(54 AS Numeric(38, 0)), CAST(53 AS Numeric(38, 0)), N'Nuclear')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(55 AS Numeric(38, 0)), CAST(35 AS Numeric(38, 0)), N'Model')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(56 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Firewalls')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(58 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Contingency Planning')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(61 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Servers')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(62 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Cryptography & Encryption')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(63 AS Numeric(38, 0)), CAST(15 AS Numeric(38, 0)), N'Physical Security')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(65 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Governing for Enterprise Security (GES)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(66 AS Numeric(38, 0)), CAST(91 AS Numeric(38, 0)), N'Strategies')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(69 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Department of Defense')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(71 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'InfoSec')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(72 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Electric Power Industry')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(88 AS Numeric(38, 0)), CAST(353 AS Numeric(38, 0)), N'Internet Protocol')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(91 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Infuse')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(92 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'General Control System Standards')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(93 AS Numeric(38, 0)), CAST(103 AS Numeric(38, 0)), N'Internet Protocol')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(94 AS Numeric(38, 0)), CAST(29 AS Numeric(38, 0)), N'Disaster Recovery')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(95 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Insider Threat')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(97 AS Numeric(38, 0)), CAST(29 AS Numeric(38, 0)), N'Response')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(98 AS Numeric(38, 0)), CAST(353 AS Numeric(38, 0)), N'Management')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(101 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Information Technology Specific Standards')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(102 AS Numeric(38, 0)), CAST(353 AS Numeric(38, 0)), N'Sanitation')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(103 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Malware Threats')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(104 AS Numeric(38, 0)), CAST(71 AS Numeric(38, 0)), N'Concepts')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(106 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'InfoSec')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(107 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Microsoft')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(109 AS Numeric(38, 0)), CAST(353 AS Numeric(38, 0)), N'Security Controls')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(111 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Nuclear Reactors')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(113 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'National Strategy')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(119 AS Numeric(38, 0)), CAST(71 AS Numeric(38, 0)), N'Strategies')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(120 AS Numeric(38, 0)), CAST(103 AS Numeric(38, 0)), N'Recovery')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(121 AS Numeric(38, 0)), CAST(43 AS Numeric(38, 0)), N'Risk Management')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(122 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Program Review')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(125 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Service Providers')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(126 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Test & Evaluation')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(127 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Risk Management')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(128 AS Numeric(38, 0)), CAST(127 AS Numeric(38, 0)), N'Social Networks')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(129 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Sector-Specific Plans')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(131 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Other Referenced Documents')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(132 AS Numeric(38, 0)), CAST(3 AS Numeric(38, 0)), N'Wireless')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(134 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'Security Plans')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(135 AS Numeric(38, 0)), CAST(2 AS Numeric(38, 0)), N'SQUARE')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(137 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Privacy')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(138 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Processes & Procedures')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(139 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Requirement Mode Only Standards')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(140 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Resource Identification')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(141 AS Numeric(38, 0)), CAST(144 AS Numeric(38, 0)), N'NERC CIP-002 through CIP-009 Rev 3')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(142 AS Numeric(38, 0)), CAST(144 AS Numeric(38, 0)), N'NERC CIP-002 through CIP-009 Rev 4')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(143 AS Numeric(38, 0)), CAST(106 AS Numeric(38, 0)), N'Security Controls')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(144 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Sector Specific Standards')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(145 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Test & Evaluation')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(146 AS Numeric(38, 0)), CAST(144 AS Numeric(38, 0)), N'NERC CIP-002 through CIP-010 Std 5')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(316 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Access Control')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(319 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Acquisition')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(322 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Auditing & Assessment')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(325 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Categorization')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(328 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Cloud Computing')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(331 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Communications')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(334 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Configuration Management')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(337 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Control System Security')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(340 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Cryptography & Encryption')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(343 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Devices')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(346 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Electric Power Industry')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(349 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Firewalls')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(351 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Incidents')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(353 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Information Security')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(355 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'IT Products')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(357 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Microsoft')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(359 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'National Checklist Program')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(361 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Network Security')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(363 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Patch Management')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(365 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Personal Identity Verification')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(367 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Personally Identifiable Information (PII)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(369 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Personnel Security')
GO
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(371 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Processes & Procedures')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(373 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Reporting')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(375 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Risk Management')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(377 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Security Content Automation Protocol (SCAP)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(379 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Security Controls')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(381 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Security Plans')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(383 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Service Providers')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(385 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'System Controls')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(387 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Telework')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(389 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Test & Evaluation')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(391 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Training')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(393 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Web Services')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(395 AS Numeric(38, 0)), CAST(1 AS Numeric(38, 0)), N'Wireless')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(420 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2016')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(425 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2015')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(430 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2014')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(435 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2013')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(440 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2012')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(445 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2011')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(450 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2010')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(455 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2009')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(460 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2008')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(465 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2007')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(470 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2006')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(475 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'2000-2005')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(480 AS Numeric(38, 0)), CAST(6 AS Numeric(38, 0)), N'1990-1999')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(505 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'Carnegie Mellon')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(506 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'Department of Defense (DOD)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(507 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'Department of Health and Human Services (HHS)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(508 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'Department of Homeland Security (DHS)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(509 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'National Institute of Standards and Technology (NIST)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(510 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'National Security Agency (NSA)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(511 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'North American Electric Reliability Corporation (NERC)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(512 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'Nuclear Regulatory Commission (NRC)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(513 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'Other Publishers')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(514 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'SANS')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(515 AS Numeric(38, 0)), CAST(5 AS Numeric(38, 0)), N'US Government Other')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(516 AS Numeric(38, 0)), CAST(4 AS Numeric(38, 0)), N'Credit Card Industry Standards')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(517 AS Numeric(38, 0)), CAST(516 AS Numeric(38, 0)), N'PCI DSS Payment Card Industry (PCI) Data Security Standard')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(518 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-002-5.1a BES Cyber System Categorization
')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(519 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-003-6 Security Management Controls')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(520 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-004-6 Personnel & Training')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(521 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-005-5 Electronic Security Perimeter(s)')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(522 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-006-5 Physical Security of BES Cyber Systems')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(523 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-006-6 Physical Security of BES Cyber Systems')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(524 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-007-6 Systems Security Management')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(525 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-008-5 Incident Reporting and Response Planning')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(526 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-009-6 Recovery Plans for BES Cyber Systems')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(527 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-010-2 Configuration Change & Vulnerability
 Assessments')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(528 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-011-2 Information Protection')
INSERT [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id], [Parent_Path_Id], [Path_Name]) VALUES (CAST(529 AS Numeric(38, 0)), CAST(72 AS Numeric(38, 0)), N'CIP-014-2 Physical Security')
ALTER TABLE [dbo].[REF_LIBRARY_PATH]  WITH CHECK ADD  CONSTRAINT [FK_REF_LIBRARY_PATH_REF_LIBRARY_PATH] FOREIGN KEY([Parent_Path_Id])
REFERENCES [dbo].[REF_LIBRARY_PATH] ([Lib_Path_Id])
GO
ALTER TABLE [dbo].[REF_LIBRARY_PATH] CHECK CONSTRAINT [FK_REF_LIBRARY_PATH_REF_LIBRARY_PATH]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Lib Path Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REF_LIBRARY_PATH', @level2type=N'COLUMN',@level2name=N'Lib_Path_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Parent Path Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REF_LIBRARY_PATH', @level2type=N'COLUMN',@level2name=N'Parent_Path_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Path Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REF_LIBRARY_PATH', @level2type=N'COLUMN',@level2name=N'Path_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REF_LIBRARY_PATH'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Ref Library Path' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REF_LIBRARY_PATH'
GO
