USE [CSETWeb]
GO
/****** Object:  Table [dbo].[VISIO_MAPPING]    Script Date: 6/28/2018 8:21:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VISIO_MAPPING](
	[Specific_Type] [varchar](100) NOT NULL,
	[Stencil_Name] [varchar](200) NOT NULL,
 CONSTRAINT [PK_VISIO_MAPPING] PRIMARY KEY CLUSTERED 
(
	[Specific_Type] ASC,
	[Stencil_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Active Directory', N'Active Directory')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Application Server', N'Application server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Application Server', N'Application Server.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Audio Switch', N'Audio Switch')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Audio Switch', N'Audio Switch.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Building Automation Management Systems', N'Building Automation Management Systems')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Clock', N'Clock')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Clock', N'Clock.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Configuration Server', N'Configuration Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Connector', N'Connector')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Connector', N'Connector.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Cross', N'Cross')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'CT Scanner', N'CT Scanner')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'CT Scanner', N'CT Scanner.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Database Server', N'Database')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Database Server', N'Database Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Database Server', N'Database Server.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Database Server', N'DB Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'DCS', N'DCS')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'DCS', N'DCS.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Dispatch Console', N'Dispatch Console')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Dispatch Console', N'Dispatch Console.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'DNS Server', N'DNS Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'DNS Server', N'Domain Name System Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Door Access Door Control Unit', N'Door Access Door Control Unit')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Door Access Door Control Unit', N'Door Access Door Control Unit.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'ECG', N'ECG')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'ECG', N'ECG.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'EEG', N'EEG')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'EEG', N'EEG.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Electronic Security System', N'Electronic Security System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Ellipse', N'Circle')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Ellipse', N'Ellipse')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Emergency Medical Service Communications Hardware', N'Emergency Medical Service Communications Hardware')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'EMG', N'electromyograph')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'EMG', N'EMG')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'EMG', N'EMG.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Endoscopy System', N'Endoscopy System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Endoscopy System', N'Endoscopy System.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Engineering Workstation', N'Engineering Workstation')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Engineering Workstation', N'Engineering Workstation.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Ethernet Backhaul', N'Ethernet Backhaul')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Ethernet Backhaul', N'Ethernet Backhaul.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Firewall', N'Firewall')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Firewall', N'Firewall.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Front End Processor', N'Front End Processor')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Front End Processor', N'Front End Processor.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Handheld Wireless Device', N'Cell Phone')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Handheld Wireless Device', N'Handheld Wireless Device')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Handheld Wireless Device', N'Handheld Wireless Device.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Handheld Wireless Device', N'Smart Phone')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Hexagon', N'Hexagon')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Historian', N'Historian')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'HMI', N'HMI')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'HMI', N'HMI.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Hub', N'Hub')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Hub', N'Hub.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IDS', N'IDS')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IDS', N'IDS.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IED', N'IED')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IED', N'IED.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Imaging Modalities and Equipment', N'Imaging Modalities and Equipment')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Imaging Server', N'Imaging Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Infant Protection Remote Display Unit', N'Infant Protection Remote Display Unit')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Infant Protection Remote Display Unit', N'Infant Protection Remote Display Unit.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Infusion Pump', N'Infusion Pump')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Infusion Pump', N'Infusion Pump.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Interactive Television System', N'Interactive Television System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IP Camera', N'IP Camera')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IP Camera', N'Video Camera')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IP Phone', N'IP Phone')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IP Phone', N'Telephone')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IP Phone', N'Video Phone')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IPS', N'IPS')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'IPS', N'IPS.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Linear Partical Accelerator', N'Linear Partical Accelerator')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Linear Partical Accelerator', N'Linear Partical Accelerator.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Link Encryption', N'Link Encryption')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Link Encryption', N'Link Encryption.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Magnetic Resonance Imaging', N'Magnetic Resonance Imaging')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Magnetic Resonance Imaging', N'Magnetic Resonance Imaging.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Magnetic Resonance Imaging', N'MRI')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Mail Server', N'Mail Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Master Site', N'Master Site')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Master Site', N'Master Site.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Medical Gas System', N'Medical Gas System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Medical Gas System', N'Medical Gas System.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Microwave Backhaul', N'Microwave Backhaul')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Microwave Backhaul', N'Microwave Backhaul.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Modem', N'Modem')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Modem', N'Modem.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'MTU', N'MTU')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'MTU', N'MTU.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Multi Protocol Label Switching', N'MPL Switch')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Multi Protocol Label Switching', N'MPLS')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Multi Protocol Label Switching', N'Multi Protocol Label Switch')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Multi Protocol Label Switching', N'Multi Protocol Label Switching
.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Multi Protocol Label Switching', N'Multi Protocol Label Switching')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Multiple Services Component', N'Multiple Services Component')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Network Printer', N'Network Printer')
GO
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Network Printer', N'Network Printer.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Network Printer', N'Printer')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Network Scanner And Copier', N'Network Scanner And Copier')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Network Scanner And Copier', N'Network Scanner And Copier.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Octagon', N'Octagon')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Optical Ring System', N'Optical Ring System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Optical Ring System', N'Optical Ring System.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Partner', N'Partner')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Partner', N'Partner.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'PC', N'Laptop computer')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'PC', N'PC')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'PC', N'Workstation')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Pentagon', N'Pentagon')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Pentagon', N'Pentagon.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Physiological Monitoring System', N'Physiological Monitoring System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'PLC', N'PLC')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'PLC', N'PLC.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Power Over Ethernet', N'POE')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Power Over Ethernet', N'Power Over Ethernet')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Power Over Ethernet', N'Power Over Ethernet.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Public Kiosk', N'Public Kiosk')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Radio Site', N'Radio Site')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Radio Site', N'Radio Site.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Real Time Location System', N'Real Time Location System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Rectangle', N'Rectangle')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Rectangle', N'Square')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Relay Panel', N'Relay Panel')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Relay Panel', N'Relay Panel.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Remote Access Server', N'Remote Access Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Remote Access Server', N'Remote Access Server.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'RFID Transmitter', N'RFID Transmitter')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Right Triangle', N'Right Triangle')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Rounded Rectangle', N'Rounded Rectangle')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Router', N'Router')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Router', N'Router.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'RTU', N'RTU')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'RTU', N'RTU.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Safety Instrumented System', N'Safety Instrumented System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Safety Instrumented System', N'Safety Instrumented System.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Security Information And Event Management System', N'Security Information And Event Management System')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Security Information And Event Management System', N'Security Information And Event Management System.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Security Information And Event Management System', N'SIEMS')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Serial Radio', N'Serial Radio')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Serial Radio', N'Serial Radio.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Serial Switch', N'Serial Switch')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Serial Switch', N'Serial Switch.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Server', N'Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Star', N'16-Point Star')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Star', N'24-Point Star')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Star', N'32-Point Star')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Star', N'5-Point Star')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Star', N'6-Point Star')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Star', N'7-Point Star')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Star', N'Star')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Subscriber Radio', N'Subscriber Radio')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Subscriber Radio', N'Subscriber Radio.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Switch', N'Switch')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Switch', N'Switch.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'T1 Backhaul', N'T1 Backhaul')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'T1 Backhaul', N'T1 Backhaul.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'TDM Backhaul', N'TDM Backhaul')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'TDM Backhaul', N'TDM Backhaul.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Terminal Server', N'Terminal Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Terminal Server', N'Terminal Server.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Text', N'Text')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Triangle', N'Triangle')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Ultrasound', N'Ultrasound')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Ultrasound', N'Ultrasound.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Unidirectional Device', N'Unidirectional Device')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Unidirectional Device', N'Unidirectional Device.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Uninterruptible Power Supply', N'Uninterruptible Power Supply')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Unknown', N'Unknown')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Unknown', N'Unknown.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Urodynamic Diagnostic Equipment', N'Urodynamic Diagnostic Equipment')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Urodynamic Diagnostic Equipment', N'Urodynamic Diagnostic Equipment.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Vendor', N'Vendor')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Vendor', N'Vendor.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Video Teleconferencing Equipment', N'Video Teleconferencing Equipment')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Virtual Machine Server', N'Virtual Machine Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Virtual Machine Server', N'Virtual Machine Server.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'VLAN Router', N'VLAN Router')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'VLAN Router', N'VLAN Router.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'VLAN Switch', N'VLAN Switch')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'VLAN Switch', N'VLAN Switch.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'VPN', N'VPN')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'VPN', N'VPN.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Web', N'Web')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Web', N'Web.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Web Server', N'Web Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Web Server', N'Web Server.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Windows Update Server', N'Windows Update Server')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Windows Update Server', N'Windows Update Server.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Windows Update Server', N'WUS')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Wireless Modem', N'Wireless Modem')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Wireless Modem', N'Wireless Modem.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Wireless Network', N'Wireless Network')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Wireless Network', N'Wireless Network.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Wireless Router', N'Wireless Router')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Wireless Router', N'Wireless Router.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'XRay Generator', N'XRay Generator')
GO
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'XRay Generator', N'XRay Generator.cset')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Zone', N'Zone')
INSERT [dbo].[VISIO_MAPPING] ([Specific_Type], [Stencil_Name]) VALUES (N'Zone', N'Zone.cset')
ALTER TABLE [dbo].[VISIO_MAPPING]  WITH NOCHECK ADD  CONSTRAINT [FK_VISIO_MAPPING_DIAGRAM_TYPES] FOREIGN KEY([Specific_Type])
REFERENCES [dbo].[DIAGRAM_TYPES] ([Specific_Type])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VISIO_MAPPING] CHECK CONSTRAINT [FK_VISIO_MAPPING_DIAGRAM_TYPES]
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'VISIO_MAPPING'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'VISIO_MAPPING'
GO
