USE [CSETWeb]
GO
/****** Object:  Table [dbo].[REFERENCE_DOCS]    Script Date: 6/28/2018 8:21:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REFERENCE_DOCS](
	[Reference_Doc_Id] [int] IDENTITY(1,1) NOT NULL,
	[Doc_Name] [nvarchar](max) NULL,
	[Doc_Link] [nvarchar](max) NULL,
	[Doc_Short] [varchar](50) NULL,
	[Date_Updated] [datetime] NULL,
	[Date_Last_Checked] [datetime] NULL,
	[Doc_Url] [nvarchar](max) NULL,
	[Doc_Notes] [nvarchar](max) NULL,
 CONSTRAINT [PK_Reference_Docs] PRIMARY KEY CLUSTERED 
(
	[Reference_Doc_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[REFERENCE_DOCS] ON 

INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (1, N'NIST Special Publication 800-53 Revision 3', N'NIST SP800-53 R3.pdf', N'NIST SP 800-53r3', NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'SP 800-53 Rev. 4 Initial Public Draft available final due July 2012')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (2, N'20 Critical Security Controls Twenty Critical Controls for Effective Cyber Defense: Consensus Audit', N'cag.pdf', N'CAG', NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.sans.org/critical-security-controls/guidelines.php', N'2.3 currently resides in app')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (3, N'American Petroleum Institute Pipeline SCADA Security Standard API 1164 2nd Edition', NULL, N'API 1164r2', NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.techstreet.com/cgi-bin/basket?action=add&item_id=4454136', N'nixed by the legal beagles in 4.0')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (4, N'North American Electric Reliability Corporation (NERC) CIPS', NULL, N'NERC CIPS', NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.nerc.com/page.php?cid=2%7C20', N'CIP-002-4 updated 01.24.2011')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (5, N'NRC Cyber Security Programs for Nuclear Facilities Regulatory Guide 5.71', N'NRC Reg Guide 5-71.pdf', N'NRC RG 5.71', NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.nrc.gov/reading-rm/doc-collections/reg-guides/protection/rg/division-5/division-5-61.html', N'current')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (6, N'North American Electric Reliability Corporation (NERC) CIP-007-1 ', N'CIP-007-1.pdf', NULL, NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.nerc.com/files/CIP-007-1.pdf', N'current')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (7, N'ANSI/ISA-99.00.01 , “Security for Industrial Automation and Control Systems Part 1: Terminology, Concepts, and Models"', NULL, NULL, NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.isa.org/Template.cfm?Section=Shop_ISA&Template=/Ecommerce/ProductDisplay.cfm&Productid=9661', N'not found in app')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (8, N'ISA-99.00.02 (DRAFT) Security for Industrial Automation and Control Systems: Part 2: Establishing an Industrial Automation and Control Systems Security Program', NULL, NULL, NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.isa.org/Template.cfm?Section=Standards2&template=/Ecommerce/ProductDisplay.cfm&ProductID=10243', N'not found in app')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (9, N'National Institute of Standards and Technology (NIST)—Special Publication 800-42 "Guideline on Network Security Testing."', NULL, NULL, NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'csrc.nist.gov/publications/nistpubs/800-115/SP800-115.pdf', N'not found in app replaced by SP800-115')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (10, N'North American Electric Reliability Corporation (NERC) CIP-005-1', N'CIP-005-1.pdf', NULL, NULL, CAST(N'2012-04-10T00:00:00.000' AS DateTime), N'http://www.nerc.com/files/CIP-005-3a.pdf', N'still on v.1')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (12, N'NIST Special Publication 800-12 “An Introduction to Computer Security: The NIST Handbook.”', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'up to date')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (13, N'NIST Special Publication 800-82 “Guide to Industrial Control Systems (ICS) Security,” Final Public Draft.', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'up to date')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (14, N'NIST Special Publication 800-94 “Guide to Intrusion Detection and Prevention Systems (IDPS).”', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'up to date')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (15, N'North American Electric Reliability Corporation (NERC) CIP-006-1 “Physical Security of Critical Cyber Assets”', N'CIP-006-1.pdf', NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://www.nerc.com/files/CIP-006-3c.pdf', N'v.3 published July 2010')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (16, N'NIST Special Publication 800-41 Rev. 1 “Guidelines on Firewalls and Firewall Policy (Draft).”', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'up to date')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (17, N'NIST Special Publication 800-15 “Minimum Interoperability Specification for PKI Components (MISPC),Version 1”', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'up to date')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (18, N'NIST Special Publication 800-32 “Introduction to Public Key Technology and the Federal PKI Infrastructure”', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'up to date')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (19, N'NIST Special Publication 800-67 “Recommendation for the Triple Data Encryption Algorithm (TDEA) Block Cipher”', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://csrc.nist.gov/publications/PubsSPs.html', N'not in app')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (20, N'FIPS PUB 112 “Password Usage Standard”', NULL, NULL, NULL, CAST(N'2012-04-11T00:00:00.000' AS DateTime), N'http://www.itl.nist.gov/fipspubs/fip112.htm', N'not in app')
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (21, N'NIST Special Publication 800-53 Revision 2 “Recommended Security Controls for Federal Information Systems"', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (22, N'NIST Special Publication 800-63 Version 1.0.2 “Electronic Authentication Guideline: Recommendations of the National Institute of Standards and Technology”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (23, N'NIST Special Publication 800-14 “Generally Accepted Principles and Practices for Securing Information Technology Systems”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (24, N'NIST Special Publication 800-61 “Computer Security Incident Handling Guide”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (25, N'NIST Special Publication 800-92 “Guide to Computer Security Log Management.”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (26, N'NIST Special Publication 800-27 "Engineering Principles for Information Technology Security (A Baseline for Achieving Security)",Revision A.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (27, N'NIST Special Publication 800-42 “Guideline on Network Security Testing.”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (28, N'NIST Special Publication 800-40  Version 2.0  “Creating a Patch and Vulnerability Management Program”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (29, N'NIST Special Publication 800-83 “Guide to Malware Incident Prevention and Handling”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (30, N'NIST Special Publication 800-81 “Secure Domain Name System (DNS) Deployment Guide”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (31, N'IEC61850 ''“International Standard for Substation Automation Systems.”''', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (32, N'EIA-485, "OSI Model Physical Layer Electrical Specification of a Two-wire, Half-duplex, Multipoint Serial Connection."', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (33, N'ANSI/ISA-TR99.00.01-2007 Security Technologies for Industrial Automation and Control Systems', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (34, N'NIST Special Publication 800-53 Revision 1 “Recommended Security Controls for Federal Information Systems”', N'NIST SP800-53.pdf', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (35, N'ISO 11898-3:2006 "Road vehicles -- Controller area network (CAN) -- Part 3: Low-speed,fault-tolerant,medium-dependent interface"', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (36, N'IEC 61131-3 "Programmable Controllers – Part 3: Programming Languages"', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (37, N'Department of Homeland Security, Recommended Practice for Securing Control System Modems Janruary 2008', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (38, N'RFC 793 Transmission Control Protocol', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (39, N'RFC 791 Internet Protocol', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (40, N'RFC 4301 Security Architecture for the Internet Protocol', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (41, N'RFC 2341 "Cisco Layer Two Forwarding (Protocol) ‘L2F."', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (42, N'RFC 2637 "Point-to-Point Tunneling Protocol.”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (43, N'RFC 2661 "Layer Two Tunneling Protocol ‘L2TP."', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (44, N'RFC 2764 "A Framework for IP Based Virtual Private Networks."', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (45, N'RFC 4026 "Provider Provisioned Virtual Private Network (VPN) Terminology.”', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (46, N'IEEE Standard 1402-2000  "IEEE Guide for Electric Power Substation Physical and Electronic Security," IEEE, New York, New York, April 4, 2000.  ', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (47, N'North American Electric Reliability Corporation (NERC)  CIP-002-1—CIP-009-1, Critical Infrastructure Protection Reliability Standards.   ', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (48, N'Department of Homeland Security  Recommended Practice Control Systems Cyber Security Defense in Depth Strategies, May 2006.  ', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (49, N'Bluetooth Special Interest Group,<a href="http://www.bluetooth.org/apps/content/">http://www.bluetooth.org/apps/content/</a>, Web page accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (50, N'Bluetooth Technical Information, <a href="http://www.bluetooth.com/Pages/Tech-Info.aspx"> http://www.bluetooth.com/Pages/Tech-Info.aspx</a>, Web accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (51, N'Bluetooth Host Controller Interface (HCI), <a href="http://www.palowireless.com/infotooth/tutorial/hci.asp">http://www.palowireless.com/infotooth/tutorial/hci.asp</a>.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (53, N'Bluetooth Security, C. Gehrmann, J. Persson, B. Smeets, Artech House, 2004.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (54, N'Bluetooth Profiles, D. Gratton, Prentice Hall Publishers, 2003.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (55, N'Gehrmann, C., J. Persson, B. Smeets, Bluetooth Security, Artech House, 2004.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (56, N'Gratton, D., Bluetooth Profiles, Prentice Hall Publishers, 2003.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (57, N'Palo Wireless, "Host Controller Interface (HCI)," <a href="http://www.palowireless.com/infotooth/tutorial/hci.asp">http://www.palowireless.com/infotooth/tutorial/hci.asp</a>, Web page accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (58, N'IEEE 802.11 n.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (59, N'T. Brown, Video Surveillance over Wireless, <a href="http://www.hendonpub.com/publications/article/?mag=PSIT&articleId=206465&articleLoc=Other+Articles">http://www.hendonpub.com/publications/article/?mag=PSIT&articleId=206465&articleLoc=Other+Articles</a>.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (60, N'M. Natarajan, Critical Success Factors in Wireless Video Surveillance, <a href="http://www.securityinfowatch.com/article/10558492/critical-success-factors-in-wireless-video-surveillance">http://www.securityinfowatch.com/article/10558492/critical-success-factors-in-wireless-video-surveillance</a>.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (61, N'MPEG-4 – The Media Standard, <a href="http://www.m4if.org/public/documents/vault/m4-out-20027.pdf">http://www.m4if.org/public/documents/vault/m4-out-20027.pdf</a>.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (62, N'EPCGlobal, <a href="http://www.epcglobalinc.org/standards/">http://www.epcglobalinc.org/standards/</a>, Web last accessed May 4, 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (63, N'ISO/IED 18000-2, ISO/IED 18000-3.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (64, N'ISO/IEC 11784-11785.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (65, N'ISO/IEC 10536.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (66, N'"RFID Business Applications," RFID Journal, <a href="http://www.rfidjournal.com/article/articleprint/1334/-1/1">http://www.rfidjournal.com/article/articleprint/1334/-1/1</a>, Web last accessed May 4, 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (67, N'L. Batina, J. Guajardo, T. Kerins, N. Mentens, P. Tuyls, and I.Verbauwhede, “Public-Key Cryptography for RFID-Tags,” In RFID Security: Techniques,Protocols and System-On-Chip Design, P. Kitsos, and Y. Zhang (eds.), Springer-Verlag, 34 pages, 2008. ', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (68, N'J. Schroeter,Demystifying UHF Gen 2 RFID, HF RFID, June 02, 2008,<a href="http://www.eetimes.com/design/industrial-control/4019123/Demystifying-UHF-Gen-2-RFID-HF-RFID">http://www.eetimes.com/design/industrial-control/4019123/Demystifying-UHF-Gen-2-RFID-HF-RFID</a>, Web last accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (69, N'Aime, M., G. Calandriello, A. Lioy, Dependability in Wireless Networks, IEEE Security and Privacy, January/February 2007.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (70, N'Akriditis, P, et al.,  Proximity Breeds Danger: Emerging Threats in Metro-area Wireless Networks, 2007, <a href="http://www.usenix.org/events/sec07/tech/full_papers/akritidis/akritidis_html/">http://www.usenix.org/events/sec07/tech/full_papers/akritidis/akritidis_html/</a>,  Web page accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (71, N'Bellardo, J. and S. Savage, "802.11 Denial-of-Service Attacks: Real Vulnerabilities and Practical Solutions," 2003, <a href="http://cseweb.ucsd.edu/~savage/papers/UsenixSec03.pdf">http://cseweb.ucsd.edu/~savage/papers/UsenixSec03.pdf</a>, Web page accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (72, N'Gizmodo.com, Gadgets: Wireless Jammer, July 28, 2005, <a href="http://gizmodo.com/114698/wireless-jammer">http://gizmodo.com/114698/wireless-jammer</a>, Web page last accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (73, N'IEEE 802.11, “The Working Group for WLAN Standards,” Institute of Electrical and Electronics Engineers, 2007.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (74, N'IEEE Std 802.11i-2004, “Part 11: Wireless LAN Medium Access Control (MAC) and Physical Layer (PHY) specifications Amendment 6: Medium Access Control (MAC) Security Enhancements,” Institute of Electrical and Electronics Engineers, 2007.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (75, N'Infrostream Technologies, Cellphone Jammers, WIFI/Bluetooth Jammers, Wireless Camera Hunter, <a href="http://www.infostream.biz/">http://www.infostream.biz/</a>,  Web page last accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (76, N'Kirk, J. ''Evil twin'' Wi-Fi access points proliferate, April 2007, <a href="http://www.networkworld.com/news/2007/042507-infosec-evil-twin-wi-fi-access.html">''http://www.networkworld.com/news/2007/042507-infosec-evil-twin-wi-fi-access.html</a>, Web page last accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (78, N'Teska, T., How To Crack WPA / WPA 2, January 2008, <a href="http://www.smallnetbuilder.com/wireless/wireless-howto/30278-how-to-crack-wpa--wpa2">http://www.smallnetbuilder.com/wireless/wireless-howto/30278-how-to-crack-wpa--wpa2</a>, Web page last accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (79, N'Vladimirov, A., K. Gavrilenko, and A. Mikhailovsky, 2004, WiFoo: The Secrets of Wireless Hacking, Person/Addison Wesley, <a href="http://www.wi-foo.com">http://www.wi-foo.com</a>, Web page accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (80, N'WiFi Alliance, WPA2 (WiFi Protected Access 2),2007, <a href="http://www.wi-fi.org/knowledge-center/glossary/">http://www.wi-fi.org/knowledge-center/glossary/</a>, Web page last accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (81, N'Daintree Networks, Inc., "Understanding 802.15.4 and ZigBee Networking," <a href="http://www.daintree.net/resources/index.php#primer">"http://www.daintree.net/resources/index.php#primer</a>, Web page accessed April 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (82, N'Gutierrez, J., E. Callaway, and R. Barrett, “Low-Rate Wireless Personal Area Networks: Enabling Wireless Sensors with IEEE 802.15.4™,” IEEE Press, ISN 0-7381-3557-7, 2004.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (83, N'IEEE 802.15.4-2003 standard: <a href="http://www.cs.jhu.edu/~cliang4/public/datasheets/802.15.4-2003.pdf">http://www.cs.jhu.edu/~cliang4/public/datasheets/802.15.4-2003.pdf</a>, Web page accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (84, N'IEEE 802.15, Working Group for WPAN web page: <a href="http://grouper.ieee.org/groups/802/15/"> http://grouper.ieee.org/groups/802/15/</a>, Web page accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (85, N'The ISA Working Group SP100 addresses wireless manufacturing and control systems, <a href="http://www.isa.org//MSTemplate.cfm?MicrositeID=1134&CommitteeID=6891",>http://www.isa.org//MSTemplate.cfm?MicrositeID=1134&CommitteeID=6891</a>, Web page accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (86, N'Werb, J., et al., "Improved Quality of Service in IEEE 802.15.4 Mesh Networks," Sensicast systems and GE Global Research, <a href="http://www.cs.utexas.edu/~cdj/wia_files/submissions/008Final.pdf">http://www.cs.utexas.edu/~cdj/wia_files/submissions/008Final.pdf</a>, Web page accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (87, N'ZigBee Alliance, <a href="http://www.ZigBee.org">http://www.ZigBee.org</a>, Web page accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (88, N'Hale, G., WirelessHART products out and on the way, InTech ONline Magazine, April 24,2008, <a href="http://www.isa.org/InTechTemplate.cfm?Section=InTech_Home1&template=/ContentManagement/ContentDisplay.cfm&ContentID=68959" >"http://www.isa.org/InTechTemplate.cfm?Section=InTech_Home1&template=/ContentManagement/ContentDisplay.cfm&ContentID=68959</a>, Web page last accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (89, N'Hart Communication Foundation, <a href="http://www.hartcomm2.org/index.html">http://www.hartcomm2.org/index.html</a> ', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (90, N'HART Communication Foundation, WirelessHART Technical Data Sheet, May 15, 2007 HCF_LIT 89, Revision 1.0B, May 15, 2007.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (91, N'ISA100, Wireless Compliance Institute,<a href="http://www.isa.org/asci/ISA100-Wireless-Compliance-Institute-Prospectus.pdf">http://www.isa.org/asci/ISA100-Wireless-Compliance-Institute-Prospectus.pdf</a>,  Web page last accessed April 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (92, N'GSM <a href="http://en.wikipedia.org/wiki/GSM">http://en.wikipedia.org/wiki/GSM</a>, Web page last accessed April 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (93, N'MPT 1327, A Signalling Standard for Trunked Private Land Mobile Radio Systems,<a href="http://wiki.radioreference.com/index.php/MPT-1327">http://wiki.radioreference.com/index.php/MPT-1327</a> , Web page last accessed May 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (94, N'Project 25, "APCO Project 25 and its Project 25 (P25) Standards for Public Safety Digital Radio," <a href="http://www.apco911.org/frequency/project25/information.html">http://www.apco911.org/frequency/project25/information.html</a>, Web page last accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (95, N'TETRA RELEASE 1.3, ETSI 300 392-1 General Design <a href="http://www.etsi.org/deliver/etsi_en/300300_300399/30039201/01.03.00_40/en_30039201v010300o.pdf">http://www.etsi.org/deliver/etsi_en/300300_300399/30039201/01.03.00_40/en_30039201v010300o.pdf</a> Web page last accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (96, N'Akyildiz, I., X. Wang, W. Wang, “Wireless Mesh Networks: A Survey,” Elsevier, 2004.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (97, N'Bahr, M., “Proposed Routing for IEEE 802.11s WLAN Mesh Networks,” WICON’06, The 2nd Annual International Wireless Internet Conference, Boston, Massachusetts, August 2-5, 2006.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (98, N'Edler, J., W. Wang, "Wireless! Building Automation Unwired," <a href="http://www.automatedbuildings.com/news/mar06/articles/kiyon/060227054717kiyon.htm">http://www.automatedbuildings.com/news/mar06/articles/kiyon/060227054717kiyon.htm</a>, Web page last accessed January 2012.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (99, N'Mogre, P., M. Hollick, R. Steinmetz, “QoS in Wireless Mesh Networks: Challenges, Pitfalls, and Roadmap to its Realization,” 17th International workshop on Network and Operating Systems Support for Digital Audio & Video, Urbana-Champaign, Illinois, June 4-5, 2007.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (100, N'IEEE 802.11 n, "Standard for Enhancements for Higher Throughput," <a href="http://www.ieee802.org/11/Reports/tgn_update.htm">http://www.ieee802.org/11/Reports/tgn_update.htm</a>, Web accessed April 2009.  ', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (101, N'Mouly, M. and M. Pautet, The GSM System for Mobile Communications Cell and Sys Publishers, 1992, pp 168-170.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (103, N'Pesonen, L. GSM Interception, Novermber 1999, <a href="http://www.dia.unisa.it/professori/ads/corso-security/www/CORSO-9900/a5/Netsec/netsec.html">http://www.dia.unisa.it/professori/ads/corso-security/www/CORSO-9900/a5/Netsec/netsec.html</a>, Web page accessed March 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (104, N'Wingert, C., M. Naidu, CDMA 1x Security Overview, August 2002.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (105, N'IEEE Standard 802.16e, Part 16: Air Interface for Fixed and Mobile Broadband Wireless Access Systems, 2005, pp 269-313.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (106, N'Petäjäsoja, S., et al., Wireless Security: Past, Present and Future, February 2008,<a href="http://www.codenomicon.com/resources/whitepapers/Codenomicon_Wireless_WP_v1_0.pdf">http://www.codenomicon.com/resources/whitepapers/Codenomicon_Wireless_WP_v1_0.pdf</a>, Web page accessed May 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (107, N'WiMAX Forum Mobile System Profile, Release 1.0 Approved Specification, Release 1.0 Approved Specification, (Revision 1.4.0: 2007-05-02), 2007.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (108, N'WiMAX Technology, <a href="http://www.wimaxforum.org/resources/frequently-asked-questions/">http://www.wimaxforum.org/resources/frequently-asked-questions/</a>, Web page accessed April 2009.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (109, N'GR-63-CORE, “NEBS Requirements: Physical Protection,” April 2002. ', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (110, N'GR-1089-CORE, “Electromagnetic Compatibility and Electrical Safety - Generic Criteria for Network Telecommunications Equipment,” October 2002.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (111, N'Senetas Security, “Whitepaper – Microwave Link Encryption,” June 2006.', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[REFERENCE_DOCS] ([Reference_Doc_Id], [Doc_Name], [Doc_Link], [Doc_Short], [Date_Updated], [Date_Last_Checked], [Doc_Url], [Doc_Notes]) VALUES (113, N'', NULL, NULL, NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[REFERENCE_DOCS] OFF
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Reference Doc Id is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Reference_Doc_Id'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Doc Name is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Doc_Name'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Doc Link is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Doc_Link'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Doc Short is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Doc_Short'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Date Updated is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Date_Updated'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Date Last Checked is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Date_Last_Checked'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Doc Url is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Doc_Url'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Doc Notes is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS', @level2type=N'COLUMN',@level2name=N'Doc_Notes'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REFERENCE_DOCS'
GO
