USE [CSETWeb]
GO
/****** Object:  Table [dbo].[CNSS_CIA_TYPES]    Script Date: 6/28/2018 8:21:22 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CNSS_CIA_TYPES](
	[CIA_Type] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CNSS_CIA_TYPES] PRIMARY KEY CLUSTERED 
(
	[CIA_Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CNSS_CIA_TYPES] ([CIA_Type]) VALUES (N'Availability')
INSERT [dbo].[CNSS_CIA_TYPES] ([CIA_Type]) VALUES (N'Confidentiality')
INSERT [dbo].[CNSS_CIA_TYPES] ([CIA_Type]) VALUES (N'Integrity')
