USE [CSETWeb]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 6/28/2018 8:21:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[PrimaryEmail] [varchar](150) NOT NULL,
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Password] [varchar](250) NOT NULL,
	[Salt] [varchar](250) NOT NULL,
	[IsSuperUser] [bit] NOT NULL,
	[PasswordResetRequired] [bit] NOT NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[PrimaryEmail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[USERS] ON 

SET IDENTITY_INSERT [dbo].[USERS] OFF
/****** Object:  Index [IX_USERS]    Script Date: 6/28/2018 8:21:31 AM ******/
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [IX_USERS] UNIQUE NONCLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_IsSuperUser]  DEFAULT ((0)) FOR [IsSuperUser]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_PasswordResetRequired]  DEFAULT ((1)) FOR [PasswordResetRequired]
GO
