USE [CSETWeb]
GO
/****** Object:  Table [dbo].[STANDARD_CATEGORY]    Script Date: 6/28/2018 8:21:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STANDARD_CATEGORY](
	[Standard_Category] [varchar](250) NOT NULL,
 CONSTRAINT [PK_STANDARD_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[Standard_Category] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'(DHS PED:~ ~)')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Agreements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control Decisions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control for Mobile Devices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control for Output Devices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control for Portable and Mobile Devices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control for Transmission Medium')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Control Policy and Procedures - Common Governance, Risk, and Compliance (GRC) Requirements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Controls')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Enforcement')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Records')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Restrictions for Change')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Access Restrictions for Configuration Change')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Account Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Account Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Account Monitoring and Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Accountability, Audit, and Risk Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Accounting of Disclosures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Acquisition Process')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Acquisitions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Addition, Removal, and Disposal of Equipment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Administrative Privileges')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Administrative Safeguards')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Allocation of Resources')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternate Communications Protocols')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternate Control Center')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternate Processing Site')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternate Storage Site')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternate Storage Sites')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternate Telecommunication Services')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternate Work Site')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Alternative Control Center')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Analysis')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Anomalies and Events')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Application Partitioning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Application Software Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Architecture and Provisioning for Name/Address Resolution Service')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Asset Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Asset Monitoring and Tracking')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Asset, Change, and Configuration Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Assign Cybersecurity Responsibilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Attack Mitigation And Incident Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Analysis Tools and Report Generation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit and Accountability')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit and Accountability Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Events')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Generation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Logs')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Monitor/Analysis')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Monitoring, Analysis, and Reporting')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Monitoring/Analysis')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Record Generation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Record Retention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Reduction and Report Generation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Review, Analysis, and Reporting')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Storage Capacity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audit Tools')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Auditable Events')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Auditable Events List')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Auditing Roles Responsible For Provenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Auditor Qualification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Audits')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Authenticator Feedback')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Authenticator Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Authority and Purpose')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Authority to Collect')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Automated Labeling')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Awareness & Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Awareness and Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Awareness and Training Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Baseline Configuration')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Baseline Cyber Security Measures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Boundary Defense')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Boundary Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Build and Maintain a Secure Network and Systems')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Business Environment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'CDA, System And Communications Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Collaborative Computing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Collaborative Computing Devices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Communication Confidentiality')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Communication Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Communication Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Communications')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Communications Partitioning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Complaint Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Component Authenticity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Component Inventory')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Concealment and Misdirection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Concurrent Session Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Conduct and Frequency of Audits')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Confidentiality of Information at Rest')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration Change Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration Change Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration for Least Functionality')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration Management Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration Management Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration Security')
GO
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Configuration Settings')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Consent')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contact with Security Groups and Associations')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contacts with Security Groups and Associations')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Content of Audit Records')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contingency Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contingency Plan Testing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contingency Plan Testing and Exercises')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contingency Planning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contingency Planning Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contingency Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity of Operations')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity of Operations Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity of Operations Plan Testing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity of Operations Plan Update')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity of Operations Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity of Operations Roles and Responsibilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuity of Operations Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuous Assessment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuous Improvement')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuous Monitoring')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Continuous Vulnerability Assessment and Remediation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Contractor and Third Party Personnel Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Control Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Control System Access Restrictions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Control the Workforce Life Cycle')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Controlled Access Based on the Need to Know')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Controlled Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Controlled Use of Administrative Privileges')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Coordination of Emergency Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Corrective Action')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Covert Channel Analysis')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Critical Cyber Asset Classification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Critical Cyber Assets')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Critical Digital Asset and Communications Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Critical Infrastructure Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Criticality Analysis')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cross-Organizational Auditing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cryptographic Key Establishment and Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cryptographic Module Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Customized Development of Critical Components')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cyber Asset Physical Access Controls')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cyber Security Contingency Plan ')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cyber Security Policies')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cyber Security Program Manager')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cyber Security Sponsor')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Cybersecurity Program Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Integrity and Data Integrity Board')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Loss')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Minimization and Retention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Quality')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Quality and Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Recovery')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Recovery Capability')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Retention and Disposal')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Data Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Defense in Depth')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Defense-In-Depth')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Defensive Strategy')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Delivery and Removal')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Denial of Service Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Denial-of-Service Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Detect Cybersecurity Events')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Detection Processes')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Develop Cybersecurity Workforce')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Developer Configuration Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Developer Screening')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Developer Security Architecture and Design')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Developer Security Testing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Developer Security Testing and Evaluation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Developer-Provided Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Development Process, Standards, and Tools')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Device Configuration')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Device Identification and Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Disaster Recovery')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Dissemination of Privacy Program Information')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Distributed Processing and Storage')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Electronic Security Perimeter')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Electronic Security Perimeters')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Email and Web Browser Protections')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Emergency Lighting')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Emergency Power')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Emergency Shutoff')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Emergency Shutoff Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Enclave and Computing Env''t')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Enclave Boundary Defense')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Encryption')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Enhanced Cyber Security Measures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Enterprise Architecture')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Environmental Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Error Handling')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Escalate Cybersecurity Events and Declare Incidents')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Establish and Maintain a Common Operating Picture')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Establish and Maintain Cybersecurity Architecture')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Establish and Maintain Identities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Establish Cybersecurity Program Strategy')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Event and Incident Response, Continuity of Operations')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'External Information System Services')
GO
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'External System Services')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Factory Default Settings Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Fail in Known State')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Fail-Safe Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Fail-Safe Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Failure Prevention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Fire Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Firewall')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Flaw Remediation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Functional Verification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'General Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'General System Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Governance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Governance and Privacy Program')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Hardware Inventory')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Heterogeneity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Honeypots')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Host Intrusion Detection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'HTTPS')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identification And Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identification and Authentication (Non-Organizational Users)')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identification and Authentication (Organizational Users)')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identification and Authentication Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identification-Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identifier Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identify and Respond to Threats')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identify Dependencies')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Identity and Access Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Implement Strong Access Control Measures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Improvements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Handling')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Monitoring')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Reporting')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Reporting & Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response and Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Assistance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response General')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Investigation and Analysis')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Roles and Responsibilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Testing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Testing and Exercises')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Incident Response Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Increase Cybersecurity Awareness')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Individual Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Individual Participation and Redress')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Info Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information and Document Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information and Document Management Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information and Document Retention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Exchange')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Flow Enforcement')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Handling')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Handling and Retention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information in Shared Resources')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Input Validation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Leakage')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Output Filtering')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Output Handling and Retention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Protection Processes and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Remnants')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Security Architecture')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Security Measures of
Performance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Security Measures of Performance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Security Program Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Security Resources')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Security Workforce')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Sharing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Sharing and Communications')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Sharing with Third Parties')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information Spillage Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information System Backup')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information System Component Inventory')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information System Connections')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information System Documentation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information System Inventory')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information System Monitoring')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Information System Recovery and Reconstitution')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Insider Threat Program')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Internal System Connections')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Internal Use')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Intrusion Detection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Inventory')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Inventory of Authorized and Unauthorized Devices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Inventory of Authorized and Unauthorized Software')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Inventory of Personally Identifiable Information')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Least Functionality')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Least Privilege')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Legacy Smart Grid Information System Upgrades')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Life Cycle Support')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Life-Cycle Support')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Limitation and Control of Network Ports')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Location of Information System Components')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Location of Smart Grid Information System Assets')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Logging')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Maintain a Vulnerability Management Program')
GO
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Maintain an Information Security Policy')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Maintenance Monitoring And Information Sharing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Maintenance Personnel')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Maintenance Tools')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Maintenance, Monitoring, and Analysis of Audit Logs')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Malicious Code and Spam Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Malicious Code Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Malware')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Malware Defenses')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Manage Asset Configuration')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Manage Asset Inventory')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Manage Changes to Assets')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Manage Dependency Risk')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Management Accountability')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Management Activities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Management Controls')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Management Practices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Downgrading')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Marking')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Protection Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Sanitization')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Sanitization and Disposal')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Sensitivity Level')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Storage')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Transport')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Media Use')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Memory Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Message Authenticity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Minimization of Personally Identifiable Information')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Minimization of Pii Used in Testing, Training, and Research')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Mission/Business Process Definition')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Mitigation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Mobile Code')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Mobile Device Management MDM ')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring & Malware')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring & Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring and Reviewing Control System Security Policy')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring Configuration Changes')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring for Information Disclosure')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring Physical Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Monitoring Tools')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Need to Know')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Network Architecture')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Network Configuration')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Network Disconnect')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Network Engineering')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Network Vulnerabilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Non-Local Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Non-Modifiable Executable Programs')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Non-Persistence')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Non-repudiation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Operating System-Independent Applications')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Operational Controls')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Operations Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Organizational')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Organizational Requirements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Organizational Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Out-of-Band Channels')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Password')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Passwords')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Patch Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Penetration')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Penetration Testing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Penetration Tests')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Penetration Tests and Red Team Exercises')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Perform Logging')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Perform Monitoring')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Perform Secure Software Development')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Permitted Actions without Identification or Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Accountability')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel and Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Roles')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Sanctions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Screening')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Security Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Termination')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Personnel Transfer')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical & Envtl. Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Access Authorizations')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Access Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Access Log Retention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Access Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical and Environmental')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical and Environmental Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical and Environmental Protection Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical and Environmental Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical and Environmental Security Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical And Operational Environment Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Safeguards')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Physical Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Plan for Continuity')
GO
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Plan of Action and Milestones')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Plan of Action and Milestones Process')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Planning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Planning Process Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Plans')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Platform Vulnerabilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Platform-Independent Applications')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Polices and Procedures and Documentation Requirements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Policies')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Policies & Procedures General')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Policy Vulnerabilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Port and I/O Device Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Portable/Mobile/Wireless')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Ports, Protocols & Services')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Position Categorization')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Position Risk Designation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Power Equipment and Cabling')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Power Equipment and Power Cabling')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Predictable Failure Prevention')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Prev Logon Notification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Previous Logon Notification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Awareness and Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Impact and Risk Assessment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Impact Assessment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Incident Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Monitoring and Auditing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Notice')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Reporting')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy Requirements for Contractors and Service Providers')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Privacy-Enhanced System Design and Development')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Process Isolation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Program Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Proprietary Application Development')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Protect Cardholder Data')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Protection of Audit Information')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Protection of Information at Rest')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Protective Technology')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Provenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Provenance Policy And Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Public Key Infrastructure Certificates')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Public Website Publication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Publicly Accessible Content')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Purpose Specification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Real-time or Layered Notice')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Recover')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Recovery Communications')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Recovery Improvements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Recovery Planning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Recovery Plans')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Redress')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Reduce Cybersecurity Vulnerabilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Regularly Monitor and Test Networks')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Remote Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Remote Access Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Remote Access Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Remote Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Remote Session Termination')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Removable Media')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Resource Priority')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Respond to Incidents and Escalated Cybersecurity Events')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Response Communications')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Response Improvements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Response Planning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Response to Audit Processing Failures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Assessment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Assessment Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Assessment Update')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Management ')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Management and Assessment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Management Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Management Strategy')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Risk Mitigation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Role-Based Security Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Roles & Responsibilities')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Rules of Behavior')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Safe Mode')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Secure Configurations for Hardware and Software')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Secure Configurations for Network Devices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Secure Name / Address Resolution Service (Authoritative Source)')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Secure Name /Address Resolution Service (Authoritative Source)')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Secure Name /Address Resolution Service (Recursive or Caching Resolver)')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Secure Name/Address Resolution Service')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Securing Content')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Securing the Component')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Securing the Router')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Securing the System')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security - Inventory of Personally Identifiable Information')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security - Privacy Incident Response')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Alerts')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Alerts and Advisories')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Alerts, Advisories, and Directives')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Architecture')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Assessment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Assessment & Risk Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Assessment and Authorization')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Assessment and Authorization Policies and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Assessment and Authorization Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Assessment and Risk Management')
GO
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Assessments')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Attributes')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Authorization')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Authorization Process')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Authorization to Operate')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Authorization to Operate Process')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Awareness')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Awareness and Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Awareness and Training Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Awareness and Training Records')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Awareness Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Categorization')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Concept Of Operations')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Continuous Monitoring')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Design-Configuration')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Engineering Principles')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Event Logging')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Func Isolation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Function Isolation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Function Verification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Functionality Verification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Impact Analysis')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Impact Level')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Operation of Cyber System')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Planning Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Policies for Contractors and Third Parties')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Policy')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Policy Compliance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Program')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Program Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Program Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Responsibility Testing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Roles')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Skills')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Skills Assessment and Appropriate Training to Fill Gaps')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security Training Records')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Security-Related Activity Planning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Senior Information Security Officer')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Senior Management Authority')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Sensor Capability and Data')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Separation of Duties')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Service Identification And Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Session Audit')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Session Authenticity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Session Lock')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Session Lock P3 Not Selected')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Session Termination')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Share Cybersecurity Information')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'SIS')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Situational Awareness')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System and Communication Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System and Communication Protection Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System and Information Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System and Information Integrity Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System and Services Acquisition')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System and Services Acquisition Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Backup')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Connections')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Development and Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Documentation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Maintenance Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Monitoring Tools and Techniques')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Partitioning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Recovery and Reconstitution')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Security Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Smart Grid Information System Use Notification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Software')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Software and Information Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Software Inventory')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Software License Usage Restrictions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Software Usage Restrictions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Software, Firmware and Information Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Spam Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Sponsor Cybersecurity Program')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Strategic Planning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Strategic Planning Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Supply Chain and External Dependencies Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Supply Chain Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System & Information Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System & Services Acquisition')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Comms Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Communication Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Communications Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Communications Protection Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System And Information Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Information Integrity Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Service Acquisition')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Services Acquisition')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System and Services Acquisition Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Categorization')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Connections')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Development')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Development and Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Development Life Cycle')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Hardening')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Integrity')
GO
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Interconnections')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Lifecycle')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Maintenance Policy and Procedures')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System of Records Notices and Privacy Act Statements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Recovery')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Security Plan')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'System Use Notification')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Systems Security Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Tamper Resistance and Detection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Technical Controls')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Technical Safeguards')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Telecommunications Services')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Temperature and Humidity Controls')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Testing, Training, and Monitoring')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Thin Nodes')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Third-Party Personnel Security')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Threat and Vulnerability Management')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Threat Awareness Program')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Time Stamps')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Timely Maintenance')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Tracking Provenance And Developing A Baseline')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Training')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transmission Confidentiality and Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transmission Integrity')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transmission of Security Attributes')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transmission of Security Parameters')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transparency')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transparency - Dissemination of Privacy Program Information')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transparency - Privacy Notice')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Transparency - System of Records Notices and Privacy Act Statements')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Trusted Path')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Trustworthiness')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Unsuccessful Login Attempts')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Unsupported System Components')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Usage Restrictions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Use Limitation')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Use Limitation - Information Sharing With Third Parties')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Use Limitation - Internal Use')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Use of Cryptography')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Use of External Information Control Systems')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Use of External Information Systems')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Use of NIST Approved Cryptography')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'User Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'User Identification and Authentication')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'User-Based Collaboration and Information Sharing')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'User-Installed Software')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Virtualization Techniques')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Visitor Access Records')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Visitor Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Visitor Records')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Voice Over Internet Protocol')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Voice-Over Internet Protocol')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Vulnerability & Incident Mgmt.')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Vulnerability Assessment')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Vulnerability Assessment and Awareness')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Vulnerability Scanning')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Water Damage Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Wireless')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Wireless Access')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Wireless Access Control')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Wireless Access Restrictions')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Wireless Devices')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Wireless Link Protection')
INSERT [dbo].[STANDARD_CATEGORY] ([Standard_Category]) VALUES (N'Workforce Management')
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The Standard Category is used to' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'STANDARD_CATEGORY', @level2type=N'COLUMN',@level2name=N'Standard_Category'
GO
EXEC sys.sp_addextendedproperty @name=N'BELONGS_IN_EA', @value=N'YES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'STANDARD_CATEGORY'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'STANDARD_CATEGORY'
GO
