FROM node:22

WORKDIR /var/www

COPY package*.json ./
RUN npm install
COPY . .

ENV NODE_OPTIONS=--max_old_space_size=8192

EXPOSE 4200
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200"]