// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    public partial class AVAILABLE_MATURITY_MODELS
    {
        [Key]
        public int Assessment_Id { get; set; }
        public bool Selected { get; set; }
        [Key]
        public int model_id { get; set; }

        [ForeignKey(nameof(Assessment_Id))]
        [InverseProperty(nameof(ASSESSMENTS.AVAILABLE_MATURITY_MODELS))]
        public virtual ASSESSMENTS Assessment_ { get; set; }
        [ForeignKey(nameof(model_id))]
        [InverseProperty(nameof(MATURITY_MODELS.AVAILABLE_MATURITY_MODELS))]
        public virtual MATURITY_MODELS model_ { get; set; }
    }
}