// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    public partial class MATURITY_QUESTIONS
    {
        public MATURITY_QUESTIONS()
        {
            MATURITY_REFERENCES = new HashSet<MATURITY_REFERENCES>();
        }

        [Key]
        public int Mat_Question_Id { get; set; }
        [StringLength(250)]
        public string Question_Title { get; set; }
        [Required]
        public string Question_Text { get; set; }
        public string Supplemental_Info { get; set; }
        [StringLength(250)]
        public string Category { get; set; }
        [StringLength(250)]
        public string Sub_Category { get; set; }
        public int Maturity_Level { get; set; }
        [Required]
        [StringLength(50)]
        public string Set_Name { get; set; }
        public int Sequence { get; set; }
        [MaxLength(20)]
        public byte[] Text_Hash { get; set; }

        [ForeignKey(nameof(Set_Name))]
        //[InverseProperty(nameof(SETS.MATURITY_QUESTIONS))]
        public virtual SETS Set_NameNavigation { get; set; }
        [InverseProperty("Mat_Question_")]
        public virtual ICollection<MATURITY_REFERENCES> MATURITY_REFERENCES { get; set; }
    }
}