// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    public partial class MATURITY_LEVELS
    {
        [Required]
        [StringLength(50)]
        public string Set_Name { get; set; }
        public int Level { get; set; }
        [StringLength(50)]
        public string Level_Name { get; set; }
    }
}