// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    public partial class MATURITY_QUESTIONS
    {
        public MATURITY_QUESTIONS()
        {
            MATURITY_REFERENCES = new HashSet<MATURITY_REFERENCES>();
            MATURITY_SOURCE_FILES = new HashSet<MATURITY_SOURCE_FILES>();
        }

        [Key]
        public int Mat_Question_Id { get; set; }
        [StringLength(250)]
        public string Question_Title { get; set; }
        [Required]
        public string Question_Text { get; set; }
        public string Supplemental_Info { get; set; }
        [StringLength(250)]
        public string Category { get; set; }
        [StringLength(250)]
        public string Sub_Category { get; set; }
        public int Maturity_Level { get; set; }
        public int Sequence { get; set; }
        [MaxLength(20)]
        public byte[] Text_Hash { get; set; }
        public int Maturity_Model_Id { get; set; }

        [ForeignKey(nameof(Maturity_Level))]
        [InverseProperty(nameof(MATURITY_LEVELS.MATURITY_QUESTIONS))]
        public virtual MATURITY_LEVELS Maturity_LevelNavigation { get; set; }
        [ForeignKey(nameof(Maturity_Model_Id))]
        [InverseProperty(nameof(MATURITY_MODELS.MATURITY_QUESTIONS))]
        public virtual MATURITY_MODELS Maturity_Model_ { get; set; }
        [InverseProperty("Mat_Question_")]
        public virtual ICollection<MATURITY_REFERENCES> MATURITY_REFERENCES { get; set; }
        [InverseProperty("Mat_Question_")]
        public virtual ICollection<MATURITY_SOURCE_FILES> MATURITY_SOURCE_FILES { get; set; }
    }
}