DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0030.js", "first": "0", "last": "066" },
	{ "fileName": "0xu0031.js", "first": "1", "last": "1996" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "25" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "365" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "438" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "552A" },
	{ "fileName": "0xu0036.js", "first": "6", "last": "62443" },
	{ "fileName": "0xu0037.js", "first": "7", "last": "7628" },
	{ "fileName": "0xu0038.js", "first": "8", "last": "8510.01" },
	{ "fileName": "0xu0039.js", "first": "9", "last": "90" },
	{ "fileName": "0xu0041.js", "first": "A", "last": "AXIS" },
	{ "fileName": "0xu0042.js", "first": "BACK", "last": "BYPASSES" },
	{ "fileName": "0xu0043.js", "first": "C", "last": "CYSTOURETHROGRAPHY" },
	{ "fileName": "0xu0044.js", "first": "DAILY", "last": "DYNAMICALLY" },
	{ "fileName": "0xu0045.js", "first": "E", "last": "EYEWASH" },
	{ "fileName": "0xu0046.js", "first": "F", "last": "FUTURE" },
	{ "fileName": "0xu0047.js", "first": "G", "last": "GUIDES" },
	{ "fileName": "0xu0048.js", "first": "HAD", "last": "HYPERLINKS" },
	{ "fileName": "0xu0049.js", "first": "I", "last": "I’VE" },
	{ "fileName": "0xu004a.js", "first": "JANUARY", "last": "JUSTIFICATION" },
	{ "fileName": "0xu004b.js", "first": "KEEP", "last": "KNOWN" },
	{ "fileName": "0xu004c.js", "first": "LABEL", "last": "LOWEST" },
	{ "fileName": "0xu004d.js", "first": "MAC", "last": "MY" },
	{ "fileName": "0xu004e.js", "first": "N", "last": "NUTRIENTS" },
	{ "fileName": "0xu004f.js", "first": "OBJECT", "last": "OXYGEN" },
	{ "fileName": "0xu0050.js", "first": "PACKAGE", "last": "PUTS" },
	{ "fileName": "0xu0051.js", "first": "QUALIFICATIONS", "last": "QUICKLY" },
	{ "fileName": "0xu0052.js", "first": "R5", "last": "RUNS" },
	{ "fileName": "0xu0053.js", "first": "S", "last": "SYSTEMS" },
	{ "fileName": "0xu0054.js", "first": "T", "last": "TYPICALLY" },
	{ "fileName": "0xu0055.js", "first": "U", "last": "UTILIZING" },
	{ "fileName": "0xu0056.js", "first": "V1", "last": "VULNERABILITY" },
	{ "fileName": "0xu0057.js", "first": "WALK", "last": "WRITTEN" },
	{ "fileName": "0xu0058.js", "first": "X", "last": "XS" },
	{ "fileName": "0xu0059.js", "first": "Y2K", "last": "YOUTUBE" },
	{ "fileName": "0xu005a.js", "first": "ZONE", "last": "ZOOM" }
];