// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class AcetAnswerDistributionResult
    {
        public string Answer_Text { get; set; }
        public int? Count { get; set; }
    }
}
