// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[PrimaryKey("AddressType", "Id")]
public partial class ADDRESS
{
    [StringLength(150)]
    public string PrimaryEmail { get; set; }

    [Key]
    [StringLength(50)]
    public string AddressType { get; set; }

    [Key]
    public Guid Id { get; set; }

    [StringLength(150)]
    public string City { get; set; }

    [StringLength(150)]
    public string Country { get; set; }

    [StringLength(150)]
    public string Line1 { get; set; }

    [StringLength(150)]
    public string Line2 { get; set; }

    [StringLength(150)]
    public string State { get; set; }

    [StringLength(150)]
    public string Zip { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("ADDRESS")]
    public virtual USER_DETAIL_INFORMATION IdNavigation { get; set; }
}