// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class analytics_compute_single_averages_maturityResult
    {
        [StringLength(200)]
        public string Title { get; set; }
        [StringLength(1)]
        public string Answer_Text { get; set; }
        public int Answer_Count { get; set; }
        public int Total { get; set; }
        public int Percentage { get; set; }
    }
}
