// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class analytics_getMinMaxAverageForSectorIndustryGroupResult
    {
        public string Question_Group_Heading { get; set; }
        public int? min { get; set; }
        public int? max { get; set; }
        public int? avg { get; set; }
    }
}
