// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    [Keyless]
    public partial class ASSESSMENT_DETAIL_FILTER_DATA
    {
        [Required]
        [Unicode(false)]
        public string Name { get; set; }
        [Unicode(false)]
        public string CityOrSite { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string State { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Charter { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Model { get; set; }
    }
}