// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of ASSESSMENT_ROLES records
/// </summary>
public partial class ASSESSMENT_ROLES
{
    [Key]
    public int AssessmentRoleId { get; set; }

    [Required]
    [StringLength(50)]
    public string AssessmentRole { get; set; }

    [InverseProperty("AssessmentRole")]
    public virtual ICollection<ASSESSMENT_CONTACTS> ASSESSMENT_CONTACTS { get; set; } = new List<ASSESSMENT_CONTACTS>();
}