// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class ASSESSMENT_ICONS
    {
        public ASSESSMENT_ICONS()
        {
            MATURITY_MODELS = new HashSet<MATURITY_MODELS>();
            SETS = new HashSet<SETS>();
        }

        [Key]
        public int Icon_Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Icon_Path { get; set; }

        [InverseProperty("Icon")]
        public virtual ICollection<MATURITY_MODELS> MATURITY_MODELS { get; set; }
        [InverseProperty("Icon")]
        public virtual ICollection<SETS> SETS { get; set; }
    }
}