// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    /// <summary>
    /// A collection of ASSESSMENT_IRP_HEADER records
    /// </summary>
    public partial class ASSESSMENT_IRP_HEADER
    {
        public int? HEADER_RISK_LEVEL_ID { get; set; }
        [Key]
        public int ASSESSMENT_ID { get; set; }
        [Key]
        public int IRP_HEADER_ID { get; set; }
        public int? RISK_LEVEL { get; set; }
        [StringLength(500)]
        public string COMMENT { get; set; }

        [ForeignKey(nameof(ASSESSMENT_ID))]
        [InverseProperty(nameof(ASSESSMENTS.ASSESSMENT_IRP_HEADER))]
        public virtual ASSESSMENTS ASSESSMENT_ { get; set; }
        [ForeignKey(nameof(IRP_HEADER_ID))]
        [InverseProperty(nameof(IRP_HEADER.ASSESSMENT_IRP_HEADER))]
        public virtual IRP_HEADER IRP_HEADER_ { get; set; }
    }
}