// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[Index("Defining_System", Name = "IX_CIS_CSI_DEFINING_SYSTEMS", IsUnique = true)]
public partial class CIS_CSI_DEFINING_SYSTEMS
{
    [Key]
    public int Defining_System_Id { get; set; }

    [Required]
    [StringLength(400)]
    public string Defining_System { get; set; }

    [InverseProperty("Primary_Defining_SystemNavigation")]
    public virtual ICollection<CIS_CSI_SERVICE_COMPOSITION> CIS_CSI_SERVICE_COMPOSITION { get; set; } = new List<CIS_CSI_SERVICE_COMPOSITION>();

    [InverseProperty("Defining_System")]
    public virtual ICollection<CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS> CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS { get; set; } = new List<CIS_CSI_SERVICE_COMPOSITION_SECONDARY_DEFINING_SYSTEMS>();
}