// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class CIST_CSI_SERVICE_COMPOSITION
    {
        [Key]
        public int Assessment_Id { get; set; }
        [StringLength(400)]
        public string Networks_Description { get; set; }
        [StringLength(400)]
        public string Services_Description { get; set; }
        [StringLength(400)]
        public string Applications_Description { get; set; }
        [StringLength(400)]
        public string Connections_Description { get; set; }
        [StringLength(400)]
        public string Personnel_Description { get; set; }
        [StringLength(400)]
        public string Other_Defining_System_Description { get; set; }
        public int? Primary_Defining_System { get; set; }
        public int? Secondary_Defining_System { get; set; }

        [ForeignKey(nameof(Assessment_Id))]
        [InverseProperty(nameof(ASSESSMENTS.CIST_CSI_SERVICE_COMPOSITION))]
        public virtual ASSESSMENTS Assessment { get; set; }
        [ForeignKey(nameof(Primary_Defining_System))]
        [InverseProperty(nameof(CIST_CSI_DEFINING_SYSTEMS.CIST_CSI_SERVICE_COMPOSITION))]
        public virtual CIST_CSI_DEFINING_SYSTEMS Primary_Defining_SystemNavigation { get; set; }
    }
}