// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class CIST_CSI_CUSTOMER_AMOUNTS
    {
        public CIST_CSI_CUSTOMER_AMOUNTS()
        {
            CIST_CSI_SERVICE_DEMOGRAPHICS = new HashSet<CIST_CSI_SERVICE_DEMOGRAPHICS>();
        }

        public int Value_Id { get; set; }
        [Key]
        [StringLength(25)]
        public string Customer_Amount { get; set; }
        public int? Value_Order { get; set; }

        [InverseProperty("Num_CustomersNavigation")]
        public virtual ICollection<CIST_CSI_SERVICE_DEMOGRAPHICS> CIST_CSI_SERVICE_DEMOGRAPHICS { get; set; }
    }
}