// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class CIST_CSI_STAFF_COUNTS
    {
        public CIST_CSI_STAFF_COUNTS()
        {
            CIST_CSI_ORGANIZATION_DEMOGRAPHICSCybersecurity_IT_ICS_Staff_CountNavigation = new HashSet<CIST_CSI_ORGANIZATION_DEMOGRAPHICS>();
            CIST_CSI_ORGANIZATION_DEMOGRAPHICSIT_ICS_Staff_CountNavigation = new HashSet<CIST_CSI_ORGANIZATION_DEMOGRAPHICS>();
            CIST_CSI_SERVICE_DEMOGRAPHICSCybersecurity_IT_ICS_Staff_CountNavigation = new HashSet<CIST_CSI_SERVICE_DEMOGRAPHICS>();
            CIST_CSI_SERVICE_DEMOGRAPHICSIT_ICS_Staff_CountNavigation = new HashSet<CIST_CSI_SERVICE_DEMOGRAPHICS>();
        }

        [Key]
        [StringLength(25)]
        public string Staff_Count { get; set; }
        public int Sequence { get; set; }

        [InverseProperty(nameof(CIST_CSI_ORGANIZATION_DEMOGRAPHICS.Cybersecurity_IT_ICS_Staff_CountNavigation))]
        public virtual ICollection<CIST_CSI_ORGANIZATION_DEMOGRAPHICS> CIST_CSI_ORGANIZATION_DEMOGRAPHICSCybersecurity_IT_ICS_Staff_CountNavigation { get; set; }
        [InverseProperty(nameof(CIST_CSI_ORGANIZATION_DEMOGRAPHICS.IT_ICS_Staff_CountNavigation))]
        public virtual ICollection<CIST_CSI_ORGANIZATION_DEMOGRAPHICS> CIST_CSI_ORGANIZATION_DEMOGRAPHICSIT_ICS_Staff_CountNavigation { get; set; }
        [InverseProperty(nameof(CIST_CSI_SERVICE_DEMOGRAPHICS.Cybersecurity_IT_ICS_Staff_CountNavigation))]
        public virtual ICollection<CIST_CSI_SERVICE_DEMOGRAPHICS> CIST_CSI_SERVICE_DEMOGRAPHICSCybersecurity_IT_ICS_Staff_CountNavigation { get; set; }
        [InverseProperty(nameof(CIST_CSI_SERVICE_DEMOGRAPHICS.IT_ICS_Staff_CountNavigation))]
        public virtual ICollection<CIST_CSI_SERVICE_DEMOGRAPHICS> CIST_CSI_SERVICE_DEMOGRAPHICSIT_ICS_Staff_CountNavigation { get; set; }
    }
}