// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    /// <summary>
    /// A collection of COMPONENT_NAMES_LEGACY records
    /// </summary>
    public partial class COMPONENT_NAMES_LEGACY
    {
        public int Component_Symbol_id { get; set; }
        [Key]
        [StringLength(50)]
        public string Old_Symbol_Name { get; set; }

        [ForeignKey(nameof(Component_Symbol_id))]
        [InverseProperty(nameof(COMPONENT_SYMBOLS.COMPONENT_NAMES_LEGACY))]
        public virtual COMPONENT_SYMBOLS Component_Symbol_ { get; set; }
    }
}