// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class counties1
    {
        [Key]
        [StringLength(10)]
        [Unicode(false)]
        public string FIPS { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(2)]
        [Unicode(false)]
        public string State { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string RegionCode { get; set; }
    }
}