// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class County_MetropolitanArea
    {
        [Key]
        public int County_Code { get; set; }
        [Key]
        public int MetropolitanArea { get; set; }

        [ForeignKey("County_Code")]
        [InverseProperty("County_MetropolitanArea")]
        public virtual Counties County_CodeNavigation { get; set; }
        [ForeignKey("MetropolitanArea")]
        [InverseProperty("County_MetropolitanArea")]
        public virtual MetropolitanArea MetropolitanAreaNavigation { get; set; }
    }
}