// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using CSETWebCore.DataLayer.Model;

namespace CSETWebCore.DataLayer.Model
{
    public partial class CsetwebContext
    {

        [DbFunction("convert_sal", "dbo")]
        public static string convert_sal(string SAL)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("convert_sal_short", "dbo")]
        public static string convert_sal_short(string SAL)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("Split", "dbo")]
        public IQueryable<SplitResult> Split(string str)
        {
            return FromExpression(() => Split(str));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SplitResult>().HasNoKey();
        }
    }
}
