// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using CSETWebCore.DataLayer.Model;

namespace CSETWebCore.DataLayer.Model
{
    public partial class CsetwebContext
    {

        [DbFunction("convert_sal", "dbo")]
        public static string convert_sal(string SAL)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("convert_sal_short", "dbo")]
        public static string convert_sal_short(string SAL)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("func_AM", "dbo")]
        public IQueryable<func_AMResult> func_AM(int? assessmentId)
        {
            return FromExpression(() => func_AM(assessmentId));
        }

        [DbFunction("func_MQ", "dbo")]
        public IQueryable<func_MQResult> func_MQ(int? assessmentId)
        {
            return FromExpression(() => func_MQ(assessmentId));
        }

        //[DbFunction("Split", "dbo")]
        //public IQueryable<SplitResult> Split(string string)
        //{
        //    return FromExpression(() => Split(string));
        //}

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<func_AMResult>().HasNoKey();
            modelBuilder.Entity<func_MQResult>().HasNoKey();
            modelBuilder.Entity<SplitResult>().HasNoKey();
        }
    }
}
