// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    public partial class CUSTOM_QUESTIONAIRE_QUESTIONS
    {
        [Key]
        [StringLength(50)]
        public string Custom_Questionaire_Name { get; set; }
        [Key]
        public int Question_Id { get; set; }

        [ForeignKey(nameof(Custom_Questionaire_Name))]
        [InverseProperty(nameof(CUSTOM_QUESTIONAIRES.CUSTOM_QUESTIONAIRE_QUESTIONS))]
        public virtual CUSTOM_QUESTIONAIRES Custom_Questionaire_NameNavigation { get; set; }
    }
}