// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class CYOTE_PATHS
    {
        public CYOTE_PATHS()
        {
            CYOTE_ANSWERS = new HashSet<CYOTE_ANSWERS>();
        }

        [Key]
        public int Path_Id { get; set; }
        public int Option1 { get; set; }
        public int Option2 { get; set; }
        public int Option3 { get; set; }

        [InverseProperty("Path")]
        public virtual ICollection<CYOTE_ANSWERS> CYOTE_ANSWERS { get; set; }
    }
}