// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class DOCUMENT_FILE
    {
        public DOCUMENT_FILE()
        {
            INFORMATION = new HashSet<INFORMATION>();
            Answer = new HashSet<ANSWER>();
        }

        public int Assessment_Id { get; set; }
        /// <summary>
        /// The Document Id is used to
        /// </summary>
        [Key]
        public int Document_Id { get; set; }
        /// <summary>
        /// The Path is used to
        /// </summary>
        [StringLength(3990)]
        [Unicode(false)]
        public string Path { get; set; }
        /// <summary>
        /// The Title is used to
        /// </summary>
        [StringLength(3990)]
        [Unicode(false)]
        public string Title { get; set; }
        [StringLength(32)]
        [Unicode(false)]
        public string FileMd5 { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string ContentType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTimestamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedTimestamp { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Name { get; set; }
        public byte[] Data { get; set; }

        [ForeignKey("Assessment_Id")]
        [InverseProperty("DOCUMENT_FILE")]
        public virtual ASSESSMENTS Assessment { get; set; }
        [ForeignKey("Assessment_Id")]
        [InverseProperty("DOCUMENT_FILE")]
        public virtual DEMOGRAPHICS AssessmentNavigation { get; set; }
        [InverseProperty("eMass_Document")]
        public virtual ICollection<INFORMATION> INFORMATION { get; set; }

        [ForeignKey("Document_Id")]
        [InverseProperty("Document")]
        public virtual ICollection<ANSWER> Answer { get; set; }
    }
}