// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class ExtendedDemographicCountyAnswers
    {
        [Key]
        public int Assessment_Id { get; set; }
        [Key]
        public int County_Id { get; set; }

        [ForeignKey("Assessment_Id")]
        [InverseProperty("ExtendedDemographicCountyAnswers")]
        public virtual ASSESSMENTS Assessment { get; set; }
        [ForeignKey("County_Id")]
        [InverseProperty("ExtendedDemographicCountyAnswers")]
        public virtual Counties County { get; set; }
    }
}