// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class ExtendedSector
    {
        public ExtendedSector()
        {
            ExtendedSubSector = new HashSet<ExtendedSubSector>();
        }

        [Key]
        [StringLength(150)]
        public string SectorName { get; set; }
        [Required]
        [StringLength(4000)]
        public string SectorHelp { get; set; }

        [InverseProperty("SectorNameNavigation")]
        public virtual ICollection<ExtendedSubSector> ExtendedSubSector { get; set; }
    }
}