// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class ExtendedSubSector
    {
        public ExtendedSubSector()
        {
            ExtendedDemographicAnswer = new HashSet<ExtendedDemographicAnswer>();
        }

        public int? SectorId { get; set; }
        [Key]
        [StringLength(150)]
        public string SectorName { get; set; }
        [Key]
        [StringLength(250)]
        public string SubSectorName { get; set; }

        [ForeignKey("SectorName")]
        [InverseProperty("ExtendedSubSector")]
        public virtual ExtendedSector SectorNameNavigation { get; set; }
        [InverseProperty("S")]
        public virtual ICollection<ExtendedDemographicAnswer> ExtendedDemographicAnswer { get; set; }
    }
}