// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of FINANCIAL_REVIEWTYPE records
/// </summary>
public partial class FINANCIAL_REVIEWTYPE
{
    [Key]
    [StringLength(50)]
    public string ReviewType { get; set; }

    [InverseProperty("ReviewTypeNavigation")]
    public virtual ICollection<FINANCIAL_HOURS> FINANCIAL_HOURS { get; set; } = new List<FINANCIAL_HOURS>();
}