// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    /// <summary>
    /// A collection of FINANCIAL_REVIEWTYPE records
    /// </summary>
    public partial class FINANCIAL_REVIEWTYPE
    {
        public FINANCIAL_REVIEWTYPE()
        {
            FINANCIAL_HOURS = new HashSet<FINANCIAL_HOURS>();
        }

        [Key]
        [StringLength(50)]
        public string ReviewType { get; set; }

        [InverseProperty("ReviewTypeNavigation")]
        public virtual ICollection<FINANCIAL_HOURS> FINANCIAL_HOURS { get; set; }
    }
}