// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of FINANCIAL_DOMAINS records
/// </summary>
[Index("Domain", Name = "IX_FINANCIAL_DOMAINS", IsUnique = true)]
public partial class FINANCIAL_DOMAINS
{
    [Required]
    [StringLength(255)]
    public string Domain { get; set; }

    [Key]
    public int DomainId { get; set; }

    [StringLength(50)]
    public string Acronym { get; set; }

    [InverseProperty("Domain")]
    public virtual ICollection<FINANCIAL_DOMAIN_FILTERS> FINANCIAL_DOMAIN_FILTERS { get; set; } = new List<FINANCIAL_DOMAIN_FILTERS>();

    [InverseProperty("Domain")]
    public virtual ICollection<FINANCIAL_DOMAIN_FILTERS_V2> FINANCIAL_DOMAIN_FILTERS_V2 { get; set; } = new List<FINANCIAL_DOMAIN_FILTERS_V2>();

    [InverseProperty("Domain")]
    public virtual ICollection<FINANCIAL_GROUPS> FINANCIAL_GROUPS { get; set; } = new List<FINANCIAL_GROUPS>();

    [InverseProperty("Domain")]
    public virtual ICollection<FINANCIAL_HOURS_COMPONENT> FINANCIAL_HOURS_COMPONENT { get; set; } = new List<FINANCIAL_HOURS_COMPONENT>();
}