// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    public partial class GENERAL_SAL
    {
        /// <summary>
        /// The Id is used to
        /// </summary>
        [Key]
        public int Assessment_Id { get; set; }
        /// <summary>
        /// The Sal Weight Id is used to
        /// </summary>
        [Key]
        [StringLength(50)]
        public string Sal_Name { get; set; }
        public int Slider_Value { get; set; }

        [ForeignKey(nameof(Assessment_Id))]
        [InverseProperty(nameof(ASSESSMENTS.GENERAL_SAL))]
        public virtual ASSESSMENTS Assessment_ { get; set; }
        [ForeignKey(nameof(Sal_Name))]
        [InverseProperty(nameof(GEN_SAL_NAMES.GENERAL_SAL))]
        public virtual GEN_SAL_NAMES Sal_NameNavigation { get; set; }
    }
}