// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class Get_Merge_ConflictsResult
    {
        public int? Assessment_Id { get; set; }
        public int? Question_Or_Requirement_Id { get; set; }
        public string Answer_Text { get; set; }
    }
}
