// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class GetAnswerDistribGroupingsResult
    {
        public int grouping_id { get; set; }
        public string title { get; set; }
        public string answer_text { get; set; }
        public int? answer_count { get; set; }
    }
}
