// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class GetComparisonBestToWorstResult
    {
        public int assessment_id { get; set; }
        public string AssessmentName { get; set; }
        public string Name { get; set; }
        public int? AlternateCount { get; set; }
        public double? AlternateValue { get; set; }
        public int? NaCount { get; set; }
        public double? NaValue { get; set; }
        public int? NoCount { get; set; }
        public double? NoValue { get; set; }
        public int? TotalCount { get; set; }
        public int? TotalValue { get; set; }
        public int? UnansweredCount { get; set; }
        public double? UnansweredValue { get; set; }
        public int? YesCount { get; set; }
        public double? YesValue { get; set; }
        public double? Value { get; set; }
    }
}
