// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class GetMaturityDetailsCalculationsResult
    {
        public int? grouporder { get; set; }
        public int? Total { get; set; }
        public int DomainId { get; set; }
        public string Domain { get; set; }
        public int AssessmentFactorId { get; set; }
        public string AssessmentFactor { get; set; }
        public int FinComponentId { get; set; }
        public string FinComponent { get; set; }
        public string MaturityLevel { get; set; }
        public string Answer_Text { get; set; }
        public int acount { get; set; }
        public double AnswerPercent { get; set; }
        public bool? complete { get; set; }
    }
}
