// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    /// <summary>
    /// HYDRO specific fields for Action Items results page
    /// </summary>
    public partial class HYDRO_DATA_ACTIONS
    {

        [Key]
        [ForeignKey("Answer_Id")]
        public int Answer_Id { get; set; }
        [ForeignKey("Progress_Id")]
        public int Progress_Id { get; set; }
        [StringLength(2000)]
        public string? Comment { get; set; }
        [ForeignKey("Answer_Id")]
        [InverseProperty("HYDRO_DATA_ACTIONS")]
        public virtual ANSWER Answer { get; set; }
    }
}