// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    /// <summary>
    /// HYDRO specific fields for most of the results page
    /// </summary>
    public partial class HYDRO_DATA
    {
        public HYDRO_DATA()
        {
        }

        [Key]
        [ForeignKey("Mat_Option_Id")]
        public int Mat_Option_Id { get; set; }
        [ForeignKey("Mat_Question_Id")]
        public int Mat_Question_Id { get; set; }
        public string Feasibility { get; set; }
        [StringLength(50)]
        public int Feasibility_Limit { get; set; }
        public string Impact { get; set; }
        [StringLength(50)]
        public int Impact_Limit { get; set; }
    }
}