// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

public partial class HYDRO_PROGRESS
{
    [Key]
    public int Progress_Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Progress_Text { get; set; }

    [InverseProperty("Progress")]
    public virtual ICollection<HYDRO_DATA_ACTIONS> HYDRO_DATA_ACTIONS { get; set; } = new List<HYDRO_DATA_ACTIONS>();
}