// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    /// <summary>
    /// ISE specific fields for issues
    /// </summary>
    public partial class ISE_ACTIONS
    {
        public ISE_ACTIONS()
        {
            ISE_ACTIONS_FINDINGS = new HashSet<ISE_ACTIONS_FINDINGS>();
        }

        [Key]
        public int Mat_Question_Id { get; set; }
        public string Description { get; set; }
        [StringLength(1000)]
        public string Action_Items { get; set; }
        [StringLength(100)]
        public string Regulatory_Citation { get; set; }
        public int? Parent_Id { get; set; }

        [ForeignKey("Mat_Question_Id")]
        [InverseProperty("ISE_ACTIONS")]
        public virtual MATURITY_QUESTIONS Mat_Question { get; set; }
        [InverseProperty("Mat_Question")]
        public virtual ICollection<ISE_ACTIONS_FINDINGS> ISE_ACTIONS_FINDINGS { get; set; }
    }
}