// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    /// <summary>
    /// A collection of JWT records
    /// </summary>
    public partial class JWT
    {
        [Key]
        [StringLength(200)]
        public string Secret { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Generated { get; set; }
    }
}