// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of JWT records
/// </summary>
public partial class JWT
{
    [Key]
    [StringLength(200)]
    public string Secret { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Generated { get; set; }
}