// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

public partial class LU_WEIGHTS
{
    [Key]
    [StringLength(50)]
    public string DisplayID { get; set; }

    public double? WEIGHT_VAL { get; set; }
}