// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[Index("Assessment_Id", "Question_Or_Requirement_Id", "Malcolm_Id", Name = "IX_MALCOLM_ANSWERS", IsUnique = true)]
public partial class MALCOLM_ANSWERS
{
    public int Assessment_Id { get; set; }

    public int Question_Or_Requirement_Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Answer_Text { get; set; }

    public int Malcolm_Id { get; set; }

    [Key]
    public int Malcolm_Answer_Id { get; set; }

    public int? Mat_Option_Id { get; set; }

    [ForeignKey("Assessment_Id")]
    [InverseProperty("MALCOLM_ANSWERS")]
    public virtual ASSESSMENTS Assessment { get; set; }
}