// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    /// <summary>
    /// A collection of MATURITY_GROUPINGS records
    /// </summary>
    public partial class MATURITY_GROUPINGS
    {
        public MATURITY_GROUPINGS()
        {
            MATURITY_DOMAIN_REMARKS = new HashSet<MATURITY_DOMAIN_REMARKS>();
        }

        [Key]
        public int Grouping_Id { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }
        public int Maturity_Model_Id { get; set; }
        public int Sequence { get; set; }
        public int? Parent_Id { get; set; }
        public int? Group_Level { get; set; }
        public int Type_Id { get; set; }
        [StringLength(250)]
        public string Title_Id { get; set; }
        [StringLength(20)]
        public string Abbreviation { get; set; }

        [ForeignKey(nameof(Maturity_Model_Id))]
        [InverseProperty(nameof(MATURITY_MODELS.MATURITY_GROUPINGS))]
        public virtual MATURITY_MODELS Maturity_Model_ { get; set; }
        [ForeignKey(nameof(Type_Id))]
        [InverseProperty(nameof(MATURITY_GROUPING_TYPES.MATURITY_GROUPINGS))]
        public virtual MATURITY_GROUPING_TYPES Type_ { get; set; }
        [InverseProperty("Grouping_")]
        public virtual ICollection<MATURITY_DOMAIN_REMARKS> MATURITY_DOMAIN_REMARKS { get; set; }
    }
}