// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

public partial class MATURITY_GLOBAL_SEQUENCES
{
    public int Maturity_Model_Id { get; set; }

    [Key]
    public long global_sequence { get; set; }

    public int g1 { get; set; }

    public int? g2 { get; set; }

    public int? g3 { get; set; }

    public int? g4 { get; set; }
}