// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class MetropolitanArea
    {
        public MetropolitanArea()
        {
            County_MetropolitanArea = new HashSet<County_MetropolitanArea>();
            ExtendedDemographicMetropolitanAnswers = new HashSet<ExtendedDemographicMetropolitanAnswers>();
        }

        [Key]
        public int ToBeReplaceByISOCode { get; set; }
        [StringLength(300)]
        public string MetropolitanAreaName { get; set; }
        [StringLength(10)]
        public string ISO_Code { get; set; }

        [InverseProperty("MetropolitanAreaNavigation")]
        public virtual ICollection<County_MetropolitanArea> County_MetropolitanArea { get; set; }
        [InverseProperty("Metropolitan")]
        public virtual ICollection<ExtendedDemographicMetropolitanAnswers> ExtendedDemographicMetropolitanAnswers { get; set; }
    }
}