// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[Keyless]
public partial class METRIC_ASSESSMENT_COMPLETE
{
    public int Assessment_id { get; set; }

    [Required]
    [StringLength(17)]
    [Unicode(false)]
    public string Question_Type { get; set; }

    [Column(TypeName = "numeric(26, 14)")]
    public decimal? PERC_COMPLETE { get; set; }
}