// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

public partial class METRO_AREA
{
    [Required]
    [StringLength(300)]
    public string MetropolitanAreaName { get; set; }

    [Key]
    [StringLength(10)]
    public string Metro_FIPS { get; set; }

    [InverseProperty("Metro_FIPSNavigation")]
    public virtual ICollection<COUNTY_METRO_AREA> COUNTY_METRO_AREA { get; set; } = new List<COUNTY_METRO_AREA>();

    [InverseProperty("Metro_FIPSNavigation")]
    public virtual ICollection<METRO_ANSWERS> METRO_ANSWERS { get; set; } = new List<METRO_ANSWERS>();
}