// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[PrimaryKey("HomeMatQuestionId", "NewMatQuestionId")]
public partial class MQ_APPEND
{
    [Key]
    public int HomeMatQuestionId { get; set; }

    [Key]
    public int NewMatQuestionId { get; set; }

    [Required]
    [StringLength(1)]
    public string InsertOrReplace { get; set; }

    public int ModelId { get; set; }
}