// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[PrimaryKey("TargetQuestionId", "BonusQuestionId")]
public partial class MQ_BONUS
{
    [Key]
    public int TargetQuestionId { get; set; }

    [Key]
    public int BonusQuestionId { get; set; }

    [Required]
    [StringLength(1)]
    public string Action { get; set; }

    public int ModelId { get; set; }
}