// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

public partial class NCSF_CONVERSION_MAPPINGS_ENTRY
{
    [Key]
    [StringLength(50)]
    public string Entry_Level_Titles { get; set; }

    public int Requirement_Id { get; set; }

    [InverseProperty("Entry_Level_TitlesNavigation")]
    public virtual ICollection<NCSF_ENTRY_TO_MID> NCSF_ENTRY_TO_MID { get; set; } = new List<NCSF_ENTRY_TO_MID>();
}