// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of NCSF_CATEGORY records
/// </summary>
[Index("NCSF_Function_Id", "NCSF_Category_Id", Name = "IX_NCSF_Category", IsUnique = true)]
public partial class NCSF_CATEGORY
{
    [Required]
    [StringLength(50)]
    public string NCSF_Function_Id { get; set; }

    [Required]
    [StringLength(50)]
    public string NCSF_Category_Id { get; set; }

    [Required]
    [StringLength(50)]
    public string NCSF_Category_Name { get; set; }

    [Required]
    [StringLength(500)]
    public string NCSF_Category_Description { get; set; }

    [Key]
    public int NCSF_Cat_Id { get; set; }

    public int Question_Group_Heading_Id { get; set; }

    [ForeignKey("NCSF_Function_Id")]
    [InverseProperty("NCSF_CATEGORY")]
    public virtual NCSF_FUNCTIONS NCSF_Function { get; set; }

    [InverseProperty("NCSF_Cat")]
    public virtual ICollection<NEW_REQUIREMENT> NEW_REQUIREMENT { get; set; } = new List<NEW_REQUIREMENT>();
}