// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    public partial class NETWORK_WARNINGS
    {
        [Key]
        public int Assessment_Id { get; set; }
        [Key]
        public int Id { get; set; }
        [StringLength(2000)]
        public string WarningText { get; set; }

        [ForeignKey(nameof(Assessment_Id))]
        [InverseProperty(nameof(ASSESSMENTS.NETWORK_WARNINGS))]
        public virtual ASSESSMENTS Assessment_ { get; set; }
    }
}