// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    /// <summary>
    /// A collection of NEW_REQUIREMENT records
    /// </summary>
    public partial class NEW_REQUIREMENT
    {
        public NEW_REQUIREMENT()
        {
            FINANCIAL_REQUIREMENTS = new HashSet<FINANCIAL_REQUIREMENTS>();
            NERC_RISK_RANKING = new HashSet<NERC_RISK_RANKING>();
            PARAMETER_REQUIREMENTS = new HashSet<PARAMETER_REQUIREMENTS>();
            REQUIREMENT_LEVELS = new HashSet<REQUIREMENT_LEVELS>();
            REQUIREMENT_QUESTIONS = new HashSet<REQUIREMENT_QUESTIONS>();
            REQUIREMENT_QUESTIONS_SETS = new HashSet<REQUIREMENT_QUESTIONS_SETS>();
            REQUIREMENT_REFERENCES = new HashSet<REQUIREMENT_REFERENCES>();
            REQUIREMENT_SETS = new HashSet<REQUIREMENT_SETS>();
            REQUIREMENT_SOURCE_FILES = new HashSet<REQUIREMENT_SOURCE_FILES>();
        }

        [Key]
        public int Requirement_Id { get; set; }
        [StringLength(250)]
        public string Requirement_Title { get; set; }
        [Required]
        public string Requirement_Text { get; set; }
        public string Supplemental_Info { get; set; }
        [StringLength(250)]
        public string Standard_Category { get; set; }
        [StringLength(250)]
        public string Standard_Sub_Category { get; set; }
        public int? Weight { get; set; }
        public string Implementation_Recommendations { get; set; }
        [Required]
        [StringLength(50)]
        public string Original_Set_Name { get; set; }
        [MaxLength(20)]
        public byte[] Text_Hash { get; set; }
        public int? NCSF_Cat_Id { get; set; }
        public int? NCSF_Number { get; set; }
        [MaxLength(32)]
        public byte[] Supp_Hash { get; set; }
        public int? Ranking { get; set; }
        public int Question_Group_Heading_Id { get; set; }
        public string ExaminationApproach { get; set; }
        public int? Old_Id_For_Copy { get; set; }

        [ForeignKey(nameof(NCSF_Cat_Id))]
        [InverseProperty(nameof(NCSF_CATEGORY.NEW_REQUIREMENT))]
        public virtual NCSF_CATEGORY NCSF_Cat_ { get; set; }
        [ForeignKey(nameof(Original_Set_Name))]
        [InverseProperty(nameof(SETS.NEW_REQUIREMENT))]
        public virtual SETS Original_Set_NameNavigation { get; set; }
        public virtual QUESTION_GROUP_HEADING Question_Group_Heading_ { get; set; }
        [ForeignKey(nameof(Standard_Category))]
        [InverseProperty(nameof(STANDARD_CATEGORY.NEW_REQUIREMENT))]
        public virtual STANDARD_CATEGORY Standard_CategoryNavigation { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<FINANCIAL_REQUIREMENTS> FINANCIAL_REQUIREMENTS { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<NERC_RISK_RANKING> NERC_RISK_RANKING { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<PARAMETER_REQUIREMENTS> PARAMETER_REQUIREMENTS { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<REQUIREMENT_LEVELS> REQUIREMENT_LEVELS { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<REQUIREMENT_QUESTIONS> REQUIREMENT_QUESTIONS { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<REQUIREMENT_QUESTIONS_SETS> REQUIREMENT_QUESTIONS_SETS { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<REQUIREMENT_REFERENCES> REQUIREMENT_REFERENCES { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<REQUIREMENT_SETS> REQUIREMENT_SETS { get; set; }
        [InverseProperty("Requirement_")]
        public virtual ICollection<REQUIREMENT_SOURCE_FILES> REQUIREMENT_SOURCE_FILES { get; set; }
    }
}