// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    /// <summary>
    /// A collection of NEW_QUESTION_LEVELS records
    /// </summary>
    public partial class NEW_QUESTION_LEVELS
    {
        [Key]
        public int New_Question_Set_Id { get; set; }
        /// <summary>
        /// The Universal Sal Level is used to
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Universal_Sal_Level { get; set; }
        public int? IgnoreMe { get; set; }

        [ForeignKey(nameof(New_Question_Set_Id))]
        [InverseProperty(nameof(NEW_QUESTION_SETS.NEW_QUESTION_LEVELS))]
        public virtual NEW_QUESTION_SETS New_Question_Set_ { get; set; }
        [ForeignKey(nameof(Universal_Sal_Level))]
        [InverseProperty(nameof(UNIVERSAL_SAL_LEVEL.NEW_QUESTION_LEVELS))]
        public virtual UNIVERSAL_SAL_LEVEL Universal_Sal_LevelNavigation { get; set; }
    }
}