// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayerCore.Model
{
    public partial class NIST_SAL_QUESTION_ANSWERS
    {
        [Key]
        public int Assessment_Id { get; set; }
        [Key]
        public int Question_Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Question_Answer { get; set; }

        [ForeignKey(nameof(Assessment_Id))]
        [InverseProperty(nameof(STANDARD_SELECTION.NIST_SAL_QUESTION_ANSWERS))]
        public virtual STANDARD_SELECTION Assessment_ { get; set; }
        [ForeignKey(nameof(Question_Id))]
        [InverseProperty(nameof(NIST_SAL_QUESTIONS.NIST_SAL_QUESTION_ANSWERS))]
        public virtual NIST_SAL_QUESTIONS Question_ { get; set; }
    }
}