// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    /// <summary>
    /// A collection of QUESTION_GROUP_HEADING records
    /// </summary>
    public partial class QUESTION_GROUP_HEADING
    {
        public QUESTION_GROUP_HEADING()
        {
            NEW_REQUIREMENT = new HashSet<NEW_REQUIREMENT>();
            UNIVERSAL_SUB_CATEGORY_HEADINGS = new HashSet<UNIVERSAL_SUB_CATEGORY_HEADINGS>();
        }

        /// <summary>
        /// The Question Group Heading is used to
        /// </summary>
        [Key]
        [Column("Question_Group_Heading")]
        [StringLength(250)]
        public string Question_Group_Heading1 { get; set; }
        /// <summary>
        /// The Std Ref is used to
        /// </summary>
        [Required]
        [StringLength(10)]
        public string Std_Ref { get; set; }
        /// <summary>
        /// The Universal Weight is used to
        /// </summary>
        public int Universal_Weight { get; set; }
        /// <summary>
        /// The Question Group Heading Id is used to
        /// </summary>
        public int Question_Group_Heading_Id { get; set; }
        public bool Is_Custom { get; set; }

        public virtual ICollection<NEW_REQUIREMENT> NEW_REQUIREMENT { get; set; }
        public virtual ICollection<UNIVERSAL_SUB_CATEGORY_HEADINGS> UNIVERSAL_SUB_CATEGORY_HEADINGS { get; set; }
    }
}