// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[PrimaryKey("Assessment_Id", "Report_Section_Id")]
public partial class REPORT_DETAIL_SECTION_SELECTION
{
    [Key]
    public int Assessment_Id { get; set; }

    [Key]
    public int Report_Section_Id { get; set; }

    public int Report_Section_Order { get; set; }

    public bool Is_Selected { get; set; }

    [ForeignKey("Assessment_Id")]
    [InverseProperty("REPORT_DETAIL_SECTION_SELECTION")]
    public virtual ASSESSMENTS Assessment { get; set; }

    [ForeignKey("Report_Section_Id")]
    [InverseProperty("REPORT_DETAIL_SECTION_SELECTION")]
    public virtual REPORT_DETAIL_SECTIONS Report_Section { get; set; }
}