// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    public partial class REPORT_DETAIL_SECTION_SELECTION
    {
        [Key]
        public int Assessment_Id { get; set; }
        [Key]
        public int Report_Section_Id { get; set; }
        public int Report_Section_Order { get; set; }
        public bool Is_Selected { get; set; }

        [ForeignKey(nameof(Assessment_Id))]
        [InverseProperty(nameof(ASSESSMENTS.REPORT_DETAIL_SECTION_SELECTION))]
        public virtual ASSESSMENTS Assessment_ { get; set; }
        [ForeignKey(nameof(Report_Section_Id))]
        [InverseProperty(nameof(REPORT_DETAIL_SECTIONS.REPORT_DETAIL_SECTION_SELECTION))]
        public virtual REPORT_DETAIL_SECTIONS Report_Section_ { get; set; }
    }
}