// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer
{
    public partial class RequirementsCustomFramework
    {
        public int Requirement_Id { get; set; }
        [StringLength(250)]
        public string Requirement_Title { get; set; }
        [Required]
        public string Requirement_Text { get; set; }
        public string Supplemental_Info { get; set; }
        [Required]
        [StringLength(250)]
        public string Question_Group_Heading { get; set; }
        [StringLength(250)]
        public string Standard_Category { get; set; }
        [StringLength(250)]
        public string Standard_Sub_Category { get; set; }
        public int? Weight { get; set; }
        public int Default_Standard_Level { get; set; }
        public string Implementation_Recommendations { get; set; }
        [Required]
        [StringLength(50)]
        public string Original_Set_Name { get; set; }
        [MaxLength(20)]
        public byte[] Text_Hash { get; set; }
        public int? NCSF_Cat_Id { get; set; }
        public int? NCSF_Number { get; set; }
        [MaxLength(32)]
        public byte[] Supp_Hash { get; set; }
        public int? Ranking { get; set; }
        public int? Assessment_Id { get; set; }
    }
}