// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of STANDARD_TO_UNIVERSAL_MAP records
/// </summary>
[PrimaryKey("Universal_Sal_Level", "Standard_Level")]
public partial class STANDARD_TO_UNIVERSAL_MAP
{
    /// <summary>
    /// The Universal Sal Level is used to
    /// </summary>
    [Key]
    [StringLength(50)]
    public string Universal_Sal_Level { get; set; }

    /// <summary>
    /// The Standard Level is used to
    /// </summary>
    [Key]
    [StringLength(50)]
    public string Standard_Level { get; set; }

    [ForeignKey("Standard_Level")]
    [InverseProperty("STANDARD_TO_UNIVERSAL_MAP")]
    public virtual STANDARD_SPECIFIC_LEVEL Standard_LevelNavigation { get; set; }

    [ForeignKey("Universal_Sal_Level")]
    [InverseProperty("STANDARD_TO_UNIVERSAL_MAP")]
    public virtual UNIVERSAL_SAL_LEVEL Universal_Sal_LevelNavigation { get; set; }
}