// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of STATES_AND_PROVINCES records
/// </summary>
public partial class STATES_AND_PROVINCES
{
    [Required]
    [StringLength(5)]
    public string ISO_code { get; set; }

    [Required]
    [StringLength(50)]
    public string Display_Name { get; set; }

    [Key]
    public int STATES_AND_PROVINCES_ID { get; set; }

    [StringLength(5)]
    public string Country_Code { get; set; }

    [ForeignKey("Country_Code")]
    [InverseProperty("STATES_AND_PROVINCES")]
    public virtual COUNTRIES Country_CodeNavigation { get; set; }
}