// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class STATE_REGION
    {
        public STATE_REGION()
        {
            COUNTIES = new HashSet<COUNTIES>();
            REGION_ANSWERS = new HashSet<REGION_ANSWERS>();
        }

        [Key]
        [StringLength(50)]
        public string State { get; set; }
        [Key]
        [StringLength(50)]
        public string RegionCode { get; set; }
        [Required]
        [StringLength(50)]
        public string RegionName { get; set; }

        [InverseProperty("STATE_REGION")]
        public virtual ICollection<COUNTIES> COUNTIES { get; set; }
        [InverseProperty("STATE_REGION")]
        public virtual ICollection<REGION_ANSWERS> REGION_ANSWERS { get; set; }
    }
}