// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class StateRegion
    {
        public StateRegion()
        {
            Counties = new HashSet<Counties>();
            ExtendedDemographicRegionAnswers = new HashSet<ExtendedDemographicRegionAnswers>();
        }

        [Key]
        public int TBRB_Region_ISO_Code { get; set; }
        [Required]
        [StringLength(10)]
        public string ISO_StateCode { get; set; }
        [StringLength(10)]
        public string ISO_RegionCode { get; set; }
        [Required]
        [StringLength(150)]
        public string RegionName { get; set; }

        [InverseProperty("TBRB_Region_ISO_CodeNavigation")]
        public virtual ICollection<Counties> Counties { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<ExtendedDemographicRegionAnswers> ExtendedDemographicRegionAnswers { get; set; }
    }
}