// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class TTP
    {
        public TTP()
        {
            TTP_MAT_QUESTION = new HashSet<TTP_MAT_QUESTION>();
        }

        [Key]
        [StringLength(100)]
        public string TTP_Code { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        [StringLength(100)]
        public string URL { get; set; }

        [InverseProperty("TTP_CodeNavigation")]
        public virtual ICollection<TTP_MAT_QUESTION> TTP_MAT_QUESTION { get; set; }
    }
}