// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    /// <summary>
    /// A collection of UNIVERSAL_SAL_LEVEL records
    /// </summary>
    [Index("Full_Name_Sal", Name = "IX_UNIVERSAL_SAL_LEVEL", IsUnique = true)]
    public partial class UNIVERSAL_SAL_LEVEL
    {
        public UNIVERSAL_SAL_LEVEL()
        {
            NEW_QUESTION = new HashSet<NEW_QUESTION>();
            NEW_QUESTION_LEVELS = new HashSet<NEW_QUESTION_LEVELS>();
            STANDARD_SELECTION = new HashSet<STANDARD_SELECTION>();
            Standard_Level = new HashSet<STANDARD_SPECIFIC_LEVEL>();
        }

        /// <summary>
        /// The Universal Sal Level is used to
        /// </summary>
        [Key]
        [Column("Universal_Sal_Level")]
        [StringLength(10)]
        [Unicode(false)]
        public string Universal_Sal_Level1 { get; set; }
        /// <summary>
        /// The Sal Level Order is used to
        /// </summary>
        public int Sal_Level_Order { get; set; }
        /// <summary>
        /// The Full Name Sal is used to
        /// </summary>
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Full_Name_Sal { get; set; }

        [InverseProperty("Universal_Sal_LevelNavigation")]
        public virtual ICollection<NEW_QUESTION> NEW_QUESTION { get; set; }
        [InverseProperty("Universal_Sal_LevelNavigation")]
        public virtual ICollection<NEW_QUESTION_LEVELS> NEW_QUESTION_LEVELS { get; set; }
        public virtual ICollection<STANDARD_SELECTION> STANDARD_SELECTION { get; set; }

        [ForeignKey("Universal_Sal_Level")]
        [InverseProperty("Universal_Sal_Level")]
        public virtual ICollection<STANDARD_SPECIFIC_LEVEL> Standard_Level { get; set; }
    }
}