// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

[PrimaryKey("UserId", "EmailSentDate")]
public partial class USER_EMAIL_HISTORY
{
    [Key]
    public int UserId { get; set; }

    [Key]
    public DateTime EmailSentDate { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("USER_EMAIL_HISTORY")]
    public virtual USERS User { get; set; }
}