// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_Assessments_For_UserResult
    {
        public int AssessmentId { get; set; }
        [StringLength(100)]
        public string AssessmentName { get; set; }
        public DateTime AssessmentDate { get; set; }
        public DateTime AssessmentCreatedDate { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public bool MarkedForReview { get; set; }
        public bool UseDiagram { get; set; }
        public bool UseStandard { get; set; }
        public bool UseMaturity { get; set; }
        [StringLength(30)]
        public string workflow { get; set; }
        [StringLength(100)]
        public string SelectedMaturityModel { get; set; }
        public bool? iseSubmitted { get; set; }
        public DateTime? submittedDate { get; set; }
        [StringLength(4000)]
        public string SelectedStandards { get; set; }
        public bool? AltTextMissing { get; set; }
        public int? UserId { get; set; }
        public bool? Done { get; set; }
        public bool? Favorite { get; set; }
    }
}
