// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_getFinancialQuestionsResult
    {
        public string Requirement_title { get; set; }
        public string Requirement_text { get; set; }
        public string Answer_text { get; set; }
        public string MaturityLevel { get; set; }
    }
}
