// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_getFinancialQuestionsResult
    {
        [StringLength(250)]
        public string Requirement_title { get; set; }
        [StringLength(2147483647)]
        public string Requirement_text { get; set; }
        [StringLength(50)]
        public string Answer_text { get; set; }
        [StringLength(255)]
        public string MaturityLevel { get; set; }
    }
}
