// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_CyOTEQuestionsAnswersResult
    {
        public int Question_Level { get; set; }
        public int Mat_Question_Id { get; set; }
        public string Question_Title { get; set; }
        public string Question_Text { get; set; }
        public string Mat_Question_Type { get; set; }
        public int Sequence { get; set; }
        public string Answer_Text { get; set; }
        public string Free_Response_Answer { get; set; }
        public string Comment { get; set; }
        public int? Parent_Question_Id { get; set; }
        public string Supplemental_Info { get; set; }
    }
}
