// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_countsForLevelsByGroupMaturityModelResult
    {
        public int? GROUPING_ID { get; set; }
        public int Maturity_Level_Id { get; set; }
        [StringLength(50)]
        public string Answer_Text { get; set; }
        [StringLength(50)]
        public string Answer_Text2 { get; set; }
        public int? answer_count { get; set; }
    }
}
