// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_getRRASummaryByGoalOverallResult
    {
        public string Title { get; set; }
        public int qc { get; set; }
        public int Total { get; set; }
        public double Percent { get; set; }
    }
}
