// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_GetRawCountsForEachAssessment_StandardsResult
    {
        public int Assessment_Id { get; set; }
        public string Question_Group_Heading { get; set; }
        public string Answer_Text { get; set; }
        public int? Answer_Count { get; set; }
        public int? Total { get; set; }
        public int? Percentage { get; set; }
    }
}
