// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_financial_attributesResult
    {
        public int Assessment_Id { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
    }
}
