// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSETWebCore.DataLayer.Model
{
    public partial class usp_GetStandardsSummaryPageResult
    {
        public string Answer_Full_Name { get; set; }
        public string Short_Name { get; set; }
        public string Answer_Text { get; set; }
        public int qc { get; set; }
        public int Total { get; set; }
        public int Percent { get; set; }
    }
}
