// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model;

/// <summary>
/// A collection of WEIGHT records
/// </summary>
public partial class WEIGHT
{
    [Key]
    [Column("Weight")]
    public int Weight1 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Question_Normalized_Weight { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Requirement_Normalized_Weight { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Category_Normalized_Weight { get; set; }
}