using System;

namespace CSETWebCore.Model.Analytics;

public class AgFinding
{
    public int AnswerId { get; set; }
    public int FindingId { get; set; }
    public string Summary { get; set; }
    public string Issue { get; set; }
    public string Impact { get; set; }
    public string Recommendations { get; set; }
    public string Vulnerabilities { get; set; }
    public DateTime? ResolutionDate { get; set; }
    public int? ImportanceId { get; set; }
    public string Title { get; set; }
    public string Type { get; set; }
    public string Description { get; set; }
    public int? AutoGenerated { get; set; }
    public string Citations { get; set; }
    public string RiskArea { get; set; }
    public string SubRisk { get; set; }
    public string ActionItems { get; set; }
    public string SuppGuidance { get; set; }

}