FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app
COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://0.0.0.0:5000

RUN dotnet restore CSETWeb_Api/CSETWeb_ApiCore/CSETWebCore.Api.csproj

EXPOSE 5000
CMD ["dotnet", "watch", "--project", "CSETWeb_Api/CSETWeb_ApiCore/CSETWebCore.Api.csproj", "run", "--urls", "http://0.0.0.0:5000"]
