<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <AssemblyVersion>13.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Abstractions" Version="10.0.3" />
    <PackageReference Include="NJsonSchema" Version="11.5.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Snickler.EFCore" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSETWebCore.DataLayer\CSETWebCore.DataLayer.csproj" />
    <ProjectReference Include="..\CSETWebCore.Enum\CSETWebCore.Enum.csproj" />
  </ItemGroup>

  <ItemGroup>

    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <None Remove="Dashboard\" />
  </ItemGroup>
</Project>
